package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * CmdCompany generated by hbm2java
 */
@Entity
@Table(name = "cmd_company")
public class CmdCompany implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -3249779645949658793L;
    private long cmdCompanyId;
    @NotNull
    private OwnOwner ownOwner;
    @Size(max = 30)
    @NotNull
    private String cmdCompanyCode;
    @Size(max = 50)
    @NotNull
    private String cmdCompanyName;
    @Size(max = 20)
    private String cmdCompanySiret;
    @Size(max = 255)
    private String cmdCompanyComment;
    private String cmdCompanyVatNumber;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date cmdCompanyCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date cmdCompanyUpdateDate;
    @Size(max = 255)
    private String cmdCompanyVariable1;
    @Size(max = 255)
    private String cmdCompanyVariable2;
    @Size(max = 255)
    private String cmdCompanyVariable3;
    @Size(max = 255)
    private String cmdCompanyVariable4;
    @Size(max = 255)
    private String cmdCompanyVariable5;
    @Size(max = 255)
    private String cmdCompanyVariable6;
    @Size(max = 255)
    private String cmdCompanyVariable7;
    @Size(max = 255)
    private String cmdCompanyVariable8;
    @Size(max = 255)
    private String cmdCompanyVariable9;
    @Size(max = 255)
    private String cmdCompanyVariable10;
    private AdrAddress adrAddress;
    private Set<CmdAccount> cmdAccounts = new HashSet<CmdAccount>(0);

    public CmdCompany() {
    }

    public CmdCompany(long cmdCompanyId, OwnOwner ownOwner,
                      String cmdCompanyCode) {
        this.cmdCompanyId = cmdCompanyId;
        this.ownOwner = ownOwner;
        this.cmdCompanyCode = cmdCompanyCode;
    }

    public CmdCompany(long cmdCompanyId, OwnOwner ownOwner,
                      String cmdCompanyCode, String cmdCompanySiret,
                      String cmdCompanyComment, Date cmdCompanyCreationDate,
                      Date cmdCompanyUpdateDate, String cmdCompanyVariable1,
                      String cmdCompanyVariable2, String cmdCompanyVariable3,
                      String cmdCompanyVariable4, String cmdCompanyVariable5,
                      String cmdCompanyVariable6, String cmdCompanyVariable7,
                      String cmdCompanyVariable8, String cmdCompanyVariable9,
                      String cmdCompanyVariable10, Set<CmdAccount> cmdAccounts) {
        this.cmdCompanyId = cmdCompanyId;
        this.ownOwner = ownOwner;
        this.cmdCompanyCode = cmdCompanyCode;
        this.cmdCompanySiret = cmdCompanySiret;
        this.cmdCompanyComment = cmdCompanyComment;
        this.cmdCompanyCreationDate = cmdCompanyCreationDate;
        this.cmdCompanyUpdateDate = cmdCompanyUpdateDate;
        this.cmdCompanyVariable1 = cmdCompanyVariable1;
        this.cmdCompanyVariable2 = cmdCompanyVariable2;
        this.cmdCompanyVariable3 = cmdCompanyVariable3;
        this.cmdCompanyVariable4 = cmdCompanyVariable4;
        this.cmdCompanyVariable5 = cmdCompanyVariable5;
        this.cmdCompanyVariable6 = cmdCompanyVariable6;
        this.cmdCompanyVariable7 = cmdCompanyVariable7;
        this.cmdCompanyVariable8 = cmdCompanyVariable8;
        this.cmdCompanyVariable9 = cmdCompanyVariable9;
        this.cmdCompanyVariable10 = cmdCompanyVariable10;
        this.cmdAccounts = cmdAccounts;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_cmd_company", allocationSize = 1)
    @Column(name = "cmd_companyid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getCmdCompanyId() {
        return this.cmdCompanyId;
    }

    public void setCmdCompanyId(long cmdCompanyId) {
        this.cmdCompanyId = cmdCompanyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cmd_companyownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @Column(name = "cmd_companycode", nullable = false, length = 30)
    public String getCmdCompanyCode() {
        return this.cmdCompanyCode;
    }

    public void setCmdCompanyCode(String cmdCompanyCode) {
        this.cmdCompanyCode = cmdCompanyCode;
    }

    @Column(name = "cmd_companysiret", length = 20)
    public String getCmdCompanySiret() {
        return this.cmdCompanySiret;
    }

    public void setCmdCompanySiret(String cmdCompanySiret) {
        this.cmdCompanySiret = cmdCompanySiret;
    }

    @Column(name = "cmd_companycomment")
    public String getCmdCompanyComment() {
        return this.cmdCompanyComment;
    }

    public void setCmdCompanyComment(String cmdCompanyComment) {
        this.cmdCompanyComment = cmdCompanyComment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cmd_companycreationdate")
    public Date getCmdCompanyCreationDate() {
        return this.cmdCompanyCreationDate;
    }

    public void setCmdCompanyCreationDate(Date cmdCompanyCreationDate) {
        this.cmdCompanyCreationDate = cmdCompanyCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cmd_companyupdatedate")
    public Date getCmdCompanyUpdateDate() {
        return this.cmdCompanyUpdateDate;
    }

    public void setCmdCompanyUpdateDate(Date cmdCompanyUpdateDate) {
        this.cmdCompanyUpdateDate = cmdCompanyUpdateDate;
    }

    @Column(name = "cmd_companyvariable1")
    public String getCmdCompanyVariable1() {
        return this.cmdCompanyVariable1;
    }

    public void setCmdCompanyVariable1(String cmdCompanyVariable1) {
        this.cmdCompanyVariable1 = cmdCompanyVariable1;
    }

    @Column(name = "cmd_companyvariable2")
    public String getCmdCompanyVariable2() {
        return this.cmdCompanyVariable2;
    }

    public void setCmdCompanyVariable2(String cmdCompanyVariable2) {
        this.cmdCompanyVariable2 = cmdCompanyVariable2;
    }

    @Column(name = "cmd_companyvariable3")
    public String getCmdCompanyVariable3() {
        return this.cmdCompanyVariable3;
    }

    public void setCmdCompanyVariable3(String cmdCompanyVariable3) {
        this.cmdCompanyVariable3 = cmdCompanyVariable3;
    }

    @Column(name = "cmd_companyvariable4")
    public String getCmdCompanyVariable4() {
        return this.cmdCompanyVariable4;
    }

    public void setCmdCompanyVariable4(String cmdCompanyVariable4) {
        this.cmdCompanyVariable4 = cmdCompanyVariable4;
    }

    @Column(name = "cmd_companyvariable5")
    public String getCmdCompanyVariable5() {
        return this.cmdCompanyVariable5;
    }

    public void setCmdCompanyVariable5(String cmdCompanyVariable5) {
        this.cmdCompanyVariable5 = cmdCompanyVariable5;
    }

    @Column(name = "cmd_companyvariable6")
    public String getCmdCompanyVariable6() {
        return this.cmdCompanyVariable6;
    }

    public void setCmdCompanyVariable6(String cmdCompanyVariable6) {
        this.cmdCompanyVariable6 = cmdCompanyVariable6;
    }

    @Column(name = "cmd_companyvariable7")
    public String getCmdCompanyVariable7() {
        return this.cmdCompanyVariable7;
    }

    public void setCmdCompanyVariable7(String cmdCompanyVariable7) {
        this.cmdCompanyVariable7 = cmdCompanyVariable7;
    }

    @Column(name = "cmd_companyvariable8")
    public String getCmdCompanyVariable8() {
        return this.cmdCompanyVariable8;
    }

    public void setCmdCompanyVariable8(String cmdCompanyVariable8) {
        this.cmdCompanyVariable8 = cmdCompanyVariable8;
    }

    @Column(name = "cmd_companyvariable9")
    public String getCmdCompanyVariable9() {
        return this.cmdCompanyVariable9;
    }

    public void setCmdCompanyVariable9(String cmdCompanyVariable9) {
        this.cmdCompanyVariable9 = cmdCompanyVariable9;
    }

    @Column(name = "cmd_companyvariable10")
    public String getCmdCompanyVariable10() {
        return this.cmdCompanyVariable10;
    }

    public void setCmdCompanyVariable10(String cmdCompanyVariable10) {
        this.cmdCompanyVariable10 = cmdCompanyVariable10;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cmdCompany")
    public Set<CmdAccount> getCmdAccounts() {
        return this.cmdAccounts;
    }

    public void setCmdAccounts(Set<CmdAccount> cmdAccounts) {
        this.cmdAccounts = cmdAccounts;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cmd_companyaddressid", nullable = false)
    public AdrAddress getAdrAddress() {
        return adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }

    @Column(name = "cmd_companyname", length = 50, nullable = false)
    public String getCmdCompanyName() {
        return cmdCompanyName;
    }

    public void setCmdCompanyName(String cmdCompanyName) {
        this.cmdCompanyName = cmdCompanyName;
    }

    @Column(name = "cmd_companyvatnumber")
    public String getCmdCompanyVatNumber() {
        return cmdCompanyVatNumber;
    }

    public void setCmdCompanyVatNumber(String cmdCompanyVatNumber) {
        this.cmdCompanyVatNumber = cmdCompanyVatNumber;
    }
}
