package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrmBlockType generated by hbm2java
 */
@Entity
@Table(name = "prm_blocktype", uniqueConstraints = {
        @UniqueConstraint(columnNames = "prm_blocktypecode")})
public class PrmBlockType implements java.io.Serializable {

    private long prmBlockTypeId;
    @NotNull
    private OwnOwner ownOwner;
    @Size(max = 30)
    @NotNull
    private String prmBlockTypeCode;
    @Size(max = 100)
    private String prmBlockTypeDescription;

    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date prmBlockTypeCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date prmBlockTypeUpdateDate;
    private Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs = new HashSet<CmdSaleOrderLineArc>(
            0);
    private Set<PdtProduct> pdtProducts = new HashSet<PdtProduct>(0);
    private Set<CmdSaleOrderStock> cmdSaleOrderStocks = new HashSet<CmdSaleOrderStock>(
            0);
    private Set<RcpReceptionLine> rcpReceptionLines = new HashSet<RcpReceptionLine>(
            0);
    private Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines = new HashSet<RcpPurshaseOrderLine>(
            0);
    private Set<RcpReceptionStockArc> rcpReceptionStockArcs = new HashSet<RcpReceptionStockArc>(
            0);
    private Set<StkStockReserved> stkStockReserveds = new HashSet<StkStockReserved>(
            0);
    private Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs = new HashSet<CmdSaleOrderStockArc>(
            0);
    private Set<RcpReceptionStock> rcpReceptionStocks = new HashSet<RcpReceptionStock>(
            0);
    private Set<StkStock> stkStocks = new HashSet<StkStock>(0);
    private Set<RcpReceptionLineArc> rcpReceptionLineArcs = new HashSet<RcpReceptionLineArc>(
            0);
    private Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs = new HashSet<RcpPurshaseOrderLineArc>(
            0);
    private Set<StkStockArc> stkStockArcs = new HashSet<StkStockArc>(0);
    private Set<CmdSaleOrderLine> cmdSaleOrderLines = new HashSet<CmdSaleOrderLine>(
            0);

    public PrmBlockType() {
    }

    public PrmBlockType(long prmBlockTypeId, OwnOwner ownOwner,
                        String prmBlockTypeCode) {
        this.prmBlockTypeId = prmBlockTypeId;
        this.ownOwner = ownOwner;
        this.prmBlockTypeCode = prmBlockTypeCode;
    }

    public PrmBlockType(long prmBlockTypeId, OwnOwner ownOwner,
                        String prmBlockTypeCode, String prmBlockTypeDescription,
                        Date prmBlockTypeCreationDate,
                        Date prmBlockTypeUpdateDate,
                        Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs,
                        Set<PdtProduct> pdtProducts,
                        Set<CmdSaleOrderStock> cmdSaleOrderStocks,
                        Set<RcpReceptionLine> rcpReceptionLines,
                        Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines,
                        Set<RcpReceptionStockArc> rcpReceptionStockArcs,
                        Set<StkStockReserved> stkStockReserveds,
                        Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs,
                        Set<RcpReceptionStock> rcpReceptionStocks, Set<StkStock> stkStocks,
                        Set<RcpReceptionLineArc> rcpReceptionLineArcs,
                        Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs,
                        Set<StkStockArc> stkStockArcs,
                        Set<CmdSaleOrderLine> cmdSaleOrderLines) {
        this.prmBlockTypeId = prmBlockTypeId;
        this.ownOwner = ownOwner;
        this.prmBlockTypeCode = prmBlockTypeCode;
        this.prmBlockTypeDescription = prmBlockTypeDescription;
        this.prmBlockTypeCreationDate = prmBlockTypeCreationDate;
        this.prmBlockTypeUpdateDate = prmBlockTypeUpdateDate;
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
        this.pdtProducts = pdtProducts;
        this.cmdSaleOrderStocks = cmdSaleOrderStocks;
        this.rcpReceptionLines = rcpReceptionLines;
        this.rcpPurshaseOrderLines = rcpPurshaseOrderLines;
        this.rcpReceptionStockArcs = rcpReceptionStockArcs;
        this.stkStockReserveds = stkStockReserveds;
        this.cmdSaleOrderStockArcs = cmdSaleOrderStockArcs;
        this.rcpReceptionStocks = rcpReceptionStocks;
        this.stkStocks = stkStocks;
        this.rcpReceptionLineArcs = rcpReceptionLineArcs;
        this.rcpPurshaseOrderLineArcs = rcpPurshaseOrderLineArcs;
        this.stkStockArcs = stkStockArcs;
        this.cmdSaleOrderLines = cmdSaleOrderLines;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_prm_blocktype", allocationSize = 1)
    @Column(name = "prm_blocktypeid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPrmBlockTypeId() {
        return this.prmBlockTypeId;
    }

    public void setPrmBlockTypeId(long prmBlockTypeId) {
        this.prmBlockTypeId = prmBlockTypeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prm_blocktypeownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @Column(name = "prm_blocktypecode", unique = true, nullable = false, length = 30)
    public String getPrmBlockTypeCode() {
        return this.prmBlockTypeCode;
    }

    public void setPrmBlockTypeCode(String prmBlockTypeCode) {
        this.prmBlockTypeCode = prmBlockTypeCode;
    }

    @Column(name = "prm_blocktypedescription", length = 100)
    public String getPrmBlockTypeDescription() {
        return this.prmBlockTypeDescription;
    }

    public void setPrmBlockTypeDescription(String prmBlockTypeDescription) {
        this.prmBlockTypeDescription = prmBlockTypeDescription;
    }



    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "prm_blocktypecreationdate")
    public Date getPrmBlockTypeCreationDate() {
        return this.prmBlockTypeCreationDate;
    }

    public void setPrmBlockTypeCreationDate(Date prmBlockTypeCreationDate) {
        this.prmBlockTypeCreationDate = prmBlockTypeCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "prm_blocktypeupdatedate")
    public Date getPrmBlockTypeUpdateDate() {
        return this.prmBlockTypeUpdateDate;
    }

    public void setPrmBlockTypeUpdateDate(Date prmBlockTypeUpdateDate) {
        this.prmBlockTypeUpdateDate = prmBlockTypeUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<CmdSaleOrderLineArc> getCmdSaleOrderLineArcs() {
        return this.cmdSaleOrderLineArcs;
    }

    public void setCmdSaleOrderLineArcs(
            Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs) {
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<PdtProduct> getPdtProducts() {
        return this.pdtProducts;
    }

    public void setPdtProducts(Set<PdtProduct> pdtProducts) {
        this.pdtProducts = pdtProducts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<CmdSaleOrderStock> getCmdSaleOrderStocks() {
        return this.cmdSaleOrderStocks;
    }

    public void setCmdSaleOrderStocks(Set<CmdSaleOrderStock> cmdSaleOrderStocks) {
        this.cmdSaleOrderStocks = cmdSaleOrderStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<RcpReceptionLine> getRcpReceptionLines() {
        return this.rcpReceptionLines;
    }

    public void setRcpReceptionLines(Set<RcpReceptionLine> rcpReceptionLines) {
        this.rcpReceptionLines = rcpReceptionLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<RcpPurshaseOrderLine> getRcpPurshaseOrderLines() {
        return this.rcpPurshaseOrderLines;
    }

    public void setRcpPurshaseOrderLines(
            Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines) {
        this.rcpPurshaseOrderLines = rcpPurshaseOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<RcpReceptionStockArc> getRcpReceptionStockArcs() {
        return this.rcpReceptionStockArcs;
    }

    public void setRcpReceptionStockArcs(
            Set<RcpReceptionStockArc> rcpReceptionStockArcs) {
        this.rcpReceptionStockArcs = rcpReceptionStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<StkStockReserved> getStkStockReserveds() {
        return this.stkStockReserveds;
    }

    public void setStkStockReserveds(Set<StkStockReserved> stkStockReserveds) {
        this.stkStockReserveds = stkStockReserveds;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<CmdSaleOrderStockArc> getCmdSaleOrderStockArcs() {
        return this.cmdSaleOrderStockArcs;
    }

    public void setCmdSaleOrderStockArcs(
            Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs) {
        this.cmdSaleOrderStockArcs = cmdSaleOrderStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<RcpReceptionStock> getRcpReceptionStocks() {
        return this.rcpReceptionStocks;
    }

    public void setRcpReceptionStocks(Set<RcpReceptionStock> rcpReceptionStocks) {
        this.rcpReceptionStocks = rcpReceptionStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<StkStock> getStkStocks() {
        return this.stkStocks;
    }

    public void setStkStocks(Set<StkStock> stkStocks) {
        this.stkStocks = stkStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<RcpReceptionLineArc> getRcpReceptionLineArcs() {
        return this.rcpReceptionLineArcs;
    }

    public void setRcpReceptionLineArcs(
            Set<RcpReceptionLineArc> rcpReceptionLineArcs) {
        this.rcpReceptionLineArcs = rcpReceptionLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<RcpPurshaseOrderLineArc> getRcpPurshaseOrderLineArcs() {
        return this.rcpPurshaseOrderLineArcs;
    }

    public void setRcpPurshaseOrderLineArcs(
            Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs) {
        this.rcpPurshaseOrderLineArcs = rcpPurshaseOrderLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<StkStockArc> getStkStockArcs() {
        return this.stkStockArcs;
    }

    public void setStkStockArcs(Set<StkStockArc> stkStockArcs) {
        this.stkStockArcs = stkStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmBlockType")
    public Set<CmdSaleOrderLine> getCmdSaleOrderLines() {
        return this.cmdSaleOrderLines;
    }

    public void setCmdSaleOrderLines(Set<CmdSaleOrderLine> cmdSaleOrderLines) {
        this.cmdSaleOrderLines = cmdSaleOrderLines;
    }
    @Override
    public boolean equals(Object object) {
        boolean result = false;
        if (object == null || object.getClass() != getClass()) {
            result = false;
        } else {
            PrmBlockType obj = (PrmBlockType) object;
            if (this.getPrmBlockTypeId() == obj.getPrmBlockTypeId()) {
                result = true;
            }
        }
        return result;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 7 * hash + (int) this.getPrmBlockTypeId();
        hash = 7 * hash + (int) this.getPrmBlockTypeId();
        return hash;
    }
}
