package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrmContact generated by hbm2java
 */
@Entity
@Table(name = "prm_contact")
public class PrmContact implements java.io.Serializable {

    private long prmContactId;
    @Size(max = 30)
    @NotNull
    private String prmContactName;
    @Size(max = 30)
    @NotNull
    private String prmContactSurName;
    @Size(max = 20)
    private String prmContactTel1;
    @Size(max = 20)
    private String prmContactTel2;
    @Size(max = 20)
    private String prmContactFax;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date prmContactCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date prmContactUpdateDate;
    @Size(max = 255)
    private String prmContactVariable1;
    @Size(max = 255)
    private String prmContactVariable2;
    @Size(max = 255)
    private String prmContactVariable3;
    @Size(max = 255)
    private String prmContactVariable4;
    @Size(max = 255)
    private String prmContactVariable5;
    @Size(max = 255)
    private String prmContactVariable6;
    @Size(max = 255)
    private String prmContactVariable7;
    @Size(max = 255)
    private String prmContactVariable8;
    @Size(max = 255)
    private String prmContactVariable9;
    @Size(max = 255)
    private String prmContactVariable10;


    private Long prmContactType;
    private String prmContactEmail;
    private String prmContactComment;
    private Boolean prmContactActive;
    private OwnOwner ownOwner;
    private Set<RcpSupplier> rcpSuppliers = new HashSet<RcpSupplier>(0);
    private Set<TrpTransport> trpTransports = new HashSet<TrpTransport>(0);


    public PrmContact() {
    }

    public void setPrmContactType(Long prmContactType) {
        this.prmContactType = prmContactType;
    }

    @Column(name = "prm_contacttype")
    public Long getPrmContactType() {
        return prmContactType;
    }

    public void setPrmContactEmail(String prmContactEmail) {
        this.prmContactEmail = prmContactEmail;
    }

    @Column(name = "prm_contactemail")
    public String getPrmContactEmail() {
        return prmContactEmail;
    }

    public void setPrmContactComment(String prmContactComment) {
        this.prmContactComment = prmContactComment;
    }

    @Column(name = "prm_contactcomment")
    public String getPrmContactComment() {
        return prmContactComment;
    }

    public PrmContact(long prmContactId, String prmContactName,
                      String prmContactSurName) {
        this.prmContactId = prmContactId;
        this.prmContactName = prmContactName;
        this.prmContactSurName = prmContactSurName;
    }



    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_prm_contact", allocationSize = 1)
    @Column(name = "prm_contactid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPrmContactId() {
        return this.prmContactId;
    }

    public void setPrmContactId(long prmContactId) {
        this.prmContactId = prmContactId;
    }

    @Column(name = "prm_contactname", nullable = false, length = 30)
    public String getPrmContactName() {
        return this.prmContactName;
    }

    public void setPrmContactName(String prmContactName) {
        this.prmContactName = prmContactName;
    }

    @Column(name = "prm_contactsurname", nullable = false, length = 30)
    public String getPrmContactSurName() {
        return this.prmContactSurName;
    }

    public void setPrmContactSurName(String prmContactSurName) {
        this.prmContactSurName = prmContactSurName;
    }

    @Column(name = "prm_contacttel1", length = 20)
    public String getPrmContactTel1() {
        return this.prmContactTel1;
    }

    public void setPrmContactTel1(String prmContactTel1) {
        this.prmContactTel1 = prmContactTel1;
    }

    @Column(name = "prm_contacttel2", length = 20)
    public String getPrmContactTel2() {
        return this.prmContactTel2;
    }

    public void setPrmContactTel2(String prmContactTel2) {
        this.prmContactTel2 = prmContactTel2;
    }

    @Column(name = "prm_contactfax", length = 20)
    public String getPrmContactFax() {
        return this.prmContactFax;
    }

    public void setPrmContactFax(String prmContactFax) {
        this.prmContactFax = prmContactFax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "prm_contactcreationdate")
    public Date getPrmContactCreationDate() {
        return this.prmContactCreationDate;
    }

    public void setPrmContactCreationDate(Date prmContactCreationDate) {
        this.prmContactCreationDate = prmContactCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "prm_contactupdatedate")
    public Date getPrmContactUpdateDate() {
        return this.prmContactUpdateDate;
    }

    public void setPrmContactUpdateDate(Date prmContactUpdateDate) {
        this.prmContactUpdateDate = prmContactUpdateDate;
    }

    @Column(name = "prm_contactvariable1")
    public String getPrmContactVariable1() {
        return this.prmContactVariable1;
    }

    public void setPrmContactVariable1(String prmContactVariable1) {
        this.prmContactVariable1 = prmContactVariable1;
    }

    @Column(name = "prm_contactvariable2")
    public String getPrmContactVariable2() {
        return this.prmContactVariable2;
    }

    public void setPrmContactVariable2(String prmContactVariable2) {
        this.prmContactVariable2 = prmContactVariable2;
    }

    @Column(name = "prm_contactvariable3")
    public String getPrmContactVariable3() {
        return this.prmContactVariable3;
    }

    public void setPrmContactVariable3(String prmContactVariable3) {
        this.prmContactVariable3 = prmContactVariable3;
    }

    @Column(name = "prm_contactvariable4")
    public String getPrmContactVariable4() {
        return this.prmContactVariable4;
    }

    public void setPrmContactVariable4(String prmContactVariable4) {
        this.prmContactVariable4 = prmContactVariable4;
    }

    @Column(name = "prm_contactvariable5")
    public String getPrmContactVariable5() {
        return this.prmContactVariable5;
    }

    public void setPrmContactVariable5(String prmContactVariable5) {
        this.prmContactVariable5 = prmContactVariable5;
    }

    @Column(name = "prm_contactvariable6")
    public String getPrmContactVariable6() {
        return this.prmContactVariable6;
    }

    public void setPrmContactVariable6(String prmContactVariable6) {
        this.prmContactVariable6 = prmContactVariable6;
    }

    @Column(name = "prm_contactvariable7")
    public String getPrmContactVariable7() {
        return this.prmContactVariable7;
    }

    public void setPrmContactVariable7(String prmContactVariable7) {
        this.prmContactVariable7 = prmContactVariable7;
    }

    @Column(name = "prm_contactvariable8")
    public String getPrmContactVariable8() {
        return this.prmContactVariable8;
    }

    public void setPrmContactVariable8(String prmContactVariable8) {
        this.prmContactVariable8 = prmContactVariable8;
    }

    @Column(name = "prm_contactvariable9")
    public String getPrmContactVariable9() {
        return this.prmContactVariable9;
    }

    public void setPrmContactVariable9(String prmContactVariable9) {
        this.prmContactVariable9 = prmContactVariable9;
    }

    @Column(name = "prm_contactvariable10")
    public String getPrmContactVariable10() {
        return this.prmContactVariable10;
    }

    public void setPrmContactVariable10(String prmContactVariable10) {
        this.prmContactVariable10 = prmContactVariable10;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmContact")
    public Set<RcpSupplier> getRcpSuppliers() {
        return this.rcpSuppliers;
    }

    public void setRcpSuppliers(Set<RcpSupplier> rcpSuppliers) {
        this.rcpSuppliers = rcpSuppliers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "prmContact")
    public Set<TrpTransport> getTrpTransports() {
        return this.trpTransports;
    }

    public void setTrpTransports(Set<TrpTransport> trpTransports) {
        this.trpTransports = trpTransports;
    }
    @Column(name = "prm_contactactive")

    public Boolean getPrmContactActive() {
        return prmContactActive;
    }

    public void setPrmContactActive(Boolean prmContactActive) {
        this.prmContactActive = prmContactActive;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prm_contactownerid")
    public OwnOwner getOwnOwner() {
        return ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }
}
