package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.HashSet;
import java.util.Set;

/**
 * PrmOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "prm_orderstatus", uniqueConstraints = {@UniqueConstraint(columnNames = "prm_orderstatuscode")})
public class PrmOrderStatus implements java.io.Serializable {

    private long prmOrderStatusId;
    @Size(max = 30)
    @NotNull
    private String prmOrderStatusCode;
    @Size(max = 255)
    private String prmOrderStatusDescription;
    @NotNull
    private boolean prmOrderStatusOrderType;
    private Boolean prmOrderStatusArchivable;
    private OrgOrganisation orgOrganisation;


    public PrmOrderStatus() {
    }

    public PrmOrderStatus(long prmOrderStatusId, String prmOrderStatusCode,
                          boolean prmOrderStatusOrderType) {
        this.prmOrderStatusId = prmOrderStatusId;
        this.prmOrderStatusCode = prmOrderStatusCode;
        this.prmOrderStatusOrderType = prmOrderStatusOrderType;
    }


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_prm_orderstatus", allocationSize = 1)
    @Column(name = "prm_orderstatusid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPrmOrderStatusId() {
        return this.prmOrderStatusId;
    }

    public void setPrmOrderStatusId(long prmOrderStatusId) {
        this.prmOrderStatusId = prmOrderStatusId;
    }

    @Column(name = "prm_orderstatuscode", unique = true, nullable = false, length = 30)
    public String getPrmOrderStatusCode() {
        return this.prmOrderStatusCode;
    }

    public void setPrmOrderStatusCode(String prmOrderStatusCode) {
        this.prmOrderStatusCode = prmOrderStatusCode;
    }

    @Column(name = "prm_orderstatusdescription")
    public String getPrmOrderStatusDescription() {
        return this.prmOrderStatusDescription;
    }

    public void setPrmOrderStatusDescription(String prmOrderStatusDescription) {
        this.prmOrderStatusDescription = prmOrderStatusDescription;
    }

    @Column(name = "prm_orderstatusordertype", nullable = false, precision = 1, scale = 0)
    public boolean isPrmOrderStatusOrderType() {
        return this.prmOrderStatusOrderType;
    }

    public void setPrmOrderStatusOrderType(boolean prmOrderStatusOrderType) {
        this.prmOrderStatusOrderType = prmOrderStatusOrderType;
    }
    @Column(name = "prm_orderstatusarchivable", precision = 1, scale = 0)
    public Boolean getPrmOrderStatusArchivable() {
        return prmOrderStatusArchivable;
    }

    public void setPrmOrderStatusArchivable(Boolean prmOrderStatusArchivable) {
        this.prmOrderStatusArchivable = prmOrderStatusArchivable;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prm_orderstatusorganisationid")
    public OrgOrganisation getOrgOrganisation() {
        return orgOrganisation;
    }

    public void setOrgOrganisation(OrgOrganisation orgOrganisation) {
        this.orgOrganisation = orgOrganisation;
    }
}
