package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;

/**
 * StkStock generated by hbm2java
 */
@Entity
@Table(name = "stk_stock")
public class StkStock implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private long stkStockId;
    @NotNull
    private OwnOwner ownOwner;
    @NotNull
    private PdtProduct pdtProduct;
    private PdtUom pdtUom;

    private StkContainer stkContainer;

    @Max(999999999)
    @NotNull
    private BigDecimal stkStockQuantity;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date stkStockReceptionDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date stkStockCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date stkStockUpdateDate;
    @Size(max = 255)
    private String stkStockVariable1;
    @Size(max = 255)
    private String stkStockVariable2;
    @Size(max = 255)
    private String stkStockVariable3;
    @Size(max = 255)
    private String stkStockVariable4;
    @Size(max = 255)
    private String stkStockVariable5;
    @Size(max = 255)
    private String stkStockVariable6;
    @Size(max = 255)
    private String stkStockVariable7;
    @Size(max = 255)
    private String stkStockVariable8;
    @Size(max = 255)
    private String stkStockVariable9;
    @Size(max = 255)
    private String stkStockVariable10;


    @Size(max = 255)
    private String stkStockComment;
    private Boolean stkStockActive;


    public StkStock() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_stk_stock", allocationSize = 1)
    @Column(name = "stk_stockid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getStkStockId() {
        return this.stkStockId;
    }

    public void setStkStockId(long stkStockId) {
        this.stkStockId = stkStockId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockproductid", nullable = false)
    public PdtProduct getPdtProduct() {
        return this.pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockuomid")
    public PdtUom getPdtUom() {
        return this.pdtUom;
    }

    public void setPdtUom(PdtUom pdtUom) {
        this.pdtUom = pdtUom;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockcontainerid")
    public StkContainer getStkContainer() {
        return this.stkContainer;
    }

    public void setStkContainer(StkContainer stkContainer) {
        this.stkContainer = stkContainer;
    }

    @Column(name = "stk_stockquantity", nullable = false, precision = 17, scale = 5)
    public BigDecimal getStkStockQuantity() {
        return this.stkStockQuantity;
    }

    public void setStkStockQuantity(BigDecimal stkStockQuantity) {
        this.stkStockQuantity = stkStockQuantity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "stk_stockreceptiondate")
    public Date getStkStockReceptionDate() {
        return this.stkStockReceptionDate;
    }

    public void setStkStockReceptionDate(Date stkStockReceptionDate) {
        this.stkStockReceptionDate = stkStockReceptionDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "stk_stockcreationdate")
    public Date getStkStockCreationDate() {
        return this.stkStockCreationDate;
    }

    public void setStkStockCreationDate(Date stkStockCreationDate) {
        this.stkStockCreationDate = stkStockCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "stk_stockupdatedate")
    public Date getStkStockUpdateDate() {
        return this.stkStockUpdateDate;
    }

    public void setStkStockUpdateDate(Date stkStockUpdateDate) {
        this.stkStockUpdateDate = stkStockUpdateDate;
    }

    @Column(name = "stk_stockvariable1")
    public String getStkStockVariable1() {
        return this.stkStockVariable1;
    }

    public void setStkStockVariable1(String stkStockVariable1) {
        this.stkStockVariable1 = stkStockVariable1;
    }

    @Column(name = "stk_stockvariable2")
    public String getStkStockVariable2() {
        return this.stkStockVariable2;
    }

    public void setStkStockVariable2(String stkStockVariable2) {
        this.stkStockVariable2 = stkStockVariable2;
    }

    @Column(name = "stk_stockvariable3")
    public String getStkStockVariable3() {
        return this.stkStockVariable3;
    }

    public void setStkStockVariable3(String stkStockVariable3) {
        this.stkStockVariable3 = stkStockVariable3;
    }

    @Column(name = "stk_stockvariable4")
    public String getStkStockVariable4() {
        return this.stkStockVariable4;
    }

    public void setStkStockVariable4(String stkStockVariable4) {
        this.stkStockVariable4 = stkStockVariable4;
    }

    @Column(name = "stk_stockvariable5")
    public String getStkStockVariable5() {
        return this.stkStockVariable5;
    }

    public void setStkStockVariable5(String stkStockVariable5) {
        this.stkStockVariable5 = stkStockVariable5;
    }

    @Column(name = "stk_stockvariable6")
    public String getStkStockVariable6() {
        return this.stkStockVariable6;
    }

    public void setStkStockVariable6(String stkStockVariable6) {
        this.stkStockVariable6 = stkStockVariable6;
    }

    @Column(name = "stk_stockvariable7")
    public String getStkStockVariable7() {
        return this.stkStockVariable7;
    }

    public void setStkStockVariable7(String stkStockVariable7) {
        this.stkStockVariable7 = stkStockVariable7;
    }

    @Column(name = "stk_stockvariable8")
    public String getStkStockVariable8() {
        return this.stkStockVariable8;
    }

    public void setStkStockVariable8(String stkStockVariable8) {
        this.stkStockVariable8 = stkStockVariable8;
    }

    @Column(name = "stk_stockvariable9")
    public String getStkStockVariable9() {
        return this.stkStockVariable9;
    }

    public void setStkStockVariable9(String stkStockVariable9) {
        this.stkStockVariable9 = stkStockVariable9;
    }

    @Column(name = "stk_stockvariable10")
    public String getStkStockVariable10() {
        return this.stkStockVariable10;
    }

    public void setStkStockVariable10(String stkStockVariable10) {
        this.stkStockVariable10 = stkStockVariable10;
    }

    @Column(name = "stk_stockcomment", length = 255)
    public String getStkStockComment() {
        return stkStockComment;
    }

    public void setStkStockComment(String stkStockComment) {
        this.stkStockComment = stkStockComment;
    }

    @Column(name = "stk_stockactive")
    public Boolean getStkStockActive() {
        return stkStockActive;
    }

    public void setStkStockActive(Boolean stkStockActive) {
        this.stkStockActive = stkStockActive;
    }
}
