package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrpTransport generated by hbm2java
 */
@Entity
@Table(name = "trp_transport", uniqueConstraints = @UniqueConstraint(columnNames = "trp_transportcode"))
public class TrpTransport implements java.io.Serializable {

    private long trpTransportId;
    private com.sinno.ems.entities.PrmContact prmContact;
    @Size(max = 30)
    @NotNull
    private String trpTransportCode;
    private String trpTransportName;
    private AdrAddress adrAddress;
    @Size(max = 255)
    private String trpTransportDescription;
    @Max(999999999)
    private BigDecimal trpTransportSiret;
    @Size(max = 255)
    private String trpTransportComment;
    private PrmEdi prmEdi;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date trpTransportCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date trpTransportUpdateDate;

    @NotNull
    private Boolean trpTransportIsActive;

    @Size(max = 255)
    private String trpTransportVariable1;
    @Size(max = 255)
    private String trpTransportVariable2;
    @Size(max = 255)
    private String trpTransportVariable3;
    @Size(max = 255)
    private String trpTransportVariable4;
    @Size(max = 255)
    private String trpTransportVariable5;
    @Size(max = 255)
    private String trpTransportVariable6;
    @Size(max = 255)
    private String trpTransportVariable7;
    @Size(max = 255)
    private String trpTransportVariable8;
    @Size(max = 255)
    private String trpTransportVariable9;
    @Size(max = 255)
    private String trpTransportVariable10;
    private Set<RcpSupplier> rcpSuppliers = new HashSet<RcpSupplier>(0);
    private Set<RcpPurshaseOrder> rcpPurshaseOrders = new HashSet<RcpPurshaseOrder>(
            0);
    private Set<CmdAccount> cmdAccounts = new HashSet<CmdAccount>(0);
    private Set<RcpReceptionArc> rcpReceptionArcs = new HashSet<RcpReceptionArc>(
            0);
    private Set<RcpReception> rcpReceptions = new HashSet<RcpReception>(0);
    private Set<RcpPurshaseOrderArc> rcpPurshaseOrderArcs = new HashSet<RcpPurshaseOrderArc>(
            0);
    private Set<CmdSaleOrderArc> cmdSaleOrderArcs = new HashSet<CmdSaleOrderArc>(
            0);
    private Set<CmdSaleOrder> cmdSaleOrders = new HashSet<CmdSaleOrder>(0);
    private Set<CmdSaleOrderLine> cmdSaleOrderLines = new HashSet<CmdSaleOrderLine>(
            0);
    private Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs = new HashSet<CmdSaleOrderLineArc>(
            0);

    public TrpTransport() {
    }

    public TrpTransport(long trpTransportId, String trpTransportCode) {
        this.trpTransportId = trpTransportId;
        this.trpTransportCode = trpTransportCode;
    }

    public TrpTransport(long trpTransportId, com.sinno.ems.entities.PrmContact prmContact,
                        String trpTransportCode, String trpTransportDescription,
                        BigDecimal trpTransportSiret, String trpTransportComment,
                        PrmEdi prmEdi, Date trpTransportCreationDate,
                        Date trpTransportUpdateDate, String trpTransportVariable1,
                        String trpTransportVariable2, String trpTransportVariable3,
                        String trpTransportVariable4, String trpTransportVariable5,
                        String trpTransportVariable6, String trpTransportVariable7,
                        String trpTransportVariable8, String trpTransportVariable9,
                        String trpTransportVariable10, Set<RcpSupplier> rcpSuppliers,
                        Set<RcpPurshaseOrder> rcpPurshaseOrders,
                        Set<CmdAccount> cmdAccounts, Set<RcpReceptionArc> rcpReceptionArcs,
                        Set<RcpReception> rcpReceptions,
                        Set<RcpPurshaseOrderArc> rcpPurshaseOrderArcs,
                        Set<CmdSaleOrderArc> cmdSaleOrderArcs,
                        Set<CmdSaleOrder> cmdSaleOrders,
                        Set<CmdSaleOrderLine> cmdSaleOrderLines,
                        Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs) {
        this.trpTransportId = trpTransportId;
        this.prmContact = prmContact;
        this.trpTransportCode = trpTransportCode;
        this.trpTransportDescription = trpTransportDescription;
        this.trpTransportSiret = trpTransportSiret;
        this.trpTransportComment = trpTransportComment;
        this.prmEdi = prmEdi;
        this.trpTransportCreationDate = trpTransportCreationDate;
        this.trpTransportUpdateDate = trpTransportUpdateDate;
        this.trpTransportVariable1 = trpTransportVariable1;
        this.trpTransportVariable2 = trpTransportVariable2;
        this.trpTransportVariable3 = trpTransportVariable3;
        this.trpTransportVariable4 = trpTransportVariable4;
        this.trpTransportVariable5 = trpTransportVariable5;
        this.trpTransportVariable6 = trpTransportVariable6;
        this.trpTransportVariable7 = trpTransportVariable7;
        this.trpTransportVariable8 = trpTransportVariable8;
        this.trpTransportVariable9 = trpTransportVariable9;
        this.trpTransportVariable10 = trpTransportVariable10;
        this.rcpSuppliers = rcpSuppliers;
        this.rcpPurshaseOrders = rcpPurshaseOrders;
        this.cmdAccounts = cmdAccounts;
        this.rcpReceptionArcs = rcpReceptionArcs;
        this.rcpReceptions = rcpReceptions;
        this.rcpPurshaseOrderArcs = rcpPurshaseOrderArcs;
        this.cmdSaleOrderArcs = cmdSaleOrderArcs;
        this.cmdSaleOrders = cmdSaleOrders;
        this.cmdSaleOrderLines = cmdSaleOrderLines;
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_trp_transport", allocationSize = 1)
    @Column(name = "trp_transportid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getTrpTransportId() {
        return this.trpTransportId;
    }

    public void setTrpTransportId(long trpTransportId) {
        this.trpTransportId = trpTransportId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trp_transportcontactid")
    public com.sinno.ems.entities.PrmContact getPrmContact() {
        return this.prmContact;
    }

    public void setPrmContact(com.sinno.ems.entities.PrmContact prmContact) {
        this.prmContact = prmContact;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trp_transportaddressid", nullable = false)
    public AdrAddress getAdrAddress() {
        return adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }

    @Column(name = "trp_transportisactive", nullable = false)
    public Boolean getTrpTransportIsActive() {
        return trpTransportIsActive;
    }
    public void setTrpTransportIsActive(Boolean trpTransportIsActive) {
        this.trpTransportIsActive = trpTransportIsActive;
    }

    @Column(name = "trp_transportcode", unique = true, nullable = false, length = 30)
    public String getTrpTransportCode() {
        return this.trpTransportCode;
    }

    public void setTrpTransportCode(String trpTransportCode) {
        this.trpTransportCode = trpTransportCode;
    }

    @Column(name = "trp_transportdescription")
    public String getTrpTransportDescription() {
        return this.trpTransportDescription;
    }

    public void setTrpTransportDescription(String trpTransportDescription) {
        this.trpTransportDescription = trpTransportDescription;
    }

    @Column(name = "trp_transportsiret", precision = 20, scale = 0)
    public BigDecimal getTrpTransportSiret() {
        return this.trpTransportSiret;
    }

    public void setTrpTransportSiret(BigDecimal trpTransportSiret) {
        this.trpTransportSiret = trpTransportSiret;
    }

    @Column(name = "trp_transportcomment")
    public String getTrpTransportComment() {
        return this.trpTransportComment;
    }

    public void setTrpTransportComment(String trpTransportComment) {
        this.trpTransportComment = trpTransportComment;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trp_transportediid")
    public PrmEdi getPrmEdi() {
        return this.prmEdi;
    }

    public void setPrmEdi(PrmEdi prmEdi) {
        this.prmEdi = prmEdi;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "trp_transportcreationdate")
    public Date getTrpTransportCreationDate() {
        return this.trpTransportCreationDate;
    }

    public void setTrpTransportCreationDate(Date trpTransportCreationDate) {
        this.trpTransportCreationDate = trpTransportCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "trp_transportupdatedate")
    public Date getTrpTransportUpdateDate() {
        return this.trpTransportUpdateDate;
    }

    public void setTrpTransportUpdateDate(Date trpTransportUpdateDate) {
        this.trpTransportUpdateDate = trpTransportUpdateDate;
    }

    @Column(name = "trp_transportvariable1")
    public String getTrpTransportVariable1() {
        return this.trpTransportVariable1;
    }

    public void setTrpTransportVariable1(String trpTransportVariable1) {
        this.trpTransportVariable1 = trpTransportVariable1;
    }

    @Column(name = "trp_transportvariable2")
    public String getTrpTransportVariable2() {
        return this.trpTransportVariable2;
    }

    public void setTrpTransportVariable2(String trpTransportVariable2) {
        this.trpTransportVariable2 = trpTransportVariable2;
    }

    @Column(name = "trp_transportvariable3")
    public String getTrpTransportVariable3() {
        return this.trpTransportVariable3;
    }

    public void setTrpTransportVariable3(String trpTransportVariable3) {
        this.trpTransportVariable3 = trpTransportVariable3;
    }

    @Column(name = "trp_transportvariable4")
    public String getTrpTransportVariable4() {
        return this.trpTransportVariable4;
    }

    public void setTrpTransportVariable4(String trpTransportVariable4) {
        this.trpTransportVariable4 = trpTransportVariable4;
    }

    @Column(name = "trp_transportvariable5")
    public String getTrpTransportVariable5() {
        return this.trpTransportVariable5;
    }

    public void setTrpTransportVariable5(String trpTransportVariable5) {
        this.trpTransportVariable5 = trpTransportVariable5;
    }

    @Column(name = "trp_transportvariable6")
    public String getTrpTransportVariable6() {
        return this.trpTransportVariable6;
    }

    public void setTrpTransportVariable6(String trpTransportVariable6) {
        this.trpTransportVariable6 = trpTransportVariable6;
    }

    @Column(name = "trp_transportvariable7")
    public String getTrpTransportVariable7() {
        return this.trpTransportVariable7;
    }

    public void setTrpTransportVariable7(String trpTransportVariable7) {
        this.trpTransportVariable7 = trpTransportVariable7;
    }

    @Column(name = "trp_transportvariable8")
    public String getTrpTransportVariable8() {
        return this.trpTransportVariable8;
    }

    public void setTrpTransportVariable8(String trpTransportVariable8) {
        this.trpTransportVariable8 = trpTransportVariable8;
    }

    @Column(name = "trp_transportvariable9")
    public String getTrpTransportVariable9() {
        return this.trpTransportVariable9;
    }

    public void setTrpTransportVariable9(String trpTransportVariable9) {
        this.trpTransportVariable9 = trpTransportVariable9;
    }

    @Column(name = "trp_transportvariable10")
    public String getTrpTransportVariable10() {
        return this.trpTransportVariable10;
    }

    public void setTrpTransportVariable10(String trpTransportVariable10) {
        this.trpTransportVariable10 = trpTransportVariable10;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<RcpSupplier> getRcpSuppliers() {
        return this.rcpSuppliers;
    }

    public void setRcpSuppliers(Set<RcpSupplier> rcpSuppliers) {
        this.rcpSuppliers = rcpSuppliers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<RcpPurshaseOrder> getRcpPurshaseOrders() {
        return this.rcpPurshaseOrders;
    }

    public void setRcpPurshaseOrders(Set<RcpPurshaseOrder> rcpPurshaseOrders) {
        this.rcpPurshaseOrders = rcpPurshaseOrders;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<CmdAccount> getCmdAccounts() {
        return this.cmdAccounts;
    }

    public void setCmdAccounts(Set<CmdAccount> cmdAccounts) {
        this.cmdAccounts = cmdAccounts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<RcpReceptionArc> getRcpReceptionArcs() {
        return this.rcpReceptionArcs;
    }

    public void setRcpReceptionArcs(Set<RcpReceptionArc> rcpReceptionArcs) {
        this.rcpReceptionArcs = rcpReceptionArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<RcpReception> getRcpReceptions() {
        return this.rcpReceptions;
    }

    public void setRcpReceptions(Set<RcpReception> rcpReceptions) {
        this.rcpReceptions = rcpReceptions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<RcpPurshaseOrderArc> getRcpPurshaseOrderArcs() {
        return this.rcpPurshaseOrderArcs;
    }

    public void setRcpPurshaseOrderArcs(
            Set<RcpPurshaseOrderArc> rcpPurshaseOrderArcs) {
        this.rcpPurshaseOrderArcs = rcpPurshaseOrderArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<CmdSaleOrderArc> getCmdSaleOrderArcs() {
        return this.cmdSaleOrderArcs;
    }

    public void setCmdSaleOrderArcs(Set<CmdSaleOrderArc> cmdSaleOrderArcs) {
        this.cmdSaleOrderArcs = cmdSaleOrderArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<CmdSaleOrder> getCmdSaleOrders() {
        return this.cmdSaleOrders;
    }

    public void setCmdSaleOrders(Set<CmdSaleOrder> cmdSaleOrders) {
        this.cmdSaleOrders = cmdSaleOrders;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<CmdSaleOrderLine> getCmdSaleOrderLines() {
        return this.cmdSaleOrderLines;
    }

    public void setCmdSaleOrderLines(Set<CmdSaleOrderLine> cmdSaleOrderLines) {
        this.cmdSaleOrderLines = cmdSaleOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trpTransport")
    public Set<CmdSaleOrderLineArc> getCmdSaleOrderLineArcs() {
        return this.cmdSaleOrderLineArcs;
    }

    public void setCmdSaleOrderLineArcs(
            Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs) {
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
    }

    @Column(name = "trp_transportname")
    public String getTrpTransportName() {
        return trpTransportName;
    }

    public void setTrpTransportName(String trpTransportName) {
        this.trpTransportName = trpTransportName;
    }


}
