package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;

/**
 * UsrUser generated by hbm2java
 */
@Entity
@Table(name = "usr_user")
public class UsrUser extends EmsEntity implements Serializable {

    private static final long serialVersionUID = -3952175616242893842L;

    private long usrUserId;
    @NotNull
    private OwnOwner ownOwner;
    @NotNull
    private UsrUserGroup usrUserGroup;
    @Size(max = 30)
    @NotNull
    private String usrUserCode;
    @Size(max = 100)
    @NotNull
    private String usrUserPassword;
    @Size(max = 50)
    private String usrUserName;
    @Size(max = 50)
    private String usrUserSurname;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date usrUserDateOfBirth;
    @Size(max = 20)
    private String usrUserTel;
    @Size(max = 50)
    private String usrUserPassport;
    @Size(max = 255)
    private String usrUserComment;
    private Boolean usrUserIsActive;
    @Email
    @Size(max = 50)
    private String usrUserEmail;
    private Long usrUserType;
    private String userUserColumns;

    public UsrUser() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_usr_user_id", allocationSize = 1)
    @Column(name = "usr_userid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getUsrUserId() {
        return this.usrUserId;
    }

    public void setUsrUserId(long usrUserId) {
        this.usrUserId = usrUserId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usr_userownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usr_usergroupid", nullable = false)
    public UsrUserGroup getUsrUserGroup() {
        return this.usrUserGroup;
    }

    public void setUsrUserGroup(UsrUserGroup usrUsergroup) {
        this.usrUserGroup = usrUsergroup;
    }

    @Column(name = "usr_usercode", nullable = false, length = 30)
    public String getUsrUserCode() {
        return this.usrUserCode;
    }

    public void setUsrUserCode(String usrUsercode) {
        this.usrUserCode = usrUsercode;
    }

    @Column(name = "usr_userpassword", nullable = false, length = 20)
    public String getUsrUserPassword() {
        return this.usrUserPassword;
    }

    public void setUsrUserPassword(String usrUserpassword) {
        this.usrUserPassword = usrUserpassword;
    }

    @Column(name = "usr_username", length = 50)
    public String getUsrUserName() {
        return this.usrUserName;
    }

    public void setUsrUserName(String usrUsername) {
        this.usrUserName = usrUsername;
    }

    @Column(name = "usr_usersurname", length = 50)
    public String getUsrUserSurname() {
        return this.usrUserSurname;
    }

    public void setUsrUserSurname(String usrUsersurname) {
        this.usrUserSurname = usrUsersurname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "usr_userdateofbirth", length = 13)
    public Date getUsrUserDateOfBirth() {
        return this.usrUserDateOfBirth;
    }

    public void setUsrUserDateOfBirth(Date usrUserdateofbirth) {
        this.usrUserDateOfBirth = usrUserdateofbirth;
    }

    @Column(name = "usr_usertel", length = 20)
    public String getUsrUserTel() {
        return this.usrUserTel;
    }

    public void setUsrUserTel(String usrUsertel) {
        this.usrUserTel = usrUsertel;
    }

    @Column(name = "usr_userpassport", length = 50)
    public String getUsrUserPassport() {
        return this.usrUserPassport;
    }

    public void setUsrUserPassport(String usrUserpassport) {
        this.usrUserPassport = usrUserpassport;
    }

    @Column(name = "usr_usercomment")
    public String getUsrUserComment() {
        return this.usrUserComment;
    }

    public void setUsrUserComment(String usrUsercomment) {
        this.usrUserComment = usrUsercomment;
    }

    @Column(name = "usr_userisactive")
    public Boolean getUsrUserIsActive() {
        return this.usrUserIsActive;
    }

    public void setUsrUserIsActive(Boolean usrUserisactive) {
        this.usrUserIsActive = usrUserisactive;
    }
/*
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usrUser")
    public Set<UsrUserActions> getUsrUserActions() {
        return this.usrUserActions;
    }

    public void setUsrUserActions(Set<UsrUserActions> usrUseractionses) {
        this.usrUserActions = usrUseractionses;
    }
*/

    /**
     * @return the usrUserEmail
     */
    @Column(name = "usr_useremail", unique = true)
    public String getUsrUserEmail() {
        return usrUserEmail;
    }

    /**
     * @param usrUserEmail the usrUserEmail to set
     */
    public void setUsrUserEmail(String usrUserEmail) {
        this.usrUserEmail = usrUserEmail;
    }

    @Column(name = "usr_usertype")

    public Long getUsrUserType() {
        return usrUserType;
    }

    public void setUsrUserType(Long usrUserType) {
        this.usrUserType = usrUserType;
    }

    @Size()
    @Column(name = "usr_usercolumns")
    public String getUserUserColumns() {
        return userUserColumns;
    }

    public void setUserUserColumns(String userUserColumns) {
        this.userUserColumns = userUserColumns;
    }
}