package com.bagile.tms.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * WrhWarehouse generated by hbm2java
 */
@Entity
@Table(name = "wrh_warehouse", uniqueConstraints = @UniqueConstraint(columnNames = "wrh_warehousecode"))
public class WrhWarehouse implements java.io.Serializable {

    private long wrhWarehouseId;
    @NotNull
    private AdrAddress adrAddress;
    @Size(max = 30)
    @NotNull
    private String wrhWarehouseCode;
    @Size(max = 255)
    private String wrhWarehouseDescription;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date wrhWarehouseCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date wrhWarehouseUpdateDate;
    
    
    @NotNull
    @Size(max = 100)
    private String wrhWarehouseEmail;
    @Size(max = 20)
    private String wrhWarehouseTel;
    @NotNull
    private Boolean wrhWarehouseIsActive;


    @Column(name = "wrh_warehouseemail", nullable = false, length = 100)
    public String getWrhWarehouseEmail() {
        return wrhWarehouseEmail;
    }

    public void setWrhWarehouseEmail(String wrhWarehouseEmail) {
        this.wrhWarehouseEmail = wrhWarehouseEmail;
    }

    @Column(name = "wrh_warehousetel", length = 20)
    public String getWrhWarehouseTel() {
        return wrhWarehouseTel;
    }

    public void setWrhWarehouseTel(String wrhWarehouseTel) {
        this.wrhWarehouseTel = wrhWarehouseTel;
    }

    @Column(name = "wrh_warehouseisactif", nullable = false)
    public Boolean getWrhWarehouseIsActive() {
        return wrhWarehouseIsActive;
    }

    public void setWrhWarehouseIsActive(Boolean wrhWarehouseIsActive) {
        this.wrhWarehouseIsActive = wrhWarehouseIsActive;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_wrh_warehouse", allocationSize = 1)
    @Column(name = "wrh_warehouseid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getWrhWarehouseId() {
        return this.wrhWarehouseId;
    }

    public void setWrhWarehouseId(long wrhWarehouseId) {
        this.wrhWarehouseId = wrhWarehouseId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "wrh_warehouseaddressid", nullable = false)
    public AdrAddress getAdrAddress() {
        return this.adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }

    @Column(name = "wrh_warehousecode", unique = true, nullable = false, length = 30)
    public String getWrhWarehouseCode() {
        return this.wrhWarehouseCode;
    }

    public void setWrhWarehouseCode(String wrhWarehouseCode) {
        this.wrhWarehouseCode = wrhWarehouseCode;
    }

    @Column(name = "wrh_warehousedescription")
    public String getWrhWarehouseDescription() {
        return this.wrhWarehouseDescription;
    }

    public void setWrhWarehouseDescription(String wrhWarehouseDescription) {
        this.wrhWarehouseDescription = wrhWarehouseDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wrh_warehousecreationdate")
    public Date getWrhWarehouseCreationDate() {
        return this.wrhWarehouseCreationDate;
    }

    public void setWrhWarehouseCreationDate(Date wrhWarehouseCreationDate) {
        this.wrhWarehouseCreationDate = wrhWarehouseCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "wrh_warehouseupdatedate")
    public Date getWrhWarehouseUpdateDate() {
        return this.wrhWarehouseUpdateDate;
    }

    public void setWrhWarehouseUpdateDate(Date wrhWarehouseUpdateDate) {
        this.wrhWarehouseUpdateDate = wrhWarehouseUpdateDate;
    }

 

 



}
