package com.bagile.gmo.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import com.bagile.gmo.dto.EmsDto;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * gmoSaleOrderstock generated by hbm2java
 */
@Entity
@Table(name = "gmo_maintenancestock")
public class GmoMaintenanceStock extends EmsDto implements Serializable  {

    /**
     *
     */
    private static final long serialVersionUID = -2420807901768365828L;

    private long gmoSaleOrderStockId;
    private GmoMaintenance gmoMaintenance;

    private GmoActionLineMaintenance gmoActionLineMaintenance;

    private LocLocation locLocation;

    private OwnOwner ownOwner;
    @NotNull
    private PdtProduct pdtProduct;
    private PrmBlockType prmBlockType;
    private StkContainer stkContainer;

    private WrhWarehouse wrhWarehouse;
   // private PrmColor prmColor;

    @Max(999999999)
    private Long gmoSaleOrderStockLineNumber;


    @Max(999999999)
    private BigDecimal gmoSaleOrderStockQuantityServed;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date gmoSaleOrderStockDlc;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date gmoSaleOrderStockDluo;
    @Size(max = 255)
    private String gmoSaleOrderStockSerialNo;
    @Size(max = 255)
    private String gmoSaleOrderStockLot;
    private PdtUom pdtUom;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date gmoSaleOrderStockOrderDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date gmoSaleOrderStockCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date gmoSaleOrderStockUpdateDate;
    @Size(max = 50)
    private String gmoSaleOrderStockQuality;
    @Max(999999999)
    private BigDecimal gmoSaleOrderStockWeight;
    private StkStock stkStock;
   // private PdtProductDimension pdtProductDimension;
    private PdtProductPack pdtProductPack;


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_gmo_saleorderstock", allocationSize = 1)
    @Column(name = "gmo_saleorderstockid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getgmoSaleOrderStockId() {
        return this.gmoSaleOrderStockId;
    }

    public void setgmoSaleOrderStockId(long gmoSaleOrderStockId) {
        this.gmoSaleOrderStockId = gmoSaleOrderStockId;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_maintenanaceid", nullable = false)
    public GmoMaintenance getGmoMaintenance() {
        return gmoMaintenance;
    }

    public void setGmoMaintenance(GmoMaintenance gmoMaintenance) {
        this.gmoMaintenance = gmoMaintenance;
    }



    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.MERGE)
    @JoinColumn(name = "gmo_actionmaintenancelineid", nullable = false)
    public GmoActionLineMaintenance getGmoActionLineMaintenance() {
        return gmoActionLineMaintenance;
    }

    public void setGmoActionLineMaintenance(GmoActionLineMaintenance gmoActionLineMaintenance) {
        this.gmoActionLineMaintenance = gmoActionLineMaintenance;
    }





    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstocklocid")
    public LocLocation getLocLocation() {
        return this.locLocation;
    }

    public void setLocLocation(LocLocation locLocation) {
        this.locLocation = locLocation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockownerid")
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockproductid", nullable = false)
    public PdtProduct getPdtProduct() {
        return this.pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockblocktypeid")
    public PrmBlockType getPrmBlockType() {
        return this.prmBlockType;
    }

    public void setPrmBlockType(PrmBlockType prmBlockType) {
        this.prmBlockType = prmBlockType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockcontainerid")
    public StkContainer getStkContainer() {
        return this.stkContainer;
    }

    public void setStkContainer(StkContainer stkContainer) {
        this.stkContainer = stkContainer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockwarehouseid")
    public WrhWarehouse getWrhWarehouse() {
        return this.wrhWarehouse;
    }

    public void setWrhWarehouse(WrhWarehouse wrhWarehouse) {
        this.wrhWarehouse = wrhWarehouse;
    }

  /*  @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockcolorid")
    public PrmColor getPrmColor() {
        return prmColor;
    }

    public void setPrmColor(PrmColor prmColor) {
        this.prmColor = prmColor;
    }*/

    @Column(name = "gmo_saleorderstocklinenumber", precision = 10, scale = 0)
    public Long getgmoSaleOrderStockLineNumber() {
        return this.gmoSaleOrderStockLineNumber;
    }

    public void setgmoSaleOrderStockLineNumber(Long gmoSaleOrderStockLineNumber) {
        this.gmoSaleOrderStockLineNumber = gmoSaleOrderStockLineNumber;
    }

    @Column(name = "gmo_saleorderstockquantityserved", nullable = false, precision = 12, scale = 5)
    public BigDecimal getgmoSaleOrderStockQuantityServed() {
        return this.gmoSaleOrderStockQuantityServed;
    }

    public void setgmoSaleOrderStockQuantityServed(
            BigDecimal gmoSaleOrderStockQuantityServed) {
        this.gmoSaleOrderStockQuantityServed = gmoSaleOrderStockQuantityServed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "gmo_saleorderstockdlc", length = 13)
    public Date getgmoSaleOrderStockDlc() {
        return this.gmoSaleOrderStockDlc;
    }

    public void setgmoSaleOrderStockDlc(Date gmoSaleOrderStockDlc) {
        this.gmoSaleOrderStockDlc = gmoSaleOrderStockDlc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "gmo_saleorderstockdluo", length = 13)
    public Date getgmoSaleOrderStockDluo() {
        return this.gmoSaleOrderStockDluo;
    }

    public void setgmoSaleOrderStockDluo(Date gmoSaleOrderStockDluo) {
        this.gmoSaleOrderStockDluo = gmoSaleOrderStockDluo;
    }

    @Column(name = "gmo_saleorderstockserialno", length = 50)
    public String getgmoSaleOrderStockSerialNo() {
        return this.gmoSaleOrderStockSerialNo;
    }

    public void setgmoSaleOrderStockSerialNo(String gmoSaleOrderStockSerialNo) {
        this.gmoSaleOrderStockSerialNo = gmoSaleOrderStockSerialNo;
    }

    @Column(name = "gmo_saleorderstocklot", length = 50)
    public String getgmoSaleOrderStockLot() {
        return this.gmoSaleOrderStockLot;
    }

    public void setgmoSaleOrderStockLot(String gmoSaleOrderStockLot) {
        this.gmoSaleOrderStockLot = gmoSaleOrderStockLot;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockuomid", nullable = false)
    public PdtUom getPdtUom() {
        return this.pdtUom;
    }

    public void setPdtUom(PdtUom pdtUom) {
        this.pdtUom = pdtUom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "gmo_saleorderstockorderdate")
    public Date getgmoSaleOrderStockOrderDate() {
        return this.gmoSaleOrderStockOrderDate;
    }

    public void setgmoSaleOrderStockOrderDate(Date gmoSaleOrderStockOrderDate) {
        this.gmoSaleOrderStockOrderDate = gmoSaleOrderStockOrderDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "gmo_saleorderstockcreationdate")
    public Date getgmoSaleOrderStockCreationDate() {
        return this.gmoSaleOrderStockCreationDate;
    }

    public void setgmoSaleOrderStockCreationDate(
            Date gmoSaleOrderStockCreationDate) {
        this.gmoSaleOrderStockCreationDate = gmoSaleOrderStockCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "gmo_saleorderstockupdatedate")
    public Date getgmoSaleOrderStockUpdateDate() {
        return this.gmoSaleOrderStockUpdateDate;
    }

    public void setgmoSaleOrderStockUpdateDate(Date gmoSaleOrderStockUpdateDate) {
        this.gmoSaleOrderStockUpdateDate = gmoSaleOrderStockUpdateDate;
    }

    @Column(name = "gmo_saleorderstockquality", length = 50)

    public String getgmoSaleOrderStockQuality() {
        return gmoSaleOrderStockQuality;
    }

    public void setgmoSaleOrderStockQuality(String gmoSaleOrderStockQuality) {
        this.gmoSaleOrderStockQuality = gmoSaleOrderStockQuality;
    }

    @Column(name = "gmo_saleorderstockweight", precision = 10, scale = 0)

    public BigDecimal getgmoSaleOrderStockWeight() {
        return gmoSaleOrderStockWeight;
    }

    public void setgmoSaleOrderStockWeight(BigDecimal gmoSaleOrderStockWeight) {
        this.gmoSaleOrderStockWeight = gmoSaleOrderStockWeight;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gmo_saleorderstockstockid")
    public StkStock getStkStock() {
        return stkStock;
    }

    public void setStkStock(StkStock stkStock) {
        this.stkStock = stkStock;
    }
   /*@ManyToOne
    @JoinColumn(name = "gmo_saleorderstockyproductdimensionid")
    public PdtProductDimension getPdtProductDimension() {
        return pdtProductDimension;
    }

    public void setPdtProductDimension(PdtProductDimension pdtProductDimension) {
        this.pdtProductDimension = pdtProductDimension;
    }*/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gmo_saleorderstockpackid")
    public PdtProductPack getPdtProductPack() {
        return pdtProductPack;
    }

    public void setPdtProductPack(PdtProductPack pdtProductPack) {
        this.pdtProductPack = pdtProductPack;
    }
}

