package com.bagile.gmo.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * OwnOwner generated by hbm2java
 */
@Entity
@Table(name = "own_owner", uniqueConstraints = @UniqueConstraint(columnNames = "own_ownercode"))
public class OwnOwner extends EmsEntity implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1484351263626605420L;
    private long ownOwnerId;
    @Size(max = 30)
    @NotNull
    private String ownOwnerCode;
    @Size(max = 255)
    private String ownOwnerDescription;
    @Size(max = 20)
    private String ownOwnerSiret;
    @Size(max = 255)
    private String ownOwnerComment;
    private Boolean ownOwnerIsActive = true;
    @NotNull
    private String ownOwnerName;
    @NotNull
    private String ownOwnerSurname;
    @NotNull
    private String ownOwnerEmail;
    private String ownOwnerPrimaryTel;
    private String ownOwnerSecondaryTel;
    @NotNull
    private byte[] ownOwnerImage;

    public OwnOwner() {
    }

    public OwnOwner(long ownOwnerId, String ownOwnerCode,
                    Boolean ownOwnerIsActive) {
        this.ownOwnerId = ownOwnerId;
        this.ownOwnerCode = ownOwnerCode;
        this.ownOwnerIsActive = ownOwnerIsActive;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_own_owner_id", allocationSize = 1)
    @Column(name = "own_ownerid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getOwnOwnerId() {
        return this.ownOwnerId;
    }

    public void setOwnOwnerId(long ownOwnerId) {
        this.ownOwnerId = ownOwnerId;
    }



    @Column(name = "own_ownercode", unique = true, nullable = false, length = 30)

    public String getOwnOwnerCode() {
        return this.ownOwnerCode;
    }

    public void setOwnOwnerCode(String ownOwnerCode) {
        this.ownOwnerCode = ownOwnerCode;
    }

  /*  @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn(name = "own_ownerorganisationid")
    public OrgOrganisation getOrgOrganisation() {
        return orgOrganisation;
    }

    public void setOrgOrganisation(OrgOrganisation orgOrganisation) {
        this.orgOrganisation = orgOrganisation;
    }
*/
    @Column(name = "own_ownerdescription")
    public String getOwnOwnerDescription() {
        return this.ownOwnerDescription;
    }

    public void setOwnOwnerDescription(String ownOwnerDescription) {
        this.ownOwnerDescription = ownOwnerDescription;
    }

    @Column(name = "own_ownersiret", length = 20)
    public String getOwnOwnerSiret() {
        return this.ownOwnerSiret;
    }

    public void setOwnOwnerSiret(String ownOwnerSiret) {
        this.ownOwnerSiret = ownOwnerSiret;
    }

    @Column(name = "own_ownercomment")
    public String getOwnOwnerComment() {
        return this.ownOwnerComment;
    }

    public void setOwnOwnerComment(String ownOwnerComment) {
        this.ownOwnerComment = ownOwnerComment;
    }

    @Column(name = "own_ownerisactive", nullable = false)
    public Boolean getOwnOwnerIsActive() {
        return ownOwnerIsActive;
    }

    public void setOwnOwnerIsActive(Boolean ownOwnerIsActive) {
        this.ownOwnerIsActive = ownOwnerIsActive;
    }

    /*@ManyToOne
    @JoinColumn(name = "own_owneraddressid",nullable = false)
    public AdrAddress getAdrAddress() {
        return adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }*/

    @Column(name = "own_ownername",nullable = false,length = 50)
    public String getOwnOwnerName() {
        return ownOwnerName;
    }

    public void setOwnOwnerName(String name) {
        this.ownOwnerName = name;
    }
    @Column(name = "own_ownersurname",nullable = false,length = 50)

    public String getOwnOwnerSurname() {
        return ownOwnerSurname;
    }

    public void setOwnOwnerSurname(String ownOwnerSurname) {
        this.ownOwnerSurname = ownOwnerSurname;
    }
    @Column(name = "own_owneremail",nullable = false,length = 100)

    public String getOwnOwnerEmail() {
        return ownOwnerEmail;
    }

    public void setOwnOwnerEmail(String ownOwnerEmail) {
        this.ownOwnerEmail = ownOwnerEmail;
    }
    @Column(name = "own_ownerprimarytel",length = 20)

    public String getOwnOwnerPrimaryTel() {
        return ownOwnerPrimaryTel;
    }

    public void setOwnOwnerPrimaryTel(String ownOwnerPrimaryTel) {
        this.ownOwnerPrimaryTel = ownOwnerPrimaryTel;
    }
    @Column(name = "own_ownersecondarytel",length = 20)

    public String getOwnOwnerSecondaryTel() {
        return ownOwnerSecondaryTel;
    }

    public void setOwnOwnerSecondaryTel(String ownOwnerSecondaryTel) {
        this.ownOwnerSecondaryTel = ownOwnerSecondaryTel;
    }
    @Column(name="own_ownerimage", nullable = false)
    public byte[] getOwnOwnerImage() {
        return ownOwnerImage;
    }

    public void setOwnOwnerImage(byte[] ownOwnerImage) {
        this.ownOwnerImage = ownOwnerImage;
    }


    @Override
    public boolean equals(Object object) {
        boolean result = false;
        if (object == null || object.getClass() != getClass()) {
            result = false;
        } else {
            OwnOwner obj = (OwnOwner) object;
            if (this.getOwnOwnerId() == obj.getOwnOwnerId()) {
                result = true;
            }
        }
        return result;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 7 * hash + (int) this.getOwnOwnerId();
        hash = 7 * hash + (int) this.getOwnOwnerId();
        return hash;
    }
}
