package com.bagile.gmo.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

/**
 * PrmBlockType generated by hbm2java
 */
@Entity
@Table(name = "prm_blocktype", uniqueConstraints = {
        @UniqueConstraint(columnNames = "prm_blocktypecode")})
public class PrmBlockType extends EmsEntity implements java.io.Serializable {

    private long prmBlockTypeId;
    @NotNull
    private OwnOwner ownOwner;
    @Size(max = 30)
    @NotNull
    private String prmBlockTypeCode;
    @Size(max = 100)
    private String prmBlockTypeDescription;

    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date prmBlockTypeCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date prmBlockTypeUpdateDate;


    public PrmBlockType() {
    }

    public PrmBlockType(long prmBlockTypeId, OwnOwner ownOwner,
                        String prmBlockTypeCode) {
        this.prmBlockTypeId = prmBlockTypeId;
        this.ownOwner = ownOwner;
        this.prmBlockTypeCode = prmBlockTypeCode;
    }


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_prm_blocktype", allocationSize = 1)
    @Column(name = "prm_blocktypeid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPrmBlockTypeId() {
        return this.prmBlockTypeId;
    }

    public void setPrmBlockTypeId(long prmBlockTypeId) {
        this.prmBlockTypeId = prmBlockTypeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prm_blocktypeownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @Column(name = "prm_blocktypecode", unique = true, nullable = false, length = 30)
    public String getPrmBlockTypeCode() {
        return this.prmBlockTypeCode;
    }

    public void setPrmBlockTypeCode(String prmBlockTypeCode) {
        this.prmBlockTypeCode = prmBlockTypeCode;
    }

    @Column(name = "prm_blocktypedescription", length = 100)
    public String getPrmBlockTypeDescription() {
        return this.prmBlockTypeDescription;
    }

    public void setPrmBlockTypeDescription(String prmBlockTypeDescription) {
        this.prmBlockTypeDescription = prmBlockTypeDescription;
    }



    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "prm_blocktypecreationdate")
    public Date getPrmBlockTypeCreationDate() {
        return this.prmBlockTypeCreationDate;
    }

    public void setPrmBlockTypeCreationDate(Date prmBlockTypeCreationDate) {
        this.prmBlockTypeCreationDate = prmBlockTypeCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "prm_blocktypeupdatedate")
    public Date getPrmBlockTypeUpdateDate() {
        return this.prmBlockTypeUpdateDate;
    }

    public void setPrmBlockTypeUpdateDate(Date prmBlockTypeUpdateDate) {
        this.prmBlockTypeUpdateDate = prmBlockTypeUpdateDate;
    }

    @Override
    public boolean equals(Object object) {
        boolean result = false;
        if (object == null || object.getClass() != getClass()) {
            result = false;
        } else {
            PrmBlockType obj = (PrmBlockType) object;
            if (this.getPrmBlockTypeId() == obj.getPrmBlockTypeId()) {
                result = true;
            }
        }
        return result;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 7 * hash + (int) this.getPrmBlockTypeId();
        hash = 7 * hash + (int) this.getPrmBlockTypeId();
        return hash;
    }
}
