package com.bagile.gmo.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RcpPurshaseOrderLine generated by hbm2java
 */
@Entity
@Table(name = "rcp_purshaseorderline")
public class RcpPurshaseOrderLine extends EmsEntity implements java.io.Serializable {

    private Long rcpPurshaseOrderLineId;
   // @NotNull
    private OwnOwner ownOwner;
    @NotNull
    private PdtProduct pdtProduct;
    private PdtUom pdtUom;
    private PdtUom pdtUomReceived;
    //private PrmBlockType prmBlockType;
   // private PrmColor prmColor;
    private PrmOrderStatus prmOrderStatus;
   // @NotNull
    private RcpPurshaseOrder rcpPurshaseOrder;
    private WrhWarehouse wrhWarehouse;

    @Max(999999999)
   // @NotNull
    private Long rcpPurshaseOrderLineNumber;

    private String rcpPurshaseOrderComment;

    @Max(999999999)
   // @NotNull
    private BigDecimal rcpPurshaseOrderLineQuantity;

    @Max(999999999)

    private BigDecimal rcpPurshaseOrderLineQuantityReceived;
    @Size(max = 255)
    private String rcpPurshaseOrderLineDescription;
    @Size(max = 50)
    private String rcpPurshaseOrderLineContainerCode;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date rcpPurshaseOrderLineDlc;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date rcpPurshaseOrderLineDluo;
    @Size(max = 255)
    private String rcpPurshaseOrderLineSerialNo;
    @Size(max = 255)
    private String rcpPurshaseOrderLineLot;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date rcpPurshaseOrderLineReceptionDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date rcpPurshaseOrderLineCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date rcpPurshaseOrderLineUpdateDate;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable1;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable2;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable3;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable4;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable5;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable6;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable7;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable8;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable9;
    @Size(max = 255)
    private String rcpPurshaseOrderLineVariable10;
    @Size(max = 50)
    private String rcpPurshaseOrderLineQuality;
    @Max(999999999)
    private BigDecimal rcpPurshaseOrderLineWeight;
    @Max(999999999)
    private BigDecimal rcpPurshaseOrderLineBlockedQuantity;
    private Set<RcpReceptionLine> rcpReceptionLines = new HashSet<RcpReceptionLine>(
            0);
    @Max(999999999)
    private BigDecimal rcpPurshaseOrderLineTotalPriceHT;
    @Max(999999999)
    private BigDecimal rcpPurshaseOrderLineTotalPriceTTC;
    private PrmVat prmVat;
    @Max(999999999)
    private BigDecimal rcpPurshaseOrderLineDiscount;
    @Max(999999999)
    private BigDecimal rcpPurshaseOrderLinePurshasePrice;
    //private PdtProductDimension pdtProductDimension;
    private PdtProductPack pdtProductPack;
    private BigDecimal rcpPurshaseOrderLineProvisionalCost;
    private BigDecimal rcpPurshaseOrderLineExtraCost;

    public RcpPurshaseOrderLine() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_rcp_purshaseorderline", allocationSize = 1)
    @Column(name = "rcp_purshaseorderlineid", unique = true, nullable = false, precision = 10, scale = 0)
    public Long getRcpPurshaseOrderLineId() {
        return this.rcpPurshaseOrderLineId;
    }

    public void setRcpPurshaseOrderLineId(Long rcpPurshaseOrderLineId) {
        this.rcpPurshaseOrderLineId = rcpPurshaseOrderLineId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlineownerid")
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlineproductid", nullable = false)
    public PdtProduct getPdtProduct() {
        return this.pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlineuomid")
    public PdtUom getPdtUom() {
        return this.pdtUom;
    }

    public void setPdtUom(PdtUom pdtUom) {
        this.pdtUom = pdtUom;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlineuomreceivedid")
    public PdtUom getPdtUomReceived() {
        return pdtUomReceived;
    }

    public void setPdtUomReceived(PdtUom pdtUomReceived) {
        this.pdtUomReceived = pdtUomReceived;
    }

   /* @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlineblocktypeid")
    public PrmBlockType getPrmBlockType() {
        return this.prmBlockType;
    }

    public void setPrmBlockType(PrmBlockType prmBlockType) {
        this.prmBlockType = prmBlockType;
    }
*/
  /*  @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlinecolorid")
    public PrmColor getPrmColor() {
        return this.prmColor;
    }

    public void setPrmColor(PrmColor prmColor) {
        this.prmColor = prmColor;
    }
*/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlinestatusid")
    public PrmOrderStatus getPrmOrderStatus() {
        return this.prmOrderStatus;
    }

    public void setPrmOrderStatus(PrmOrderStatus prmOrderStatus) {
        this.prmOrderStatus = prmOrderStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlinepoid")
    public RcpPurshaseOrder getRcpPurshaseOrder() {
        return this.rcpPurshaseOrder;
    }

    public void setRcpPurshaseOrder(RcpPurshaseOrder rcpPurshaseOrder) {
        this.rcpPurshaseOrder = rcpPurshaseOrder;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlinewarehouseid")
    public WrhWarehouse getWrhWarehouse() {
        return this.wrhWarehouse;
    }

    public void setWrhWarehouse(WrhWarehouse wrhWarehouse) {
        this.wrhWarehouse = wrhWarehouse;
    }


    @Column(name = "rcp_purshaseorderlinenumber", nullable = false, precision = 10, scale = 0)
    public Long getRcpPurshaseOrderLineNumber() {
        return this.rcpPurshaseOrderLineNumber;
    }

    @Column(name = "rcp_purshaseordercomment")
    public String getRcpPurshaseOrderComment() {
        return rcpPurshaseOrderComment;
    }

    public void setRcpPurshaseOrderComment(String rcpPurshaseOrderComment) {
        this.rcpPurshaseOrderComment = rcpPurshaseOrderComment;
    }

    public void setRcpPurshaseOrderLineNumber(Long rcpPurshaseOrderLineNumber) {
        this.rcpPurshaseOrderLineNumber = rcpPurshaseOrderLineNumber;
    }

    @Column(name = "rcp_purshaseorderlinequantity", nullable = false, precision = 12, scale = 5)
    public BigDecimal getRcpPurshaseOrderLineQuantity() {
        return this.rcpPurshaseOrderLineQuantity;
    }

    public void setRcpPurshaseOrderLineQuantity(
            BigDecimal rcpPurshaseOrderLineQuantity) {
        this.rcpPurshaseOrderLineQuantity = rcpPurshaseOrderLineQuantity;
    }

    @Column(name = "rcp_purshaseorderlinequantityreceived", precision = 12, scale = 5)
    public BigDecimal getRcpPurshaseOrderLineQuantityReceived() {
        return this.rcpPurshaseOrderLineQuantityReceived;
    }

    public void setRcpPurshaseOrderLineQuantityReceived(
            BigDecimal rcpPurshaseOrderLineQuantityReceived) {
        this.rcpPurshaseOrderLineQuantityReceived = rcpPurshaseOrderLineQuantityReceived;
    }

    @Column(name = "rcp_purshaseorderlinedescription")
    public String getRcpPurshaseOrderLineDescription() {
        return this.rcpPurshaseOrderLineDescription;
    }

    public void setRcpPurshaseOrderLineDescription(
            String rcpPurshaseOrderLineDescription) {
        this.rcpPurshaseOrderLineDescription = rcpPurshaseOrderLineDescription;
    }

    @Column(name = "rcp_purshaseorderlinecontainercode", length = 50)
    public String getRcpPurshaseOrderLineContainerCode() {
        return this.rcpPurshaseOrderLineContainerCode;
    }

    public void setRcpPurshaseOrderLineContainerCode(
            String rcpPurshaseOrderLineContainerCode) {
        this.rcpPurshaseOrderLineContainerCode = rcpPurshaseOrderLineContainerCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rcp_purshaseorderlinedlc", length = 13)
    public Date getRcpPurshaseOrderLineDlc() {
        return this.rcpPurshaseOrderLineDlc;
    }

    public void setRcpPurshaseOrderLineDlc(Date rcpPurshaseOrderLineDlc) {
        this.rcpPurshaseOrderLineDlc = rcpPurshaseOrderLineDlc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rcp_purshaseorderlinedluo", length = 13)
    public Date getRcpPurshaseOrderLineDluo() {
        return this.rcpPurshaseOrderLineDluo;
    }

    public void setRcpPurshaseOrderLineDluo(Date rcpPurshaseOrderLineDluo) {
        this.rcpPurshaseOrderLineDluo = rcpPurshaseOrderLineDluo;
    }

    @Column(name = "rcp_purshaseorderlineserialno", length = 50)
    public String getRcpPurshaseOrderLineSerialNo() {
        return this.rcpPurshaseOrderLineSerialNo;
    }

    public void setRcpPurshaseOrderLineSerialNo(
            String rcpPurshaseOrderLineSerialNo) {
        this.rcpPurshaseOrderLineSerialNo = rcpPurshaseOrderLineSerialNo;
    }

    @Column(name = "rcp_purshaseorderlinelot", length = 50)
    public String getRcpPurshaseOrderLineLot() {
        return this.rcpPurshaseOrderLineLot;
    }

    public void setRcpPurshaseOrderLineLot(String rcpPurshaseOrderLineLot) {
        this.rcpPurshaseOrderLineLot = rcpPurshaseOrderLineLot;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rcp_purshaseorderlinereceptiondate")
    public Date getRcpPurshaseOrderLineReceptionDate() {
        return this.rcpPurshaseOrderLineReceptionDate;
    }

    public void setRcpPurshaseOrderLineReceptionDate(
            Date rcpPurshaseOrderLineReceptionDate) {
        this.rcpPurshaseOrderLineReceptionDate = rcpPurshaseOrderLineReceptionDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rcp_purshaseorderlinecreationdate")
    public Date getRcpPurshaseOrderLineCreationDate() {
        return this.rcpPurshaseOrderLineCreationDate;
    }

    public void setRcpPurshaseOrderLineCreationDate(
            Date rcpPurshaseOrderLineCreationDate) {
        this.rcpPurshaseOrderLineCreationDate = rcpPurshaseOrderLineCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rcp_purshaseorderlineupdatedate")
    public Date getRcpPurshaseOrderLineUpdateDate() {
        return this.rcpPurshaseOrderLineUpdateDate;
    }

    public void setRcpPurshaseOrderLineUpdateDate(
            Date rcpPurshaseOrderLineUpdateDate) {
        this.rcpPurshaseOrderLineUpdateDate = rcpPurshaseOrderLineUpdateDate;
    }

    @Column(name = "rcp_purshaseorderlinevariable1")
    public String getRcpPurshaseOrderLineVariable1() {
        return this.rcpPurshaseOrderLineVariable1;
    }

    public void setRcpPurshaseOrderLineVariable1(
            String rcpPurshaseOrderLineVariable1) {
        this.rcpPurshaseOrderLineVariable1 = rcpPurshaseOrderLineVariable1;
    }

    @Column(name = "rcp_purshaseorderlinevariable2")
    public String getRcpPurshaseOrderLineVariable2() {
        return this.rcpPurshaseOrderLineVariable2;
    }

    public void setRcpPurshaseOrderLineVariable2(
            String rcpPurshaseOrderLineVariable2) {
        this.rcpPurshaseOrderLineVariable2 = rcpPurshaseOrderLineVariable2;
    }

    @Column(name = "rcp_purshaseorderlinevariable3")
    public String getRcpPurshaseOrderLineVariable3() {
        return this.rcpPurshaseOrderLineVariable3;
    }

    public void setRcpPurshaseOrderLineVariable3(
            String rcpPurshaseOrderLineVariable3) {
        this.rcpPurshaseOrderLineVariable3 = rcpPurshaseOrderLineVariable3;
    }

    @Column(name = "rcp_purshaseorderlinevariable4")
    public String getRcpPurshaseOrderLineVariable4() {
        return this.rcpPurshaseOrderLineVariable4;
    }

    public void setRcpPurshaseOrderLineVariable4(
            String rcpPurshaseOrderLineVariable4) {
        this.rcpPurshaseOrderLineVariable4 = rcpPurshaseOrderLineVariable4;
    }

    @Column(name = "rcp_purshaseorderlinevariable5")
    public String getRcpPurshaseOrderLineVariable5() {
        return this.rcpPurshaseOrderLineVariable5;
    }

    public void setRcpPurshaseOrderLineVariable5(
            String rcpPurshaseOrderLineVariable5) {
        this.rcpPurshaseOrderLineVariable5 = rcpPurshaseOrderLineVariable5;
    }

    @Column(name = "rcp_purshaseorderlinevariable6")
    public String getRcpPurshaseOrderLineVariable6() {
        return this.rcpPurshaseOrderLineVariable6;
    }

    public void setRcpPurshaseOrderLineVariable6(
            String rcpPurshaseOrderLineVariable6) {
        this.rcpPurshaseOrderLineVariable6 = rcpPurshaseOrderLineVariable6;
    }

    @Column(name = "rcp_purshaseorderlinevariable7")
    public String getRcpPurshaseOrderLineVariable7() {
        return this.rcpPurshaseOrderLineVariable7;
    }

    public void setRcpPurshaseOrderLineVariable7(
            String rcpPurshaseOrderLineVariable7) {
        this.rcpPurshaseOrderLineVariable7 = rcpPurshaseOrderLineVariable7;
    }

    @Column(name = "rcp_purshaseorderlinevariable8")
    public String getRcpPurshaseOrderLineVariable8() {
        return this.rcpPurshaseOrderLineVariable8;
    }

    public void setRcpPurshaseOrderLineVariable8(
            String rcpPurshaseOrderLineVariable8) {
        this.rcpPurshaseOrderLineVariable8 = rcpPurshaseOrderLineVariable8;
    }

    @Column(name = "rcp_purshaseorderlinevariable9")
    public String getRcpPurshaseOrderLineVariable9() {
        return this.rcpPurshaseOrderLineVariable9;
    }

    public void setRcpPurshaseOrderLineVariable9(
            String rcpPurshaseOrderLineVariable9) {
        this.rcpPurshaseOrderLineVariable9 = rcpPurshaseOrderLineVariable9;
    }

    @Column(name = "rcp_purshaseorderlinevariable10")
    public String getRcpPurshaseOrderLineVariable10() {
        return this.rcpPurshaseOrderLineVariable10;
    }

    public void setRcpPurshaseOrderLineVariable10(
            String rcpPurshaseOrderLineVariable10) {
        this.rcpPurshaseOrderLineVariable10 = rcpPurshaseOrderLineVariable10;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rcpPurshaseOrderLine")
    public Set<RcpReceptionLine> getRcpReceptionLines() {
        return this.rcpReceptionLines;
    }

    public void setRcpReceptionLines(Set<RcpReceptionLine> rcpReceptionLines) {
        this.rcpReceptionLines = rcpReceptionLines;
    }

    @Column(name = "rcp_purshaseorderlinequality", length = 50)

    public String getRcpPurshaseOrderLineQuality() {
        return rcpPurshaseOrderLineQuality;
    }

    public void setRcpPurshaseOrderLineQuality(String rcpPurshaseOrderLineQuality) {
        this.rcpPurshaseOrderLineQuality = rcpPurshaseOrderLineQuality;
    }

    @Column(name = "rcp_purshaseorderlineweight", precision = 10, scale = 0)

    public BigDecimal getRcpPurshaseOrderLineWeight() {
        return rcpPurshaseOrderLineWeight;
    }

    public void setRcpPurshaseOrderLineWeight(BigDecimal rcpPurshaseOrderLineWeight) {
        this.rcpPurshaseOrderLineWeight = rcpPurshaseOrderLineWeight;
    }

    @Column(name = "rcp_purshaseorderlineblockedquantity", precision = 12, scale = 5)

    public BigDecimal getRcpReceptionLineBlockedQuantity() {
        return rcpPurshaseOrderLineBlockedQuantity;
    }

    public void setRcpReceptionLineBlockedQuantity(BigDecimal rcpReceptionLineBlockedQuantity) {
        this.rcpPurshaseOrderLineBlockedQuantity = rcpReceptionLineBlockedQuantity;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlinevatid")
    public PrmVat getPrmVat() {
        return prmVat;
    }

    public void setPrmVat(PrmVat prmVat) {
        this.prmVat = prmVat;
    }

    @Column(name = "rcp_purshaseorderlinetotalpriceht")
    public BigDecimal getRcpPurshaseOrderLineTotalPriceHT() {
        return rcpPurshaseOrderLineTotalPriceHT;
    }

    public void setRcpPurshaseOrderLineTotalPriceHT(BigDecimal rcpPurshaseOrderLineTotalPriceHT) {
        this.rcpPurshaseOrderLineTotalPriceHT = rcpPurshaseOrderLineTotalPriceHT;
    }
    @Column(name = "rcp_purshaseorderlinetotalpricettc")
    public BigDecimal getRcpPurshaseOrderLineTotalPriceTTC() {
        return rcpPurshaseOrderLineTotalPriceTTC;
    }

    public void setRcpPurshaseOrderLineTotalPriceTTC(BigDecimal rcpPurshaseOrderLineTotalPriceTTC) {
        this.rcpPurshaseOrderLineTotalPriceTTC = rcpPurshaseOrderLineTotalPriceTTC;
    }
    @Column(name = "rcp_purshaseorderlinediscount")
    public BigDecimal getRcpPurshaseOrderLineDiscount() {
        return rcpPurshaseOrderLineDiscount;
    }

    public void setRcpPurshaseOrderLineDiscount(BigDecimal rcpPurshaseOrderLineDiscount) {
        this.rcpPurshaseOrderLineDiscount = rcpPurshaseOrderLineDiscount;
    }

    @Column(name = "rcp_purshaseorderlinepurshaseprice")
    public BigDecimal getRcpPurshaseOrderLinePurshasePrice() {
        return rcpPurshaseOrderLinePurshasePrice;
    }

    public void setRcpPurshaseOrderLinePurshasePrice(BigDecimal rcpPurshaseOrderLinePurshasePrice) {
        this.rcpPurshaseOrderLinePurshasePrice = rcpPurshaseOrderLinePurshasePrice;
    }
   /* @ManyToOne
    @JoinColumn(name = "rcp_purshaseorderlineyproductdimensionid")
    public PdtProductDimension getPdtProductDimension() {
        return pdtProductDimension;
    }

    public void setPdtProductDimension(PdtProductDimension pdtProductDimension) {
        this.pdtProductDimension = pdtProductDimension;
    }*/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderlinepackid")
    public PdtProductPack getPdtProductPack() {
        return pdtProductPack;
    }

    public void setPdtProductPack(PdtProductPack pdtProductPack) {
        this.pdtProductPack = pdtProductPack;
    }
    @Column(name = "rcp_purshaseorderlineprovisionalcost")
    public BigDecimal getRcpPurshaseOrderLineProvisionalCost() {
        return rcpPurshaseOrderLineProvisionalCost;
    }

    public void setRcpPurshaseOrderLineProvisionalCost(BigDecimal rcpPurshaseOrderLineProvisionalCost) {
        this.rcpPurshaseOrderLineProvisionalCost = rcpPurshaseOrderLineProvisionalCost;
    }
    @Column(name = "rcp_purshaseorderlineextracost")
    public BigDecimal getRcpPurshaseOrderLineExtraCost() {
        return rcpPurshaseOrderLineExtraCost;
    }

    public void setRcpPurshaseOrderLineExtraCost(BigDecimal rcpPurshaseOrderLineExtraCost) {
        this.rcpPurshaseOrderLineExtraCost = rcpPurshaseOrderLineExtraCost;
    }
}
