package com.bagile.gmo.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RcpPurshaseOrder generated by hbm2java
 */
@Entity
@Table(name = "rcp_purshaseorder", uniqueConstraints = {
        @UniqueConstraint(columnNames = "rcp_PurshaseOrderCode")})
public class RcpPurshaseOrder extends EmsEntity implements java.io.Serializable {

    private Long rcpPurshaseOrderId;
   // @NotNull
    private OwnOwner ownOwner;
    private AdrAddressInfo adrAddress;
    private RcpSupplier rcpSupplier;
  //  @NotNull
    private PrmOrderStatus prmOrderStatus;
    @NotNull
    private PrmOrderType prmOrderType;
    private TrpTransport trpTransport;
    @Size(max = 30)
    @NotNull
    private String rcpPurshaseOrderCode;
    @Size(max = 255)
    private String rcpPurshaseOrderRemarks;
    @Size(max = 30)
    private String rcpPurshaseOrderSupplierOrderCode;
    @Size(max = 255)
    private String rcpPurshaseOrderDescription;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date rcpPurshaseOrderExpectedDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date rcpPurshaseOrderReceptionDate;
    @Size(max = 50)
    private String rcpPurshaseOrderAccountOrderCode;
    private Short rcpPurshaseOrderContainers;
    private WrhWarehouse wrhWarehouseSource;
    //@NotNull
    private WrhWarehouse wrhWarehouseDestination;
    @Size(max = 50)
    private String rcpPurshaseOrderTransportContact;
    @Size(max = 20)
    private String rcpPurshaseOrderImmatriculation;
    @Size(max = 20)
    private String rcpPurshaseOrderTelContact;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date rcpPurshaseOrderCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date rcpPurshaseOrderUpdateDate;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable1;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable2;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable3;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable4;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable5;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable6;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable7;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable8;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable9;
    @Size(max = 255)
    private String rcpPurshaseOrderVariable10;
    private Long rcpPurshaseOrderCmdType;
    @Size(max = 50)
    private String rcpPurshaseOrderTransfertCode;
    private Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines = new HashSet<RcpPurshaseOrderLine>(
            0);
    private Set<RcpReception> rcpReceptions = new HashSet<RcpReception>(0);
    private BigDecimal rcpPurshaseOrderTotalPriceHT;
    private BigDecimal rcpPurshaseOrderTotalPriceTTC;
    private BigDecimal rcpPurshaseOrderDiscount;
    private BigDecimal rcpPurshaseOrderVat;
   // private PrmCurrency prmCurrency;
    private Boolean rcpPurshaseOrderActive;
    private CmdSaleOrder cmdSaleOrder;
   // private Set<RcpBillingTerm> rcpBillingTerms;
    private Boolean rcpPurshaseOrderAccounted;
  //  private Set<RcpExtraCost> rcpExtraCosts;
   // private PrmPaymentStatus prmPaymentStatus;
  //  private UsrBox usrBox;
    private BigDecimal rcpPurshaseOrderPayedAmount;
    private BigDecimal rcpPurshaseTotalPriceHTDefaultCurrency;
    private BigDecimal rcpPurshaseTotalPriceTTCDefaultCurrency;
    private BigDecimal rcpPurshaseVatDefaultCurrency;
    private BigDecimal rcpPurshaseExchangeRate;
    private BigDecimal rcpPurshaseOrderProvisionalCost;
    private BigDecimal rcpPurshaseOrderExtraCost;
  //  private CmdDeal cmdDeal;
    private CmdAccount cmdAccount;

    private String rcpPurshaseOrdernotes;
    private Boolean rcpPurshaseOrderGmao;

    public RcpPurshaseOrder() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_rcp_purshaseorder", allocationSize = 1)
    @Column(name = "rcp_purshaseorderid", unique = true, nullable = false, precision = 10, scale = 0)
    public Long getRcpPurshaseOrderId() {
        return this.rcpPurshaseOrderId;
    }

    public void setRcpPurshaseOrderId(Long rcpPurshaseOrderId) {
        this.rcpPurshaseOrderId = rcpPurshaseOrderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderownerid")
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseordersupplierid", nullable = false)
    public RcpSupplier getRcpSupplier() {
        return rcpSupplier;
    }

    public void setRcpSupplier(RcpSupplier rcpSupplier) {
        this.rcpSupplier = rcpSupplier;
    }

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "adrAddressLine1", column = @Column(name = "rcp_purshaseorderaddressline1")),
            @AttributeOverride(name = "adrAddressLine2", column = @Column(name = "rcp_purshaseorderaddressline2")),
            @AttributeOverride(name = "adrAddressZip", column = @Column(name = "rcp_purshaseorderaddresszip")),
            @AttributeOverride(name = "adrAddressCity", column = @Column(name = "rcp_purshaseorderaddresscity")),
            @AttributeOverride(name = "adrAddressState", column = @Column(name = "rcp_purshaseorderaddressstate")),
            @AttributeOverride(name = "adrAddressCountry", column = @Column(name = "rcp_purshaseorderaddresscountry")),
            @AttributeOverride(name = "adrAddressDigiCode", column = @Column(name = "rcp_purshaseorderaddressdigicode")),
    })
    public AdrAddressInfo getAdrAddress() {
        return this.adrAddress;
    }

    public void setAdrAddress(AdrAddressInfo adrAddress) {
        this.adrAddress = adrAddress;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderstatusid")
    public PrmOrderStatus getPrmOrderStatus() {
        return this.prmOrderStatus;
    }

    public void setPrmOrderStatus(PrmOrderStatus prmOrderStatus) {
        this.prmOrderStatus = prmOrderStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseordertypeid", nullable = false)
    public PrmOrderType getPrmOrderType() {
        return this.prmOrderType;
    }

    public void setPrmOrderType(PrmOrderType prmOrderType) {
        this.prmOrderType = prmOrderType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseordertransportid")
    public TrpTransport getTrpTransport() {
        return this.trpTransport;
    }

    public void setTrpTransport(TrpTransport trpTransport) {
        this.trpTransport = trpTransport;
    }

    @Column(name = "rcp_PurshaseOrderCode", unique = true, nullable = false, length = 30)
    public String getRcpPurshaseOrderCode() {
        return this.rcpPurshaseOrderCode;
    }

    public void setRcpPurshaseOrderCode(String rcpPurshaseOrderCode) {
        this.rcpPurshaseOrderCode = rcpPurshaseOrderCode;
    }

    @Column(name = "rcp_purshaseorderremarks")
    public String getRcpPurshaseOrderRemarks() {
        return this.rcpPurshaseOrderRemarks;
    }

    public void setRcpPurshaseOrderRemarks(String rcpPurshaseOrderRemarks) {
        this.rcpPurshaseOrderRemarks = rcpPurshaseOrderRemarks;
    }

    @Column(name = "rcp_purshaseordernotes")
    public String getRcpPurshaseOrdernotes() {
        return rcpPurshaseOrdernotes;
    }

    public void setRcpPurshaseOrdernotes(String rcpPurshaseOrdernotes) {
        this.rcpPurshaseOrdernotes = rcpPurshaseOrdernotes;
    }

    @Column(name = "rcp_purshaseordergmao")
    public Boolean getRcpPurshaseOrderGmao() {
        return rcpPurshaseOrderGmao;
    }

    public void setRcpPurshaseOrderGmao(Boolean rcpPurshaseOrderGmao) {
        this.rcpPurshaseOrderGmao = rcpPurshaseOrderGmao;
    }

    @Column(name = "rcp_purshaseordersupplierordercode", length = 30)
    public String getRcpPurshaseOrderSupplierOrderCode() {
        return this.rcpPurshaseOrderSupplierOrderCode;
    }

    public void setRcpPurshaseOrderSupplierOrderCode(
            String rcpPurshaseOrderSupplierOrderCode) {
        this.rcpPurshaseOrderSupplierOrderCode = rcpPurshaseOrderSupplierOrderCode;
    }

    @Column(name = "rcp_purshaseorderdescription")
    public String getRcpPurshaseOrderDescription() {
        return this.rcpPurshaseOrderDescription;
    }

    public void setRcpPurshaseOrderDescription(
            String rcpPurshaseOrderDescription) {
        this.rcpPurshaseOrderDescription = rcpPurshaseOrderDescription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "rcp_purshaseorderexpecteddate", length = 13)
    public Date getRcpPurshaseOrderExpectedDate() {
        return this.rcpPurshaseOrderExpectedDate;
    }

    public void setRcpPurshaseOrderExpectedDate(
            Date rcpPurshaseOrderExpectedDate) {
        this.rcpPurshaseOrderExpectedDate = rcpPurshaseOrderExpectedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rcp_purshaseorderreceptiondate")
    public Date getRcpPurshaseOrderReceptionDate() {
        return this.rcpPurshaseOrderReceptionDate;
    }

    public void setRcpPurshaseOrderReceptionDate(
            Date rcpPurshaseOrderReceptionDate) {
        this.rcpPurshaseOrderReceptionDate = rcpPurshaseOrderReceptionDate;
    }

    @Column(name = "rcp_purshaseordercontainers", precision = 4, scale = 0)
    public Short getRcpPurshaseOrderContainers() {
        return this.rcpPurshaseOrderContainers;
    }

    public void setRcpPurshaseOrderContainers(Short rcpPurshaseOrderContainers) {
        this.rcpPurshaseOrderContainers = rcpPurshaseOrderContainers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderwarehousesourceid")
    public WrhWarehouse getWrhWarehouseSource() {
        return this.wrhWarehouseSource;
    }

    public void setWrhWarehouseSource(WrhWarehouse wrhWarehouseSource) {
        this.wrhWarehouseSource = wrhWarehouseSource;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderwarehousedestinationid", nullable = false)
    public WrhWarehouse getWrhWarehouseDestination() {
        return wrhWarehouseDestination;
    }

    public void setWrhWarehouseDestination(WrhWarehouse wrhWarehouseDestination) {
        this.wrhWarehouseDestination = wrhWarehouseDestination;
    }

    @Column(name = "rcp_purshaseordertransportcontact", length = 50)
    public String getRcpPurshaseOrderTransportContact() {
        return this.rcpPurshaseOrderTransportContact;
    }

    public void setRcpPurshaseOrderTransportContact(
            String rcpPurshaseOrderTransportContact) {
        this.rcpPurshaseOrderTransportContact = rcpPurshaseOrderTransportContact;
    }

    @Column(name = "rcp_purshaseorderimmatriculation", length = 20)
    public String getRcpPurshaseOrderImmatriculation() {
        return this.rcpPurshaseOrderImmatriculation;
    }

    public void setRcpPurshaseOrderImmatriculation(
            String rcpPurshaseOrderImmatriculation) {
        this.rcpPurshaseOrderImmatriculation = rcpPurshaseOrderImmatriculation;
    }

    @Column(name = "rcp_purshaseordertelcontact", length = 20)
    public String getRcpPurshaseOrderTelContact() {
        return this.rcpPurshaseOrderTelContact;
    }

    public void setRcpPurshaseOrderTelContact(String rcpPurshaseOrderTelContact) {
        this.rcpPurshaseOrderTelContact = rcpPurshaseOrderTelContact;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rcp_purshaseordercreationdate")
    public Date getRcpPurshaseOrderCreationDate() {
        return this.rcpPurshaseOrderCreationDate;
    }

    public void setRcpPurshaseOrderCreationDate(
            Date rcpPurshaseOrderCreationDate) {
        this.rcpPurshaseOrderCreationDate = rcpPurshaseOrderCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "rcp_purshaseorderupdatedate")
    public Date getRcpPurshaseOrderUpdateDate() {
        return this.rcpPurshaseOrderUpdateDate;
    }

    public void setRcpPurshaseOrderUpdateDate(Date rcpPurshaseOrderUpdateDate) {
        this.rcpPurshaseOrderUpdateDate = rcpPurshaseOrderUpdateDate;
    }

    @Column(name = "rcp_purshaseordervariable1")
    public String getRcpPurshaseOrderVariable1() {
        return this.rcpPurshaseOrderVariable1;
    }

    public void setRcpPurshaseOrderVariable1(String rcpPurshaseOrderVariable1) {
        this.rcpPurshaseOrderVariable1 = rcpPurshaseOrderVariable1;
    }

    @Column(name = "rcp_purshaseordervariable2")
    public String getRcpPurshaseOrderVariable2() {
        return this.rcpPurshaseOrderVariable2;
    }

    public void setRcpPurshaseOrderVariable2(String rcpPurshaseOrderVariable2) {
        this.rcpPurshaseOrderVariable2 = rcpPurshaseOrderVariable2;
    }

    @Column(name = "rcp_purshaseordervariable3")
    public String getRcpPurshaseOrderVariable3() {
        return this.rcpPurshaseOrderVariable3;
    }

    public void setRcpPurshaseOrderVariable3(String rcpPurshaseOrderVariable3) {
        this.rcpPurshaseOrderVariable3 = rcpPurshaseOrderVariable3;
    }

    @Column(name = "rcp_purshaseordervariable4")
    public String getRcpPurshaseOrderVariable4() {
        return this.rcpPurshaseOrderVariable4;
    }

    public void setRcpPurshaseOrderVariable4(String rcpPurshaseOrderVariable4) {
        this.rcpPurshaseOrderVariable4 = rcpPurshaseOrderVariable4;
    }

    @Column(name = "rcp_purshaseordervariable5")
    public String getRcpPurshaseOrderVariable5() {
        return this.rcpPurshaseOrderVariable5;
    }

    public void setRcpPurshaseOrderVariable5(String rcpPurshaseOrderVariable5) {
        this.rcpPurshaseOrderVariable5 = rcpPurshaseOrderVariable5;
    }

    @Column(name = "rcp_purshaseordervariable6")
    public String getRcpPurshaseOrderVariable6() {
        return this.rcpPurshaseOrderVariable6;
    }

    public void setRcpPurshaseOrderVariable6(String rcpPurshaseOrderVariable6) {
        this.rcpPurshaseOrderVariable6 = rcpPurshaseOrderVariable6;
    }

    @Column(name = "rcp_purshaseordervariable7")
    public String getRcpPurshaseOrderVariable7() {
        return this.rcpPurshaseOrderVariable7;
    }

    public void setRcpPurshaseOrderVariable7(String rcpPurshaseOrderVariable7) {
        this.rcpPurshaseOrderVariable7 = rcpPurshaseOrderVariable7;
    }

    @Column(name = "rcp_purshaseordervariable8")
    public String getRcpPurshaseOrderVariable8() {
        return this.rcpPurshaseOrderVariable8;
    }

    public void setRcpPurshaseOrderVariable8(String rcpPurshaseOrderVariable8) {
        this.rcpPurshaseOrderVariable8 = rcpPurshaseOrderVariable8;
    }

    @Column(name = "rcp_purshaseordervariable9")
    public String getRcpPurshaseOrderVariable9() {
        return this.rcpPurshaseOrderVariable9;
    }

    public void setRcpPurshaseOrderVariable9(String rcpPurshaseOrderVariable9) {
        this.rcpPurshaseOrderVariable9 = rcpPurshaseOrderVariable9;
    }

    @Column(name = "rcp_purshaseordervariable10")
    public String getRcpPurshaseOrderVariable10() {
        return this.rcpPurshaseOrderVariable10;
    }

    public void setRcpPurshaseOrderVariable10(String rcpPurshaseOrderVariable10) {
        this.rcpPurshaseOrderVariable10 = rcpPurshaseOrderVariable10;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "rcpPurshaseOrder", orphanRemoval = true)
    public Set<RcpPurshaseOrderLine> getRcpPurshaseOrderLines() {
        return this.rcpPurshaseOrderLines;
    }

    public void setRcpPurshaseOrderLines(
            Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines) {
        this.rcpPurshaseOrderLines = rcpPurshaseOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rcpPurshaseOrder")
    public Set<RcpReception> getRcpReceptions() {
        return this.rcpReceptions;
    }

    public void setRcpReceptions(Set<RcpReception> rcpReceptions) {
        this.rcpReceptions = rcpReceptions;
    }

    @Column(name = "rcp_purshaseordercmdtype")
    public Long getRcpPurshaseOrderCmdType() {
        return rcpPurshaseOrderCmdType;
    }

    public void setRcpPurshaseOrderCmdType(Long rcpPurshaseOrderCmdType) {
        this.rcpPurshaseOrderCmdType = rcpPurshaseOrderCmdType;
    }

    @Column(name = "rcp_purshaseorderaccountordercode", length = 50)

    public String getRcpPurshaseOrderAccountOrderCode() {
        return rcpPurshaseOrderAccountOrderCode;
    }

    public void setRcpPurshaseOrderAccountOrderCode(String rcpPurshaseOrderAccountOrderCode) {
        this.rcpPurshaseOrderAccountOrderCode = rcpPurshaseOrderAccountOrderCode;
    }

    @Column(name = "rcp_purshaseordertransfertcode")
    public String getRcpPurshaseOrderTransfertCode() {
        return rcpPurshaseOrderTransfertCode;
    }

    public void setRcpPurshaseOrderTransfertCode(String rcpPurshaseOrderTransfertCode) {
        this.rcpPurshaseOrderTransfertCode = rcpPurshaseOrderTransfertCode;
    }

    @Column(name = "rcp_purshaseordertotalpriceht")
    public BigDecimal getRcpPurshaseOrderTotalPriceHT() {
        return rcpPurshaseOrderTotalPriceHT;
    }

    public void setRcpPurshaseOrderTotalPriceHT(BigDecimal rcpPurshaseOrdertotalPriceHT) {
        this.rcpPurshaseOrderTotalPriceHT = rcpPurshaseOrdertotalPriceHT;
    }

    @Column(name = "rcp_purshaseordertotalpricettc")
    public BigDecimal getRcpPurshaseOrderTotalPriceTTC() {
        return rcpPurshaseOrderTotalPriceTTC;
    }

    public void setRcpPurshaseOrderTotalPriceTTC(BigDecimal rcpPurshaseOrdertotalPriceTTC) {
        this.rcpPurshaseOrderTotalPriceTTC = rcpPurshaseOrdertotalPriceTTC;
    }

    @Column(name = "rcp_purshaseorderdiscount")
    public BigDecimal getRcpPurshaseOrderDiscount() {
        return rcpPurshaseOrderDiscount;
    }

    public void setRcpPurshaseOrderDiscount(BigDecimal rcpPurshaseOrderdiscount) {
        this.rcpPurshaseOrderDiscount = rcpPurshaseOrderdiscount;
    }

    @Column(name = "rcp_purshaseordervat")
    public BigDecimal getRcpPurshaseOrderVat() {
        return rcpPurshaseOrderVat;
    }

    public void setRcpPurshaseOrderVat(BigDecimal rcpPurshaseOrdervat) {
        this.rcpPurshaseOrderVat = rcpPurshaseOrdervat;
    }

   /* @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseordercurrencyid")
    public PrmCurrency getPrmCurrency() {
        return prmCurrency;
    }

    public void setPrmCurrency(PrmCurrency prmCurrency) {
        this.prmCurrency = prmCurrency;
    }
*/
    @Column(name = "rcp_purshaseorderactive")
    public Boolean getRcpPurshaseOrderActive() {
        return rcpPurshaseOrderActive;
    }

    public void setRcpPurshaseOrderActive(Boolean rcpPurshaseOrderActive) {
        this.rcpPurshaseOrderActive = rcpPurshaseOrderActive;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseordersaleorderid")
    public CmdSaleOrder getCmdSaleOrder() {
        return cmdSaleOrder;
    }

    public void setCmdSaleOrder(CmdSaleOrder cmdSaleOrder) {
        this.cmdSaleOrder = cmdSaleOrder;
    }

  /*  @OneToMany(fetch = FetchType.LAZY, mappedBy = "rcpPurshaseOrder", cascade = CascadeType.ALL)
    public Set<RcpBillingTerm> getRcpBillingTerms() {
        return rcpBillingTerms;
    }

    public void setRcpBillingTerms(Set<RcpBillingTerm> rcpBillingTerms) {
        this.rcpBillingTerms = rcpBillingTerms;
    }
*/
    @Column(name = "rcp_purshaseorderaccounted")
    public Boolean getRcpPurshaseOrderAccounted() {
        return rcpPurshaseOrderAccounted;
    }

    public void setRcpPurshaseOrderAccounted(Boolean rcpPurshaseOrderAccounted) {
        this.rcpPurshaseOrderAccounted = rcpPurshaseOrderAccounted;
    }

   /* @OneToMany(fetch = FetchType.LAZY, mappedBy = "rcpPurshaseOrder")
    public Set<RcpExtraCost> getRcpExtraCosts() {
        return rcpExtraCosts;
    }

    public void setRcpExtraCosts(Set<RcpExtraCost> rcpExtraCosts) {
        this.rcpExtraCosts = rcpExtraCosts;
    }
*/
 /*  @JoinColumn(name = "rcp_purshaseorderpaymentstatusid")
    @ManyToOne(fetch = FetchType.LAZY)
    public PrmPaymentStatus getPrmPaymentStatus() {
        return prmPaymentStatus;
    }

    public void setPrmPaymentStatus(PrmPaymentStatus prmPaymentStatus) {
        this.prmPaymentStatus = prmPaymentStatus;
    }
*/
  /* @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rcp_purshaseorderboxid")
    public UsrBox getUsrBox() {
        return usrBox;
    }

    public void setUsrBox(UsrBox usrBox) {
        this.usrBox = usrBox;
    }
*/
    @Column(name = "rcp_purshaseorderpayedamount")
    public BigDecimal getRcpPurshaseOrderPayedAmount() {
        return rcpPurshaseOrderPayedAmount;
    }

    public void setRcpPurshaseOrderPayedAmount(BigDecimal rcpPurshaseOrderPayedAmount) {
        this.rcpPurshaseOrderPayedAmount = rcpPurshaseOrderPayedAmount;
    }

    @Column(name = "rcp_purchaseordertotalpricehtdefaultcurrency")
    public BigDecimal getRcpPurshaseTotalPriceHTDefaultCurrency() {
        return rcpPurshaseTotalPriceHTDefaultCurrency;
    }

    public void setRcpPurshaseTotalPriceHTDefaultCurrency(BigDecimal rcpPurshaseTotalPriceHTDefaultCurrency) {
        this.rcpPurshaseTotalPriceHTDefaultCurrency = rcpPurshaseTotalPriceHTDefaultCurrency;
    }

    @Column(name = "rcp_purchaseordertotalpricettcdefaultcurrency")

    public BigDecimal getRcpPurshaseTotalPriceTTCDefaultCurrency() {
        return rcpPurshaseTotalPriceTTCDefaultCurrency;
    }

    public void setRcpPurshaseTotalPriceTTCDefaultCurrency(BigDecimal rcpPurshaseTotalPriceTTCDefaultCurrency) {
        this.rcpPurshaseTotalPriceTTCDefaultCurrency = rcpPurshaseTotalPriceTTCDefaultCurrency;
    }

    @Column(name = "rcp_purchaseordervatdefaultcurrency")

    public BigDecimal getRcpPurshaseVatDefaultCurrency() {
        return rcpPurshaseVatDefaultCurrency;
    }

    public void setRcpPurshaseVatDefaultCurrency(BigDecimal rcpPurshaseVatDefaultCurrency) {
        this.rcpPurshaseVatDefaultCurrency = rcpPurshaseVatDefaultCurrency;
    }

    @Column(name = "rcp_purchaseorderexchangerate")

    public BigDecimal getRcpPurshaseExchangeRate() {
        return rcpPurshaseExchangeRate;
    }

    public void setRcpPurshaseExchangeRate(BigDecimal rcpPurshaseExchangeRate) {
        this.rcpPurshaseExchangeRate = rcpPurshaseExchangeRate;
    }

    @Column(name = "rcp_purshaseorderprovisionalcost")
    public BigDecimal getRcpPurshaseOrderProvisionalCost() {
        return rcpPurshaseOrderProvisionalCost;
    }

    public void setRcpPurshaseOrderProvisionalCost(BigDecimal rcpPurshaseOrderProvisionalCost) {
        this.rcpPurshaseOrderProvisionalCost = rcpPurshaseOrderProvisionalCost;
    }

    @Column(name = "rcp_purshaseorderextracost")
    public BigDecimal getRcpPurshaseOrderExtraCost() {
        return rcpPurshaseOrderExtraCost;
    }

    public void setRcpPurshaseOrderExtraCost(BigDecimal rcpPurshaseOrderExtraCost) {
        this.rcpPurshaseOrderExtraCost = rcpPurshaseOrderExtraCost;
    }

   /* @JoinColumn(name = "rcp_purshaseorderdealid")
    @ManyToOne(fetch = FetchType.LAZY)
    public CmdDeal getCmdDeal() {
        return cmdDeal;
    }

    public void setCmdDeal(CmdDeal cmdDeal) {
        this.cmdDeal = cmdDeal;
    }
    */
    @JoinColumn(name = "rcp_purshaseorderaccountid")
    @ManyToOne(fetch = FetchType.LAZY)
    public CmdAccount getCmdAccount() {
        return cmdAccount;
    }

    public void setCmdAccount(CmdAccount cmdAccount) {
        this.cmdAccount = cmdAccount;
    }
}
