package com.bagile.gmo.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Subselect;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;

/**
 * StkStockView generated by hbm2java
 */
@Entity
@Subselect("select * from schema_crmexpress.stk_gmostockview")
@Immutable
@Table(name = "stk_stockview")

public class StkStockView implements java.io.Serializable {


    private Long pdtProductId;

    @NotNull
    private PdtProduct pdtProduct;



    private BigDecimal stk_stockviewquantity;

    private BigDecimal stk_stockviewpriceht;

    public StkStockView() {
    }





    @Id
    @Column(name = "pdt_productid")
    public Long getPdtProductId() {
        return this.pdtProductId;
    }

    public void setPdtProductId(Long pdtProductId) {
        this.pdtProductId = pdtProductId;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockproductid", nullable = false)
    public PdtProduct getPdtProduct() {
        return this.pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }



    @Column(name = "stk_stockviewquantity")
    public BigDecimal getStk_stockviewquantity() {
        return stk_stockviewquantity;
    }

    public void setStk_stockviewquantity(BigDecimal stk_stockviewquantity) {
        this.stk_stockviewquantity = stk_stockviewquantity;
    }

    @Column(name = "stk_stockviewpriceht")

    public BigDecimal getStk_stockviewpriceht() {
        return stk_stockviewpriceht;
    }

    public void setStk_stockviewpriceht(BigDecimal stk_stockviewpriceht) {
        this.stk_stockviewpriceht = stk_stockviewpriceht;
    }


}
