package com.bagile.gmo.entities;


import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * UsrUser generated by hbm2java
 */
@Entity
@Table(name = "usr_agency")
public class UsrAgency extends EmsEntity implements Serializable {

    private long usrAgencyId;
    @NotNull
    private String usrAgencyCode;
    private String usrAgencyDescription;
    private GmoZone usrAgencyZone;
    private AdrAddress adrAddress;

    private UsrUser usrAgencyResponsable;


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_usr_agency", allocationSize = 1)
    @Column(name = "usr_agencyid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getUsrAgencyId() {
        return usrAgencyId;
    }

    public void setUsrAgencyId(long usrAgencyId) {
        this.usrAgencyId = usrAgencyId;
    }

    @Column(name = "usr_agencycode", unique = true, nullable = false, length = 50)
    public String getUsrAgencyCode() {
        return usrAgencyCode;
    }

    public void setUsrAgencyCode(String usrAgencyCode) {
        this.usrAgencyCode = usrAgencyCode;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
    @JoinColumn(name = "usr_agencyzoneid")
    public GmoZone getUsrAgencyZone() {
        return usrAgencyZone;
    }

    public void setUsrAgencyZone(GmoZone usrAgencyZone) {
        this.usrAgencyZone = usrAgencyZone;
    }

    @Column(name = "usr_agencydescription", length = 150)
    public String getUsrAgencyDescription() {
        return usrAgencyDescription;
    }

    public void setUsrAgencyDescription(String usrAgencyDescription) {
        this.usrAgencyDescription = usrAgencyDescription;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
    @JoinColumn(name = "usr_agencyresponsableid")
    public UsrUser getUsrAgencyResponsable() {
        return usrAgencyResponsable;
    }

    public void setUsrAgencyResponsable(UsrUser usrAgencyResponsable) {
        this.usrAgencyResponsable = usrAgencyResponsable;
    }


    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
    @JoinColumn(name = "usr_agencyaddressid")
    public AdrAddress getAdrAddress() {
        return adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }
}