package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvInvoiceArc generated by hbm2java
 */
@Entity
@Table(name = "inv_invoice_arc", uniqueConstraints = @UniqueConstraint(columnNames = "inv_invoicecode"))
public class InvInvoiceArc implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 8659566996635917310L;

    private long invInvoiceId;
    @NotNull
    private OwnOwner ownOwner;
    @NotNull
    private AdrAddress adrAddress;
    private PrmContact prmContact;
    @Size(max = 30)
    @NotNull
    private String invInvoiceCode;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoiceCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoiceUpdateDate;

    private String invInvoiceState;
    private BigDecimal invInvoiceVat;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoiceDate;
    private String invInvoiceComment;

    private Set<InvInvoiceLineArc> invInvoiceLines = new HashSet<InvInvoiceLineArc>(0);

    public InvInvoiceArc() {
    }



    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_inv_invoice_arc", allocationSize = 1)
    @Column(name = "inv_invoiceid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getInvInvoiceId() {
        return this.invInvoiceId;
    }

    public void setInvInvoiceId(long invInvoiceId) {
        this.invInvoiceId = invInvoiceId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoiceownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoiceaddressid", nullable = false)
    public AdrAddress getAdrAddress() {
        return this.adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoicecontactid")
    public PrmContact getPrmContact() {
        return this.prmContact;
    }

    public void setPrmContact(PrmContact prmContact) {
        this.prmContact = prmContact;
    }

    @Column(name = "inv_invoicecode", unique = true, nullable = false, length = 30)
    public String getInvInvoiceCode() {
        return this.invInvoiceCode;
    }

    public void setInvInvoiceCode(String invInvoiceCode) {
        this.invInvoiceCode = invInvoiceCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicecreationdate")
    public Date getInvInvoiceCreationDate() {
        return this.invInvoiceCreationDate;
    }

    public void setInvInvoiceCreationDate(Date invInvoiceCreationDate) {
        this.invInvoiceCreationDate = invInvoiceCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoiceupdatedate", nullable = false, length = 13)
    public Date getInvInvoiceUpdateDate() {
        return this.invInvoiceUpdateDate;
    }

    public void setInvInvoiceUpdateDate(Date invInvoiceUpdateDate) {
        this.invInvoiceUpdateDate = invInvoiceUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "invInvoice", orphanRemoval=true)
    public Set<InvInvoiceLineArc> getInvInvoiceLines() {
        return this.invInvoiceLines;
    }

    public void setInvInvoiceLines(Set<InvInvoiceLineArc> invInvoiceLines) {
        this.invInvoiceLines = invInvoiceLines;
    }

    @Column(name = "inv_invoicestate")
    public String getInvInvoiceState() {
        return invInvoiceState;
    }

    public void setInvInvoiceState(String invInvoiceState) {
        this.invInvoiceState = invInvoiceState;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicedate")
    public Date getInvInvoiceDate() {
        return invInvoiceDate;
    }

    public void setInvInvoiceDate(Date invInvoiceDate) {
        this.invInvoiceDate = invInvoiceDate;
    }

    @Column(name = "inv_invoicevat")
    public BigDecimal getInvInvoiceVat() {
        return invInvoiceVat;
    }

    public void setInvInvoiceVat(BigDecimal invInvoiceVat) {
        this.invInvoiceVat = invInvoiceVat;
    }

    @Column(name = "inv_invoicecomment")
    public String getInvInvoiceComment() {
        return invInvoiceComment;
    }

    public void setInvInvoiceComment(String invInvoiceComment) {
        this.invInvoiceComment = invInvoiceComment;
    }
}
