package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvInvoice generated by hbm2java
 */
@Entity
@Table(name = "inv_invoice", uniqueConstraints = @UniqueConstraint(columnNames = "inv_invoicecode"))
public class InvInvoice implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1732891692175669334L;
    private long invInvoiceId;
    @NotNull
    private OwnOwner ownOwner;
    @NotNull
    private AdrAddress adrAddress;
    @Size(max = 30)
    @NotNull
    private String invInvoiceCode;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoiceCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoiceUpdateDate;

    private Long invInvoiceState;
    private BigDecimal invInvoiceVat;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoiceDate;
    private String invInvoiceComment;
    @Size(max = 30)
    @NotNull
    private String invInvoiceName;
    @Size(max = 30)
    @NotNull
    private String invInvoiceSurname;
    @Size(max = 20)

    private String invInvoiceEmail;
    @Size(max = 20)
    private String invInvoicePrimaryTel;
    @Size(max = 20)
    private String invInvoiceSecondaryTel;
    private String invInvoiceFax;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date invInvoicStartDate;

    private Set<InvInvoiceLine> invInvoiceLines = new HashSet<InvInvoiceLine>(0);

    public InvInvoice() {
    }

    public InvInvoice(long invInvoiceId, OwnOwner ownOwner,
                      AdrAddress adrAddress, String invInvoiceCode,
                      Date invInvoiceUpdateDate) {
        this.invInvoiceId = invInvoiceId;
        this.ownOwner = ownOwner;
        this.adrAddress = adrAddress;
        this.invInvoiceCode = invInvoiceCode;
        this.invInvoiceUpdateDate = invInvoiceUpdateDate;
    }

    public InvInvoice(long invInvoiceId, OwnOwner ownOwner,
                      AdrAddress adrAddress,
                      String invInvoiceCode, Date invInvoiceCreationDate,
                      Date invInvoiceUpdateDate, Set<InvInvoiceLine> invInvoiceLines) {
        this.invInvoiceId = invInvoiceId;
        this.ownOwner = ownOwner;
        this.adrAddress = adrAddress;
        this.invInvoiceCode = invInvoiceCode;
        this.invInvoiceCreationDate = invInvoiceCreationDate;
        this.invInvoiceUpdateDate = invInvoiceUpdateDate;
        this.invInvoiceLines = invInvoiceLines;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_inv_invoice", allocationSize = 1)
    @Column(name = "inv_invoiceid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getInvInvoiceId() {
        return this.invInvoiceId;
    }

    public void setInvInvoiceId(long invInvoiceId) {
        this.invInvoiceId = invInvoiceId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoiceownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoiceaddressid", nullable = false)
    public AdrAddress getAdrAddress() {
        return this.adrAddress;
    }

    public void setAdrAddress(AdrAddress adrAddress) {
        this.adrAddress = adrAddress;
    }



    @Column(name = "inv_invoicecode", unique = true, nullable = false, length = 30)
    public String getInvInvoiceCode() {
        return this.invInvoiceCode;
    }

    public void setInvInvoiceCode(String invInvoiceCode) {
        this.invInvoiceCode = invInvoiceCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicecreationdate")
    public Date getInvInvoiceCreationDate() {
        return this.invInvoiceCreationDate;
    }

    public void setInvInvoiceCreationDate(Date invInvoiceCreationDate) {
        this.invInvoiceCreationDate = invInvoiceCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoiceupdatedate", nullable = false, length = 13)
    public Date getInvInvoiceUpdateDate() {
        return this.invInvoiceUpdateDate;
    }

    public void setInvInvoiceUpdateDate(Date invInvoiceUpdateDate) {
        this.invInvoiceUpdateDate = invInvoiceUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "invInvoice", orphanRemoval=true)
    public Set<InvInvoiceLine> getInvInvoiceLines() {
        return this.invInvoiceLines;
    }

    public void setInvInvoiceLines(Set<InvInvoiceLine> invInvoiceLines) {
        this.invInvoiceLines = invInvoiceLines;
    }

    @Column(name = "inv_invoicestate")
    public Long getInvInvoiceState() {
        return invInvoiceState;
    }

    public void setInvInvoiceState(Long invInvoiceState) {
        this.invInvoiceState = invInvoiceState;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicedate")
    public Date getInvInvoiceDate() {
        return invInvoiceDate;
    }

    public void setInvInvoiceDate(Date invInvoiceDate) {
        this.invInvoiceDate = invInvoiceDate;
    }

    @Column(name = "inv_invoicevat")
    public BigDecimal getInvInvoiceVat() {
        return invInvoiceVat;
    }

    public void setInvInvoiceVat(BigDecimal invInvoiceVat) {
        this.invInvoiceVat = invInvoiceVat;
    }

    @Column(name = "inv_invoicecomment")
    public String getInvInvoiceComment() {
        return invInvoiceComment;
    }

    public void setInvInvoiceComment(String invInvoiceComment) {
        this.invInvoiceComment = invInvoiceComment;
    }
    @Column(name = "inv_invoicename")

    public String getInvInvoiceName() {
        return invInvoiceName;
    }

    public void setInvInvoiceName(String invInvoiceName) {
        this.invInvoiceName = invInvoiceName;
    }
    @Column(name = "inv_invoicesurname")

    public String getInvInvoiceSurname() {
        return invInvoiceSurname;
    }

    public void setInvInvoiceSurname(String invInvoiceSurname) {
        this.invInvoiceSurname = invInvoiceSurname;
    }
    @Column(name = "inv_invoiceemail")

    public String getInvInvoiceEmail() {
        return invInvoiceEmail;
    }

    public void setInvInvoiceEmail(String invInvoiceEmail) {
        this.invInvoiceEmail = invInvoiceEmail;
    }
    @Column(name = "inv_invoiceprimarytel")

    public String getInvInvoicePrimaryTel() {
        return invInvoicePrimaryTel;
    }

    public void setInvInvoicePrimaryTel(String invInvoicePrimaryTel) {
        this.invInvoicePrimaryTel = invInvoicePrimaryTel;
    }
    @Column(name = "inv_invoicesecondarytel")

    public String getInvInvoiceSecondaryTel() {
        return invInvoiceSecondaryTel;
    }

    public void setInvInvoiceSecondaryTel(String invInvoiceSecondaryTel) {
        this.invInvoiceSecondaryTel = invInvoiceSecondaryTel;
    }
    @Column(name = "inv_invoicefax")

    public String getInvInvoiceFax() {
        return invInvoiceFax;
    }

    public void setInvInvoiceFax(String invInvoiceFax) {
        this.invInvoiceFax = invInvoiceFax;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicestartdate")

    public Date getInvInvoicStartDate() {
        return invInvoicStartDate;
    }

    public void setInvInvoicStartDate(Date invInvoicStartDate) {
        this.invInvoicStartDate = invInvoicStartDate;
    }
}
