package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * InvInvoicelineArc generated by hbm2java
 */
@Entity
@Table(name = "inv_invoiceline_arc")
public class InvInvoiceLineArc implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 220258602987465342L;

    private long invInvoiceLinesId;
    @NotNull
    private InvInvoiceArc invInvoice;
    @NotNull
    private InvMovementType invMovementType;
    @NotNull
    private OwnOwner ownOwner;

    @Max(999999999)
    @NotNull
    private long invInvoiceLinesLineNumber;

    @Max(999999999)
    @NotNull
    private BigDecimal invInvoiceLinesTarifPrice;

    @Max(999999999)
    @NotNull
    private BigDecimal invInvoiceLinesDiscount;

    @Max(999999999)
    @NotNull
    private BigDecimal invInvoiceLinesQuantity;

    @Max(999999999)
    @NotNull
    private BigDecimal invInvoiceLinesTotalPriceHT;

    @Max(999999999)
    @NotNull
    private BigDecimal invInvoiceLinesTotalPriceTTC;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date invInvoiceLinesCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date invInvoiceLinesUpdateDate;
    @Size(max = 255)
    private String invInvoiceLinesVariable1;
    @Size(max = 255)
    private String invInvoiceLinesVariable2;
    @Size(max = 255)
    private String invInvoiceLinesVariable3;
    @Size(max = 255)
    private String invInvoiceLinesVariable4;
    @Size(max = 255)
    private String invInvoiceLinesVariable5;
    @Size(max = 255)
    private String invInvoiceLinesVariable6;
    @Size(max = 255)
    private String invInvoiceLinesVariable7;
    @Size(max = 255)
    private String invInvoiceLinesVariable8;
    @Size(max = 255)
    private String invInvoiceLinesVariable9;
    @Size(max = 255)
    private String invInvoiceLinesVariable10;

    private String invInvoiceLinesComment;
    public InvInvoiceLineArc() {
    }





    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_inv_invoicelines_arc", allocationSize = 1)
    @Column(name = "inv_invoicelinesid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getInvInvoiceLinesId() {
        return this.invInvoiceLinesId;
    }

    public void setInvInvoiceLinesId(long invInvoiceLinesId) {
        this.invInvoiceLinesId = invInvoiceLinesId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoicelinesinvoiceid", nullable = false)
    public InvInvoiceArc getInvInvoice() {
        return this.invInvoice;
    }

    public void setInvInvoice(InvInvoiceArc invInvoice) {
        this.invInvoice = invInvoice;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoicelinesmovtypeid", nullable = false)
    public InvMovementType getInvMovementType() {
        return this.invMovementType;
    }

    public void setInvMovementType(InvMovementType invMovementType) {
        this.invMovementType = invMovementType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_invoicelinesownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @Column(name = "inv_invoicelineslinenumber", nullable = false, precision = 10, scale = 0)
    public long getInvInvoiceLinesLineNumber() {
        return this.invInvoiceLinesLineNumber;
    }

    public void setInvInvoiceLinesLineNumber(long invInvoiceLinesLineNumber) {
        this.invInvoiceLinesLineNumber = invInvoiceLinesLineNumber;
    }

    @Column(name = "inv_invoicelinestarifprice", nullable = false, precision = 12, scale = 5)
    public BigDecimal getInvInvoiceLinesTarifPrice() {
        return this.invInvoiceLinesTarifPrice;
    }

    public void setInvInvoiceLinesTarifPrice(
            BigDecimal invInvoiceLinesTarifPrice) {
        this.invInvoiceLinesTarifPrice = invInvoiceLinesTarifPrice;
    }

    @Column(name = "inv_invoicelinesdiscount", nullable = false, precision = 6, scale = 3)
    public BigDecimal getInvInvoiceLinesDiscount() {
        return this.invInvoiceLinesDiscount;
    }

    public void setInvInvoiceLinesDiscount(BigDecimal invInvoiceLinesDiscount) {
        this.invInvoiceLinesDiscount = invInvoiceLinesDiscount;
    }

    @Column(name = "inv_invoicelinesquantity", nullable = false, precision = 12, scale = 5)
    public BigDecimal getInvInvoiceLinesQuantity() {
        return this.invInvoiceLinesQuantity;
    }

    public void setInvInvoiceLinesQuantity(BigDecimal invInvoiceLinesQuantity) {
        this.invInvoiceLinesQuantity = invInvoiceLinesQuantity;
    }

    @Column(name = "inv_invoicelinestotalpriceht", nullable = false, precision = 12, scale = 5)
    public BigDecimal getInvInvoiceLinesTotalPriceHT() {
        return this.invInvoiceLinesTotalPriceHT;
    }

    public void setInvInvoiceLinesTotalPriceHT(
            BigDecimal invInvoiceLinesTotalPriceHT) {
        this.invInvoiceLinesTotalPriceHT = invInvoiceLinesTotalPriceHT;
    }

    @Column(name = "inv_invoicelinestotalpricettc", nullable = false, precision = 12, scale = 5)
    public BigDecimal getInvInvoiceLinesTotalPriceTTC() {
        return this.invInvoiceLinesTotalPriceTTC;
    }

    public void setInvInvoiceLinesTotalPriceTTC(
            BigDecimal invInvoiceLinesTotalPriceTTC) {
        this.invInvoiceLinesTotalPriceTTC = invInvoiceLinesTotalPriceTTC;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicelinescreationdate")
    public Date getInvInvoiceLinesCreationDate() {
        return this.invInvoiceLinesCreationDate;
    }

    public void setInvInvoiceLinesCreationDate(Date invInvoiceLinesCreationDate) {
        this.invInvoiceLinesCreationDate = invInvoiceLinesCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "inv_invoicelinesupdatedate")
    public Date getInvInvoiceLinesUpdateDate() {
        return this.invInvoiceLinesUpdateDate;
    }

    public void setInvInvoiceLinesUpdateDate(Date invInvoiceLinesUpdateDate) {
        this.invInvoiceLinesUpdateDate = invInvoiceLinesUpdateDate;
    }

    @Column(name = "inv_invoicelinesvariable1")
    public String getInvInvoiceLinesVariable1() {
        return this.invInvoiceLinesVariable1;
    }

    public void setInvInvoiceLinesVariable1(String invInvoiceLinesVariable1) {
        this.invInvoiceLinesVariable1 = invInvoiceLinesVariable1;
    }

    @Column(name = "inv_invoicelinesvariable2")
    public String getInvInvoiceLinesVariable2() {
        return this.invInvoiceLinesVariable2;
    }

    public void setInvInvoiceLinesVariable2(String invInvoiceLinesVariable2) {
        this.invInvoiceLinesVariable2 = invInvoiceLinesVariable2;
    }

    @Column(name = "inv_invoicelinesvariable3", length = 254)
    public String getInvInvoiceLinesVariable3() {
        return this.invInvoiceLinesVariable3;
    }

    public void setInvInvoiceLinesVariable3(String invInvoiceLinesVariable3) {
        this.invInvoiceLinesVariable3 = invInvoiceLinesVariable3;
    }

    @Column(name = "inv_invoicelinesvariable4")
    public String getInvInvoiceLinesVariable4() {
        return this.invInvoiceLinesVariable4;
    }

    public void setInvInvoiceLinesVariable4(String invInvoiceLinesVariable4) {
        this.invInvoiceLinesVariable4 = invInvoiceLinesVariable4;
    }

    @Column(name = "inv_invoicelinesvariable5")
    public String getInvInvoiceLinesVariable5() {
        return this.invInvoiceLinesVariable5;
    }

    public void setInvInvoiceLinesVariable5(String invInvoiceLinesVariable5) {
        this.invInvoiceLinesVariable5 = invInvoiceLinesVariable5;
    }

    @Column(name = "inv_invoicelinesvariable6")
    public String getInvInvoiceLinesVariable6() {
        return this.invInvoiceLinesVariable6;
    }

    public void setInvInvoiceLinesVariable6(String invInvoiceLinesVariable6) {
        this.invInvoiceLinesVariable6 = invInvoiceLinesVariable6;
    }

    @Column(name = "inv_invoicelinesvariable7")
    public String getInvInvoiceLinesVariable7() {
        return this.invInvoiceLinesVariable7;
    }

    public void setInvInvoiceLinesVariable7(String invInvoiceLinesVariable7) {
        this.invInvoiceLinesVariable7 = invInvoiceLinesVariable7;
    }

    @Column(name = "inv_invoicelinesvariable8")
    public String getInvInvoiceLinesVariable8() {
        return this.invInvoiceLinesVariable8;
    }

    public void setInvInvoiceLinesVariable8(String invInvoiceLinesVariable8) {
        this.invInvoiceLinesVariable8 = invInvoiceLinesVariable8;
    }

    @Column(name = "inv_invoicelinesvariable9")
    public String getInvInvoiceLinesVariable9() {
        return this.invInvoiceLinesVariable9;
    }

    public void setInvInvoiceLinesVariable9(String invInvoiceLinesVariable9) {
        this.invInvoiceLinesVariable9 = invInvoiceLinesVariable9;
    }

    @Column(name = "inv_invoicelinesvariable10")
    public String getInvInvoiceLinesVariable10() {
        return this.invInvoiceLinesVariable10;
    }

    public void setInvInvoiceLinesVariable10(String invInvoiceLinesVariable10) {
        this.invInvoiceLinesVariable10 = invInvoiceLinesVariable10;
    }

    @Column(name = "inv_invoicelinescomment")
    public String getInvInvoiceLinesComment() {
        return invInvoiceLinesComment;
    }

    public void setInvInvoiceLinesComment(String invInvoiceLinesComment) {
        this.invInvoiceLinesComment = invInvoiceLinesComment;
    }

}
