package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvMovementType generated by hbm2java
 */
@Entity
@Table(name = "inv_movementtype", uniqueConstraints = @UniqueConstraint(columnNames = "inv_movementtypecode"))
public class InvMovementType implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 4145090374969605488L;

    private long invMovementTypeId;
    @Size(max = 30)
    @NotNull
    private String invMovementTypeCode;
    @Size(max = 255)
    private String invMovementTypeDescription;
    private Date invMovementTypeUpdateDate;
    private Date invMovementTypeCreationDate;
    private Boolean invMovementTypeActive;
    private OrgOrganisation orgOrganisation;


    public InvMovementType() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_inv_movementtype", allocationSize = 1)
    @Column(name = "inv_movementtypeid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getInvMovementTypeId() {
        return this.invMovementTypeId;
    }

    public void setInvMovementTypeId(long invMovementTypeId) {
        this.invMovementTypeId = invMovementTypeId;
    }

    @Column(name = "inv_movementtypecode", unique = true, nullable = false, length = 30)
    public String getInvMovementTypeCode() {
        return this.invMovementTypeCode;
    }

    public void setInvMovementTypeCode(String invMovementTypeCode) {
        this.invMovementTypeCode = invMovementTypeCode;
    }

    @Column(name = "inv_movementtypedescription")
    public String getInvMovementTypeDescription() {
        return this.invMovementTypeDescription;
    }

    public void setInvMovementTypeDescription(String invMovementTypeDescription) {
        this.invMovementTypeDescription = invMovementTypeDescription;
    }

    @Column(name = "inv_movementtypeupdatedate")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getInvMovementTypeUpdateDate() {
        return invMovementTypeUpdateDate;
    }

    public void setInvMovementTypeUpdateDate(Date invMovementTypeUpdateDate) {
        this.invMovementTypeUpdateDate = invMovementTypeUpdateDate;
    }

    @Column(name = "inv_movementtypecreationdate")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getInvMovementTypeCreationDate() {
        return invMovementTypeCreationDate;
    }

    public void setInvMovementTypeCreationDate(Date invMovementTypeCreationDate) {
        this.invMovementTypeCreationDate = invMovementTypeCreationDate;
    }

    @Column(name = "inv_movementtypeactive")
    public Boolean getInvMovementTypeActive() {
        return invMovementTypeActive;
    }

    public void setInvMovementTypeActive(Boolean invMovementTypeActive) {
        this.invMovementTypeActive = invMovementTypeActive;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inv_movementtypeorganisationid")
    public OrgOrganisation getOrgOrganisation() {
        return orgOrganisation;
    }

    public void setOrgOrganisation(OrgOrganisation orgOrganisation) {
        this.orgOrganisation = orgOrganisation;
    }
}
