package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;

/**
 * LocAisle generated by hbm2java
 */
@Entity
@Table(name = "loc_aisle", uniqueConstraints = {
        @UniqueConstraint(columnNames = "loc_aislecode")})
public class LocAisle implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 4757291538037879101L;

    private long locAisleId;
    @NotNull
    private LocZone locZone;
    @NotNull
    private WrhWarehouse wrhWarehouse;
    @Size(max = 30)
    @NotNull
    private String locAisleCode;
    private boolean locAisleIsActive;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date locAisleCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date locAisleUpdateDate;
    private PrmLocationStatus prmLocationStatus;
    private Long locAisleOrder;
    private Long locAislePriority;
    private Long locAislelength;

    public LocAisle() {
    }

    public LocAisle(long locAisleId, LocZone locZone,
                    WrhWarehouse wrhWarehouse, String locAisleCode,
                    boolean locAisleIsActive) {
        this.locAisleId = locAisleId;
        this.locZone = locZone;
        this.wrhWarehouse = wrhWarehouse;
        this.locAisleCode = locAisleCode;
        this.locAisleIsActive = locAisleIsActive;
    }

    public LocAisle(long locAisleId, LocZone locZone,
                    WrhWarehouse wrhWarehouse, String locAisleCode,
                    boolean locAisleIsActive, Date locAisleCreationDate,
                    Date locAisleUpdateDate) {
        this.locAisleId = locAisleId;
        this.locZone = locZone;
        this.wrhWarehouse = wrhWarehouse;
        this.locAisleCode = locAisleCode;
        this.locAisleIsActive = locAisleIsActive;
        this.locAisleCreationDate = locAisleCreationDate;
        this.locAisleUpdateDate = locAisleUpdateDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_loc_aisle", allocationSize = 1)
    @Column(name = "loc_aisleid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getLocAisleId() {
        return this.locAisleId;
    }

    public void setLocAisleId(long locAisleId) {
        this.locAisleId = locAisleId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loc_aislezoneid", nullable = false)
    public LocZone getLocZone() {
        return this.locZone;
    }

    public void setLocZone(LocZone locZone) {
        this.locZone = locZone;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loc_aislewarehouseid", nullable = false)
    public WrhWarehouse getWrhWarehouse() {
        return this.wrhWarehouse;
    }

    public void setWrhWarehouse(WrhWarehouse wrhWarehouse) {
        this.wrhWarehouse = wrhWarehouse;
    }

    @Column(name = "loc_aislecode", unique = true, nullable = false, length = 30)
    public String getLocAisleCode() {
        return this.locAisleCode;
    }

    public void setLocAisleCode(String locAisleCode) {
        this.locAisleCode = locAisleCode;
    }

    @Column(name = "loc_aisleisactive", nullable = false)
    public boolean isLocAisleIsActive() {
        return this.locAisleIsActive;
    }

    public void setLocAisleIsActive(boolean locAisleIsActive) {
        this.locAisleIsActive = locAisleIsActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "loc_aislecreationdate")
    public Date getLocAisleCreationDate() {
        return this.locAisleCreationDate;
    }

    public void setLocAisleCreationDate(Date locAisleCreationDate) {
        this.locAisleCreationDate = locAisleCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "loc_aisleupdatedate")
    public Date getLocAisleUpdateDate() {
        return this.locAisleUpdateDate;
    }

    public void setLocAisleUpdateDate(Date locAisleUpdateDate) {
        this.locAisleUpdateDate = locAisleUpdateDate;
    }
    @Column(name = "loc_aisleorder")
    public Long getLocAisleOrder() {
        return locAisleOrder;
    }

    public void setLocAisleOrder(Long locAisleOrder) {
        this.locAisleOrder = locAisleOrder;
    }

    @Column(name = "loc_aislepriority")
    public Long getLocAislePriority() {
        return locAislePriority;
    }

    public void setLocAislePriority(Long locAislePriority) {
        this.locAislePriority = locAislePriority;
    }
    @Column(name = "loc_aislelength")
    public Long getLocAislelength() {
        return locAislelength;
    }

    public void setLocAislelength(Long locAislelength) {
        this.locAislelength = locAislelength;
    }
}
