package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LocZone generated by hbm2java
 */
@Entity
@Table(name = "loc_zone", uniqueConstraints = {
        @UniqueConstraint(columnNames = "loc_zonecode")})
public class LocZone implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1336599808939321370L;

    private long locZoneId;
    @NotNull
    @Size(max = 30)
    private String locZoneCode;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date locZoneCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date locZoneUpdateDate;
    @Size(max=255)
    private String LocZoneDescription;
    private Set<LocLocation> locLocations = new HashSet<LocLocation>(0);
    private Set<LocAisle> locAisles = new HashSet<LocAisle>(0);
    private Set<LocZoneWarehouse> locZoneWarehouses;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_loc_zone", allocationSize = 1)
    @Column(name = "loc_zoneid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getLocZoneId() {
        return this.locZoneId;
    }

    public void setLocZoneId(long locZoneId) {
        this.locZoneId = locZoneId;
    }


    @Column(name = "loc_zonecode", unique = true, nullable = false, length = 30)
    public String getLocZoneCode() {
        return this.locZoneCode;
    }

    public void setLocZoneCode(String locZoneCode) {
        this.locZoneCode = locZoneCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "loc_zonecreationdate")
    public Date getLocZoneCreationDate() {
        return this.locZoneCreationDate;
    }

    public void setLocZoneCreationDate(Date locZoneCreationDate) {
        this.locZoneCreationDate = locZoneCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "loc_zoneupdatedate")
    public Date getLocZoneUpdateDate() {
        return this.locZoneUpdateDate;
    }

    public void setLocZoneUpdateDate(Date locZoneUpdateDate) {
        this.locZoneUpdateDate = locZoneUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "locZone")
    public Set<LocLocation> getLocLocations() {
        return this.locLocations;
    }

    public void setLocLocations(Set<LocLocation> locLocations) {
        this.locLocations = locLocations;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "locZone")
    public Set<LocAisle> getLocAisles() {
        return this.locAisles;
    }

    public void setLocAisles(Set<LocAisle> locAisles) {
        this.locAisles = locAisles;
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "locZone")
    public Set<LocZoneWarehouse> getLocZoneWarehouses() {
        return locZoneWarehouses;
    }

    public void setLocZoneWarehouses(Set<LocZoneWarehouse> locZoneWarehouses) {
        this.locZoneWarehouses = locZoneWarehouses;
    }
    @Column(name = "loc_zonedescription",length = 255)
    public String getLocZoneDescription() {
        return LocZoneDescription;
    }

    public void setLocZoneDescription(String locZoneDescription) {
        LocZoneDescription = locZoneDescription;
    }
}
