package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PdtAlias generated by hbm2java
 */
@Entity
@Table(name = "pdt_alias", uniqueConstraints = {
        @UniqueConstraint(columnNames = "pdt_aliaseancode")})
public class PdtAlias implements java.io.Serializable {

    private long pdtAliasId;
    @NotNull
    private OwnOwner ownOwner;
    private PdtProduct pdtProduct;

    private PdtUom pdtUom;
    @Size(max = 30)
    @NotNull
    private String pdtAliasEanCode;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date pdtAliasCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date pdtAliasUpdateDate;
    private Set<PdtProductPack> pdtProductPacks = new HashSet<PdtProductPack>(0);

    public PdtAlias() {
    }

    public PdtAlias(long pdtAliasId, OwnOwner ownOwner, PdtProduct pdtProduct,
                    PdtUom pdtUom, String pdtAliasEanCode) {
        this.pdtAliasId = pdtAliasId;
        this.ownOwner = ownOwner;
        this.pdtProduct = pdtProduct;
        this.pdtUom = pdtUom;
        this.pdtAliasEanCode = pdtAliasEanCode;
    }

    public PdtAlias(long pdtAliasId, OwnOwner ownOwner, PdtProduct pdtProduct,
                    PdtUom pdtUom, String pdtAliasEanCode,
                    Date pdtAliasCreationDate, Date pdtAliasUpdateDate,
                    Set<PdtProductPack> pdtProductPacks) {
        this.pdtAliasId = pdtAliasId;
        this.ownOwner = ownOwner;
        this.pdtProduct = pdtProduct;
        this.pdtUom = pdtUom;
        this.pdtAliasEanCode = pdtAliasEanCode;
        this.pdtAliasCreationDate = pdtAliasCreationDate;
        this.pdtAliasUpdateDate = pdtAliasUpdateDate;
        this.pdtProductPacks = pdtProductPacks;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_pdt_alias", allocationSize = 1)
    @Column(name = "pdt_aliasid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPdtAliasId() {
        return this.pdtAliasId;
    }

    public void setPdtAliasId(long pdtAliasId) {
        this.pdtAliasId = pdtAliasId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_aliasownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_aliaspdtid", nullable = false)
    public PdtProduct getPdtProduct() {
        return this.pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_aliasuomid")
    public PdtUom getPdtUom() {
        return this.pdtUom;
    }

    public void setPdtUom(PdtUom pdtUom) {
        this.pdtUom = pdtUom;
    }

    @Column(name = "pdt_aliaseancode", unique = true, nullable = false, length = 20)
    public String getPdtAliasEanCode() {
        return this.pdtAliasEanCode;
    }

    public void setPdtAliasEanCode(String pdtAliasEanCode) {
        this.pdtAliasEanCode = pdtAliasEanCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pdt_aliascreationdate")
    public Date getPdtAliasCreationDate() {
        return this.pdtAliasCreationDate;
    }

    public void setPdtAliasCreationDate(Date pdtAliasCreationDate) {
        this.pdtAliasCreationDate = pdtAliasCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pdt_aliasupdatedate")
    public Date getPdtAliasUpdateDate() {
        return this.pdtAliasUpdateDate;
    }

    public void setPdtAliasUpdateDate(Date pdtAliasUpdateDate) {
        this.pdtAliasUpdateDate = pdtAliasUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtAlias")
    public Set<PdtProductPack> getPdtProductPacks() {
        return this.pdtProductPacks;
    }

    public void setPdtProductPacks(Set<PdtProductPack> pdtProductPacks) {
        this.pdtProductPacks = pdtProductPacks;
    }

}
