package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PdtProduct generated by hbm2java
 */
@Entity
@Table(name = "pdt_product", uniqueConstraints = {
        @UniqueConstraint(columnNames = "pdt_productcode")})
public class PdtProduct implements java.io.Serializable {

    private long pdtProductId;
    private LocLocation locLocation;
    @NotNull
    private OwnOwner ownOwner;
    private PdtProduct pdtProductParent;
    private PdtProductType pdtProductTypeByPdtProductTypeId;
    private PdtProductType pdtProductTypeByPdtProductSubTypeId;
    private PdtUom pdtUomByPdtProductUomSaleId;
    private PdtUom pdtUomByPdtProductUomBaseId;
    private PdtUom pdtUomByPdtProductUomPurshaseId;
    private PrmBlockType prmBlockType;
    private Set<PrmImage> prmImages;
    private RcpSupplier rcpSupplier;
    private WrhWarehouse wrhWarehouse;

    @Size(max = 30)
    @NotNull
    private String pdtProductCode;
    @Size(max = 1)
    @NotNull
    private String pdtProductMaterialABCCode;
    private Boolean pdtProductDlcControl;
    private Boolean pdtProductDluoControl;
    private Boolean pdtProductSerialNoControl;
    private Boolean pdtProductLotControl;
    private Boolean pdtProductColorControl;
    private Boolean pdtProductControlWeight;

    private BigDecimal pdtProductCoefficient;
    private BigDecimal pdtProductProductionCost;
    //TODO

    @Max(999999999)
    private Long pdtProductSuppOfLife;
    @Max(999999999)
    private BigDecimal pdtProductSalePriceUB;
    @Max(999999999)
    private BigDecimal pdtProductPurshasePriceUB;
    //TODO Value 1 to LIFO, 2 to FIFO, 3 to CUMB, 4 to NIFO
    @Max(999999999)
    private Long pdtProductRaisonToOut;
    @Size(max = 255)
    private String pdtProductDesc;
    @Size(max = 80)
    private String pdtProductShortDesc;
    private Integer pdtProductDaysOfLife;
    private Byte pdtProductContainerStack;
    @Size(max = 80)
    private String pdtProductPickMessage;
    @Size(max = 80)
    private String pdtProductManipulationDesc;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductMinTemp;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductMaxTemp;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductMaxStock;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductMinStock;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductManipulationPrice;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductPickingPrice;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductExpeditionPrice;

    @DecimalMax("999999999.0000")
    private BigDecimal pdtProductConditionningPrice;

    @Max(999999999)
    private Long pdtProductPaletConditionning;
    @NotNull
    private Boolean pdtProductIsActive;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date pdtProductCreationDate;

    private Boolean pdtProductIsKit;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date pdtProductUpdateDate;

    @Size(max = 255)
    private String pdtProductVariable1;
    @Size(max = 255)
    private String pdtProductVariable2;
    @Size(max = 255)
    private String pdtProductVariable3;
    @Size(max = 255)
    private String pdtProductVariable4;
    @Size(max = 255)
    private String pdtProductVariable5;
    @Size(max = 255)
    private String pdtProductVariable6;
    @Size(max = 255)
    private String pdtProductVariable7;
    @Size(max = 255)
    private String pdtProductVariable8;
    @Size(max = 255)
    private String pdtProductVariable9;
    @Size(max = 255)
    private String pdtProductVariable10;
    private Boolean pdtProductQualityOfControl;
    private BigDecimal pdtProductSamplingPercentage;
    private LocLocation pickingLocLocation;
    private PdtUom pickingPdtUom;
    private BigDecimal pdtMinimalThreshold;
    private BigDecimal pdtCapacity;
    private Boolean pdtIsReception;
    private PdtAlias pdtAlias;
    private PdtProductPack pdtProductPack;
    private Boolean pdtProductReqExp;
    private Boolean pdtProductReqRec;
    private Boolean pdtProductWarrantyManagement;
    private BigDecimal pdtProductDiscount;
    private PrmWarrantyPeriod prmWarrantyPeriod;
    private PrmCurrency prmCurrencySale;
    private PrmCurrency prmCurrencyPurshase;
    /* private Boolean pdtProductRawProduct;
     private Boolean pdtProductFinalProduct;
     private Boolean pdtProductSemiFinalProduct;
     private Boolean pdtProductKitComponent;*/
    private PdtProductForm pdtProductForm;
    private Boolean pdtProductDimension;
    private PdtProcess pdtProcess;

    private Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs = new HashSet<CmdSaleOrderLineArc>(
            0);
    private Set<CmdSaleOrderStock> cmdSaleOrderStocks = new HashSet<CmdSaleOrderStock>(
            0);
    private Set<RcpReceptionStock> rcpReceptionStocks = new HashSet<RcpReceptionStock>(
            0);
    private Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs = new HashSet<CmdSaleOrderStockArc>(
            0);
    private Set<PdtProduct> pdtProducts = new HashSet<PdtProduct>(0);
    private Set<RcpReceptionLine> rcpReceptionLines = new HashSet<RcpReceptionLine>(
            0);
    private Set<PdtProduct> pdtProducts_1 = new HashSet<PdtProduct>(0);
    private Set<StkStockArc> stkStockArcs = new HashSet<StkStockArc>(0);
    private Set<CmdSaleOrderLine> cmdSaleOrderLines = new HashSet<CmdSaleOrderLine>(
            0);
    private Set<StkStockReserved> stkStockReserveds = new HashSet<StkStockReserved>(
            0);
    private Set<RcpReceptionLineArc> rcpReceptionLineArcs = new HashSet<RcpReceptionLineArc>(
            0);
    private Set<PdtAlias> pdtAliases = new HashSet<PdtAlias>(0);
    private Set<PdtProductPack> pdtProductPacks = new HashSet<PdtProductPack>(0);
    private Set<RcpReceptionStockArc> rcpReceptionStockArcs = new HashSet<RcpReceptionStockArc>(
            0);
    private Set<StkStock> stkStocks = new HashSet<StkStock>(0);
    private Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines = new HashSet<RcpPurshaseOrderLine>(
            0);
    private Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs = new HashSet<RcpPurshaseOrderLineArc>(
            0);
    private Set<PdtProductDimension> pdtProductDimensions = new HashSet<PdtProductDimension>(0);
    private Long pdtProductVersion;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_pdt_product", allocationSize = 1)
    @Column(name = "pdt_productid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPdtProductId() {
        return this.pdtProductId;
    }

    public void setPdtProductId(long pdtProductId) {
        this.pdtProductId = pdtProductId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productlocationid")
    public LocLocation getLocLocation() {
        return this.locLocation;
    }

    public void setLocLocation(LocLocation locLocation) {
        this.locLocation = locLocation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productaliasid")
    public PdtAlias getPdtAlias() {
        return pdtAlias;
    }

    public void setPdtAlias(PdtAlias pdtAlias) {
        this.pdtAlias = pdtAlias;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productaltproductid")
    public PdtProduct getPdtProductParent() {
        return this.pdtProductParent;
    }

    public void setPdtProductParent(PdtProduct pdtProductParent) {
        this.pdtProductParent = pdtProductParent;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_producttypeid")
    public PdtProductType getPdtProductTypeByPdtProductTypeId() {
        return this.pdtProductTypeByPdtProductTypeId;
    }

    public void setPdtProductTypeByPdtProductTypeId(
            PdtProductType pdtProductTypeByPdtProductTypeId) {
        this.pdtProductTypeByPdtProductTypeId = pdtProductTypeByPdtProductTypeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productsubtypeid")
    public PdtProductType getPdtProductTypeByPdtProductSubTypeId() {
        return this.pdtProductTypeByPdtProductSubTypeId;
    }

    public void setPdtProductTypeByPdtProductSubTypeId(
            PdtProductType pdtProductTypeByPdtProductSubTypeId) {
        this.pdtProductTypeByPdtProductSubTypeId = pdtProductTypeByPdtProductSubTypeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productuomsaleid")
    public PdtUom getPdtUomByPdtProductUomSaleId() {
        return this.pdtUomByPdtProductUomSaleId;
    }

    public void setPdtUomByPdtProductUomSaleId(
            PdtUom pdtUomByPdtProductUomSaleId) {
        this.pdtUomByPdtProductUomSaleId = pdtUomByPdtProductUomSaleId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productuombaseid")
    public PdtUom getPdtUomByPdtProductUomBaseId() {
        return this.pdtUomByPdtProductUomBaseId;
    }

    public void setPdtUomByPdtProductUomBaseId(
            PdtUom pdtUomByPdtProductUomBaseId) {
        this.pdtUomByPdtProductUomBaseId = pdtUomByPdtProductUomBaseId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productuompurshaseid")
    public PdtUom getPdtUomByPdtProductUomPurshaseId() {
        return this.pdtUomByPdtProductUomPurshaseId;
    }

    public void setPdtUomByPdtProductUomPurshaseId(
            PdtUom pdtUomByPdtProductUomPurshaseId) {
        this.pdtUomByPdtProductUomPurshaseId = pdtUomByPdtProductUomPurshaseId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productdefaultblocktypeid")
    public PrmBlockType getPrmBlockType() {
        return this.prmBlockType;
    }

    public void setPrmBlockType(PrmBlockType prmBlockType) {
        this.prmBlockType = prmBlockType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<PrmImage> getPrmImages() {
        return prmImages;
    }

    public void setPrmImages(Set<PrmImage> prmImages) {
        this.prmImages = prmImages;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productdefaultsupplierid")
    public RcpSupplier getRcpSupplier() {
        return this.rcpSupplier;
    }

    public void setRcpSupplier(RcpSupplier rcpSupplier) {
        this.rcpSupplier = rcpSupplier;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productwarehouseid")
    public WrhWarehouse getWrhWarehouse() {
        return this.wrhWarehouse;
    }

    public void setWrhWarehouse(WrhWarehouse wrhWarehouse) {
        this.wrhWarehouse = wrhWarehouse;
    }

    @Column(name = "pdt_productsuppoflife", precision = 12, scale = 0)
    public Long getPdtProductSuppOfLife() {
        return pdtProductSuppOfLife;
    }

    public void setPdtProductSuppOfLife(Long pdtProductSuppOfLife) {
        this.pdtProductSuppOfLife = pdtProductSuppOfLife;
    }

    @Column(name = "pdt_productraisontoout", precision = 12, scale = 0)
    public Long getPdtProductRaisonToOut() {
        return pdtProductRaisonToOut;
    }

    public void setPdtProductRaisonToOut(Long pdtProductRaisonToOut) {
        this.pdtProductRaisonToOut = pdtProductRaisonToOut;
    }

    @Column(name = "pdt_productcode", unique = true, nullable = false, length = 30)
    public String getPdtProductCode() {
        return this.pdtProductCode;
    }

    public void setPdtProductCode(String pdtProductCode) {
        this.pdtProductCode = pdtProductCode;
    }

    @Column(name = "pdt_productpriceub")
    public BigDecimal getPdtProductSalePriceUB() {
        return pdtProductSalePriceUB;
    }

    public void setPdtProductSalePriceUB(BigDecimal pdtProductSalePriceUB) {
        this.pdtProductSalePriceUB = pdtProductSalePriceUB;
    }

    @Column(name = "pdt_productmaterialabccode", nullable = false, precision = 1, scale = 0)
    public String getPdtProductMaterialABCCode() {
        return this.pdtProductMaterialABCCode;
    }

    public void setPdtProductMaterialABCCode(String pdtProductMaterialABCCode) {
        this.pdtProductMaterialABCCode = pdtProductMaterialABCCode;
    }

    @Column(name = "pdt_productdlccontrol")
    public Boolean getPdtProductDlcControl() {
        return this.pdtProductDlcControl;
    }

    public void setPdtProductDlcControl(Boolean pdtProductDlcControl) {
        this.pdtProductDlcControl = pdtProductDlcControl;
    }

    @Column(name = "pdt_productdluocontrol")
    public Boolean getPdtProductDluoControl() {
        return this.pdtProductDluoControl;
    }

    public void setPdtProductDluoControl(Boolean pdtProductDluoControl) {
        this.pdtProductDluoControl = pdtProductDluoControl;
    }

    @Column(name = "pdt_productserialnocontrol")
    public Boolean getPdtProductSerialNoControl() {
        return this.pdtProductSerialNoControl;
    }

    public void setPdtProductSerialNoControl(Boolean pdtProductSerialNoControl) {
        this.pdtProductSerialNoControl = pdtProductSerialNoControl;
    }

    @Column(name = "pdt_productlotcontrol")
    public Boolean getPdtProductLotControl() {
        return this.pdtProductLotControl;
    }

    public void setPdtProductLotControl(Boolean pdtProductLotControl) {
        this.pdtProductLotControl = pdtProductLotControl;
    }

    @Column(name = "pdt_productcolorcontrol")
    public Boolean getPdtProductColorControl() {
        return this.pdtProductColorControl;
    }

    public void setPdtProductColorControl(Boolean pdtProductColorControl) {
        this.pdtProductColorControl = pdtProductColorControl;
    }

    @Column(name = "pdt_productdesc")
    public String getPdtProductDesc() {
        return this.pdtProductDesc;
    }

    public void setPdtProductDesc(String pdtProductDesc) {
        this.pdtProductDesc = pdtProductDesc;
    }

    @Column(name = "pdt_productshortdesc", length = 80)
    public String getPdtProductShortDesc() {
        return this.pdtProductShortDesc;
    }

    public void setPdtProductShortDesc(String pdtProductShortDesc) {
        this.pdtProductShortDesc = pdtProductShortDesc;
    }

    @Column(name = "pdt_productdaysoflife", precision = 6, scale = 0)
    public Integer getPdtProductDaysOfLife() {
        return this.pdtProductDaysOfLife;
    }

    public void setPdtProductDaysOfLife(Integer pdtProductDaysOfLife) {
        this.pdtProductDaysOfLife = pdtProductDaysOfLife;
    }

    @Column(name = "pdt_productcontainerstack", precision = 2, scale = 0)
    public Byte getPdtProductContainerStack() {
        return this.pdtProductContainerStack;
    }

    public void setPdtProductContainerStack(Byte pdtProductContainerStack) {
        this.pdtProductContainerStack = pdtProductContainerStack;
    }

    @Column(name = "pdt_productpickmessage", length = 80)
    public String getPdtProductPickMessage() {
        return this.pdtProductPickMessage;
    }

    public void setPdtProductPickMessage(String pdtProductPickMessage) {
        this.pdtProductPickMessage = pdtProductPickMessage;
    }

    @Column(name = "pdt_productmanipulationdesc", length = 80)
    public String getPdtProductManipulationDesc() {
        return this.pdtProductManipulationDesc;
    }

    public void setPdtProductManipulationDesc(String pdtProductManipulationDesc) {
        this.pdtProductManipulationDesc = pdtProductManipulationDesc;
    }

    @Column(name = "pdt_productmintemp", precision = 12, scale = 5)
    public BigDecimal getPdtProductMinTemp() {
        return this.pdtProductMinTemp;
    }

    public void setPdtProductMinTemp(BigDecimal pdtProductMinTemp) {
        this.pdtProductMinTemp = pdtProductMinTemp;
    }

    @Column(name = "pdt_productmaxtemp", precision = 17, scale = 5)
    public BigDecimal getPdtProductMaxTemp() {
        return this.pdtProductMaxTemp;
    }

    public void setPdtProductMaxTemp(BigDecimal pdtProductMaxTemp) {
        this.pdtProductMaxTemp = pdtProductMaxTemp;
    }

    @Column(name = "pdt_productmaxstock", precision = 17, scale = 5)
    public BigDecimal getPdtProductMaxStock() {
        return this.pdtProductMaxStock;
    }

    public void setPdtProductMaxStock(BigDecimal pdtProductMaxStock) {
        this.pdtProductMaxStock = pdtProductMaxStock;
    }

    @Column(name = "pdt_productminstock", precision = 17, scale = 5)
    public BigDecimal getPdtProductMinStock() {
        return this.pdtProductMinStock;
    }

    public void setPdtProductMinStock(BigDecimal pdtProductMinStock) {
        this.pdtProductMinStock = pdtProductMinStock;
    }

    @Column(name = "pdt_productmanipulationprice", precision = 17, scale = 5)
    public BigDecimal getPdtProductManipulationPrice() {
        return this.pdtProductManipulationPrice;
    }

    public void setPdtProductManipulationPrice(
            BigDecimal pdtProductManipulationPrice) {
        this.pdtProductManipulationPrice = pdtProductManipulationPrice;
    }

    @Column(name = "pdt_productpickingprice", precision = 17, scale = 5)
    public BigDecimal getPdtProductPickingPrice() {
        return this.pdtProductPickingPrice;
    }

    public void setPdtProductPickingPrice(BigDecimal pdtProductPickingPrice) {
        this.pdtProductPickingPrice = pdtProductPickingPrice;
    }

    @Column(name = "pdt_productexpeditionprice", precision = 17, scale = 5)
    public BigDecimal getPdtProductExpeditionPrice() {
        return this.pdtProductExpeditionPrice;
    }

    public void setPdtProductExpeditionPrice(
            BigDecimal pdtProductExpeditionPrice) {
        this.pdtProductExpeditionPrice = pdtProductExpeditionPrice;
    }

    @Column(name = "pdt_productconditionningprice", precision = 17, scale = 5)
    public BigDecimal getPdtProductConditionningPrice() {
        return this.pdtProductConditionningPrice;
    }

    public void setPdtProductConditionningPrice(
            BigDecimal pdtProductConditionningPrice) {
        this.pdtProductConditionningPrice = pdtProductConditionningPrice;
    }

    @Column(name = "pdt_productpaletconditionning", precision = 10, scale = 0)
    public Long getPdtProductPaletConditionning() {
        return this.pdtProductPaletConditionning;
    }

    public void setPdtProductPaletConditionning(
            Long pdtProductPaletConditionning) {
        this.pdtProductPaletConditionning = pdtProductPaletConditionning;
    }

    @Column(name = "pdt_productisactive", nullable = false)
    public Boolean getPdtProductIsActive() {
        return this.pdtProductIsActive;
    }

    public void setPdtProductIsActive(Boolean pdtProductIsActive) {
        this.pdtProductIsActive = pdtProductIsActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pdt_productcreationdate")
    public Date getPdtProductCreationDate() {
        return this.pdtProductCreationDate;
    }

    public void setPdtProductCreationDate(Date pdtProductCreationDate) {
        this.pdtProductCreationDate = pdtProductCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pdt_productupdatedate")
    public Date getPdtProductUpdateDate() {
        return this.pdtProductUpdateDate;
    }

    public void setPdtProductUpdateDate(Date pdtProductUpdateDate) {
        this.pdtProductUpdateDate = pdtProductUpdateDate;
    }

    @Column(name = "pdt_productvariable1")
    public String getPdtProductVariable1() {
        return this.pdtProductVariable1;
    }

    public void setPdtProductVariable1(String pdtProductVariable1) {
        this.pdtProductVariable1 = pdtProductVariable1;
    }

    @Column(name = "pdt_productvariable2")
    public String getPdtProductVariable2() {
        return this.pdtProductVariable2;
    }

    public void setPdtProductVariable2(String pdtProductVariable2) {
        this.pdtProductVariable2 = pdtProductVariable2;
    }

    @Column(name = "pdt_productvariable3")
    public String getPdtProductVariable3() {
        return this.pdtProductVariable3;
    }

    public void setPdtProductVariable3(String pdtProductVariable3) {
        this.pdtProductVariable3 = pdtProductVariable3;
    }

    @Column(name = "pdt_productvariable4")
    public String getPdtProductVariable4() {
        return this.pdtProductVariable4;
    }

    public void setPdtProductVariable4(String pdtProductVariable4) {
        this.pdtProductVariable4 = pdtProductVariable4;
    }

    @Column(name = "pdt_productvariable5")
    public String getPdtProductVariable5() {
        return this.pdtProductVariable5;
    }

    public void setPdtProductVariable5(String pdtProductVariable5) {
        this.pdtProductVariable5 = pdtProductVariable5;
    }

    @Column(name = "pdt_productvariable6")
    public String getPdtProductVariable6() {
        return this.pdtProductVariable6;
    }

    public void setPdtProductVariable6(String pdtProductVariable6) {
        this.pdtProductVariable6 = pdtProductVariable6;
    }

    @Column(name = "pdt_productvariable7")
    public String getPdtProductVariable7() {
        return this.pdtProductVariable7;
    }

    public void setPdtProductVariable7(String pdtProductVariable7) {
        this.pdtProductVariable7 = pdtProductVariable7;
    }

    @Column(name = "pdt_productvariable8")
    public String getPdtProductVariable8() {
        return this.pdtProductVariable8;
    }

    public void setPdtProductVariable8(String pdtProductVariable8) {
        this.pdtProductVariable8 = pdtProductVariable8;
    }

    @Column(name = "pdt_productvariable9")
    public String getPdtProductVariable9() {
        return this.pdtProductVariable9;
    }

    public void setPdtProductVariable9(String pdtProductVariable9) {
        this.pdtProductVariable9 = pdtProductVariable9;
    }

    @Column(name = "pdt_productvariable10")
    public String getPdtProductVariable10() {
        return this.pdtProductVariable10;
    }

    public void setPdtProductVariable10(String pdtProductVariable10) {
        this.pdtProductVariable10 = pdtProductVariable10;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<CmdSaleOrderLineArc> getCmdSaleOrderLineArcs() {
        return this.cmdSaleOrderLineArcs;
    }

    public void setCmdSaleOrderLineArcs(
            Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs) {
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<CmdSaleOrderStock> getCmdSaleOrderStocks() {
        return this.cmdSaleOrderStocks;
    }

    public void setCmdSaleOrderStocks(Set<CmdSaleOrderStock> cmdSaleOrderStocks) {
        this.cmdSaleOrderStocks = cmdSaleOrderStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<RcpReceptionStock> getRcpReceptionStocks() {
        return this.rcpReceptionStocks;
    }

    public void setRcpReceptionStocks(Set<RcpReceptionStock> rcpReceptionStocks) {
        this.rcpReceptionStocks = rcpReceptionStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<CmdSaleOrderStockArc> getCmdSaleOrderStockArcs() {
        return this.cmdSaleOrderStockArcs;
    }

    public void setCmdSaleOrderStockArcs(
            Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs) {
        this.cmdSaleOrderStockArcs = cmdSaleOrderStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProductParent")
    public Set<PdtProduct> getPdtProducts() {
        return this.pdtProducts;
    }

    public void setPdtProducts(Set<PdtProduct> pdtProducts) {
        this.pdtProducts = pdtProducts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<RcpReceptionLine> getRcpReceptionLines() {
        return this.rcpReceptionLines;
    }

    public void setRcpReceptionLines(Set<RcpReceptionLine> rcpReceptionLines) {
        this.rcpReceptionLines = rcpReceptionLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProductParent")
    public Set<PdtProduct> getPdtProducts_1() {
        return this.pdtProducts_1;
    }

    public void setPdtProducts_1(Set<PdtProduct> pdtProducts_1) {
        this.pdtProducts_1 = pdtProducts_1;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<StkStockArc> getStkStockArcs() {
        return this.stkStockArcs;
    }

    public void setStkStockArcs(Set<StkStockArc> stkStockArcs) {
        this.stkStockArcs = stkStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<CmdSaleOrderLine> getCmdSaleOrderLines() {
        return this.cmdSaleOrderLines;
    }

    public void setCmdSaleOrderLines(Set<CmdSaleOrderLine> cmdSaleOrderLines) {
        this.cmdSaleOrderLines = cmdSaleOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<StkStockReserved> getStkStockReserveds() {
        return this.stkStockReserveds;
    }

    public void setStkStockReserveds(Set<StkStockReserved> stkStockReserveds) {
        this.stkStockReserveds = stkStockReserveds;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<RcpReceptionLineArc> getRcpReceptionLineArcs() {
        return this.rcpReceptionLineArcs;
    }

    public void setRcpReceptionLineArcs(
            Set<RcpReceptionLineArc> rcpReceptionLineArcs) {
        this.rcpReceptionLineArcs = rcpReceptionLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<PdtAlias> getPdtAliases() {
        return this.pdtAliases;
    }

    public void setPdtAliases(Set<PdtAlias> pdtAliases) {
        this.pdtAliases = pdtAliases;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct", cascade = CascadeType.ALL)
    public Set<PdtProductPack> getPdtProductPacks() {
        return this.pdtProductPacks;
    }

    public void setPdtProductPacks(Set<PdtProductPack> pdtProductPacks) {
        this.pdtProductPacks = pdtProductPacks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<RcpReceptionStockArc> getRcpReceptionStockArcs() {
        return this.rcpReceptionStockArcs;
    }

    public void setRcpReceptionStockArcs(
            Set<RcpReceptionStockArc> rcpReceptionStockArcs) {
        this.rcpReceptionStockArcs = rcpReceptionStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<StkStock> getStkStocks() {
        return this.stkStocks;
    }

    public void setStkStocks(Set<StkStock> stkStocks) {
        this.stkStocks = stkStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<RcpPurshaseOrderLine> getRcpPurshaseOrderLines() {
        return this.rcpPurshaseOrderLines;
    }

    public void setRcpPurshaseOrderLines(
            Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines) {
        this.rcpPurshaseOrderLines = rcpPurshaseOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct")
    public Set<RcpPurshaseOrderLineArc> getRcpPurshaseOrderLineArcs() {
        return this.rcpPurshaseOrderLineArcs;
    }

    public void setRcpPurshaseOrderLineArcs(
            Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs) {
        this.rcpPurshaseOrderLineArcs = rcpPurshaseOrderLineArcs;
    }

    @Column(name = "pdt_productiskit")
    public Boolean getPdtProductIsKit() {
        return pdtProductIsKit;
    }

    public void setPdtProductIsKit(Boolean pdtProductIsKit) {
        this.pdtProductIsKit = pdtProductIsKit;
    }

    @Column(name = "pdt_productqualityofcontrol")
    public Boolean getPdtProductQualityOfControl() {
        return pdtProductQualityOfControl;
    }

    public void setPdtProductQualityOfControl(Boolean pdtProductQualityOfControl) {
        this.pdtProductQualityOfControl = pdtProductQualityOfControl;
    }

    @Column(name = "pdt_productsamplingpercentage")

    public BigDecimal getPdtProductSamplingPercentage() {
        return pdtProductSamplingPercentage;
    }

    public void setPdtProductSamplingPercentage(BigDecimal pdtProductSamplingPercentage) {
        this.pdtProductSamplingPercentage = pdtProductSamplingPercentage;
    }

    @ManyToOne
    @JoinColumn(name = "pdt_productproductpackid")
    public PdtProductPack getPdtProductPack() {
        return pdtProductPack;
    }

    public void setPdtProductPack(PdtProductPack pdtProductPack) {
        this.pdtProductPack = pdtProductPack;
    }

    @ManyToOne
    @JoinColumn(name = "pdt_productpickinglocationid")
    public LocLocation getPickingLocLocation() {
        return pickingLocLocation;
    }

    public void setPickingLocLocation(LocLocation pickingLocLocation) {
        this.pickingLocLocation = pickingLocLocation;
    }

    @ManyToOne
    @JoinColumn(name = "pdt_productpickinguomid")
    public PdtUom getPickingPdtUom() {
        return pickingPdtUom;
    }

    public void setPickingPdtUom(PdtUom pickingPdtUom) {
        this.pickingPdtUom = pickingPdtUom;
    }

    @Column(name = "pdt_productcapacity")
    public BigDecimal getPdtCapacity() {
        return pdtCapacity;
    }

    public void setPdtCapacity(BigDecimal pdtCapacity) {
        this.pdtCapacity = pdtCapacity;
    }

    @Column(name = "pdt_productisreception")
    public Boolean getPdtIsReception() {
        return pdtIsReception;
    }

    public void setPdtIsReception(Boolean pdtIsReception) {
        this.pdtIsReception = pdtIsReception;
    }

    @Column(name = "pdt_productminimalthreshold")
    public BigDecimal getPdtMinimalThreshold() {
        return pdtMinimalThreshold;
    }

    public void setPdtMinimalThreshold(BigDecimal pdtMinimalThreshold) {
        this.pdtMinimalThreshold = pdtMinimalThreshold;

    }

    @Column(name = "pdt_productreqexp")

    public Boolean getPdtProductReqExp() {
        return pdtProductReqExp;
    }

    public void setPdtProductReqExp(Boolean pdtProductReqExp) {
        this.pdtProductReqExp = pdtProductReqExp;
    }

    @Column(name = "pdt_productreqrec")

    public Boolean getPdtProductReqRec() {
        return pdtProductReqRec;
    }

    public void setPdtProductReqRec(Boolean pdtProductReqRec) {
        this.pdtProductReqRec = pdtProductReqRec;
    }

    @Column(name = "pdt_productcontrolweight")
    public Boolean getPdtProductControlWeight() {
        return pdtProductControlWeight;
    }

    public void setPdtProductControlWeight(Boolean pdtProductControlWeight) {
        this.pdtProductControlWeight = pdtProductControlWeight;
    }

    @Column(name = "pdt_productwarrantymanagement")

    public Boolean getPdtProductWarrantyManagement() {
        return pdtProductWarrantyManagement;
    }

    public void setPdtProductWarrantyManagement(Boolean pdtProductWarrantyManagement) {
        this.pdtProductWarrantyManagement = pdtProductWarrantyManagement;
    }

    @Column(name = "pdt_productdiscount")
    public BigDecimal getPdtProductDiscount() {
        return pdtProductDiscount;
    }

    public void setPdtProductDiscount(BigDecimal pdtProductDiscount) {
        this.pdtProductDiscount = pdtProductDiscount;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_productwarrantyperiodid")

    public PrmWarrantyPeriod getPrmWarrantyPeriod() {
        return prmWarrantyPeriod;
    }

    public void setPrmWarrantyPeriod(PrmWarrantyPeriod prmWarrantyPeriod) {
        this.prmWarrantyPeriod = prmWarrantyPeriod;
    }

    @Column(name = "pdt_productpurshasepriceub")

    public BigDecimal getPdtProductPurshasePriceUB() {
        return pdtProductPurshasePriceUB;
    }

    public void setPdtProductPurshasePriceUB(BigDecimal pdtProductPurshasePriceUB) {
        this.pdtProductPurshasePriceUB = pdtProductPurshasePriceUB;
    }

    @JoinColumn(name = "pdt_productcurrencyid")
    @ManyToOne(fetch = FetchType.LAZY)
    public PrmCurrency getPrmCurrencySale() {
        return prmCurrencySale;
    }

    public void setPrmCurrencySale(PrmCurrency prmCurrencySale) {
        this.prmCurrencySale = prmCurrencySale;
    }

    @JoinColumn(name = "pdt_productformid")
    @ManyToOne(fetch = FetchType.LAZY)
    public PdtProductForm getPdtProductForm() {
        return pdtProductForm;
    }

    public void setPdtProductForm(PdtProductForm pdtProductForm) {
        this.pdtProductForm = pdtProductForm;
    }

    @JoinColumn(name = "pdt_productcurrencypurshaseid")
    @ManyToOne(fetch = FetchType.LAZY)
    public PrmCurrency getPrmCurrencyPurshase() {
        return prmCurrencyPurshase;
    }

    public void setPrmCurrencyPurshase(PrmCurrency prmCurrencyPurshase) {
        this.prmCurrencyPurshase = prmCurrencyPurshase;
    }

    @Column(name = "pdt_productdimension")
    public Boolean getPdtProductDimension() {
        return pdtProductDimension;
    }

    public void setPdtProductDimension(Boolean pdtProductDimension) {
        this.pdtProductDimension = pdtProductDimension;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtProduct", cascade = CascadeType.ALL,orphanRemoval = true)
    public Set<PdtProductDimension> getPdtProductDimensions() {
        return pdtProductDimensions;
    }

    public void setPdtProductDimensions(Set<PdtProductDimension> pdtProductDimensions) {
        this.pdtProductDimensions = pdtProductDimensions;
    }

    @Column(name = "pdt_productcoefficient")
    public BigDecimal getPdtProductCoefficient() {
        return pdtProductCoefficient;
    }

    public void setPdtProductCoefficient(BigDecimal pdtProductCoefficient) {
        this.pdtProductCoefficient = pdtProductCoefficient;
    }
@Column(name = "pdt_productproductioncost")
    public BigDecimal getPdtProductProductionCost() {
        return pdtProductProductionCost;
    }

    public void setPdtProductProductionCost(BigDecimal pdtProductProductionCost) {
        this.pdtProductProductionCost = pdtProductProductionCost;
    }
    @Column(name="pdt_productversion")
    public Long getPdtProductVersion() {
        return pdtProductVersion;
    }

    public void setPdtProductVersion(Long pdtProductVersion) {
        this.pdtProductVersion = pdtProductVersion;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="pdt_productprocessid")
    public PdtProcess getPdtProcess() {
        return pdtProcess;
    }

    public void setPdtProcess(PdtProcess pdtProcess) {
        this.pdtProcess = pdtProcess;
    }
}
