package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PdtUom generated by hbm2java
 */
@Entity
@Table(name = "pdt_uom", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"pdt_uomcode", "pdt_uomownerid"} )})
public class PdtUom implements java.io.Serializable {

    private long pdtUomId;
    private OwnOwner ownOwner;
    @Size(max = 30)
    private String pdtUomCode;
    @Size(max = 100)
    private String pdtUomDescription;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date pdtUomCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date pdtUomUpdateDate;
    private Set<CmdSaleOrderLine> cmdSaleOrderLines = new HashSet<CmdSaleOrderLine>(
            0);
    private Set<CmdSaleOrderStock> cmdSaleOrderStocks = new HashSet<CmdSaleOrderStock>(
            0);
    private Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines = new HashSet<RcpPurshaseOrderLine>(
            0);
    private Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs = new HashSet<CmdSaleOrderLineArc>(
            0);
    private Set<StkStockReserved> stkStockReserveds = new HashSet<StkStockReserved>(
            0);
    private Set<RcpReceptionLine> rcpReceptionLines = new HashSet<RcpReceptionLine>(
            0);
    private Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs = new HashSet<CmdSaleOrderStockArc>(
            0);
    private Set<PdtProduct> pdtProductsForPdtProductUomSaleId = new HashSet<PdtProduct>(
            0);
    private Set<PdtProduct> pdtProductsForPdtProductUomBaseId = new HashSet<PdtProduct>(
            0);
    private Set<PdtProduct> pdtProductsForPdtProductUomPurshaseId = new HashSet<PdtProduct>(
            0);
    private Set<PdtProductPack> pdtProductPacks = new HashSet<PdtProductPack>(0);
    private Set<StkStockArc> stkStockArcs = new HashSet<StkStockArc>(0);
    private Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs = new HashSet<RcpPurshaseOrderLineArc>(
            0);
    private Set<StkStock> stkStocks = new HashSet<StkStock>(0);
    private Set<RcpReceptionLineArc> rcpReceptionLineArcs = new HashSet<RcpReceptionLineArc>(
            0);

    public PdtUom() {
    }

    public PdtUom(long pdtUomId, OwnOwner ownOwner, String pdtUomCode) {
        this.pdtUomId = pdtUomId;
        this.ownOwner = ownOwner;
        this.pdtUomCode = pdtUomCode;
    }

    public PdtUom(long pdtUomId, OwnOwner ownOwner, String pdtUomCode,
                  String pdtUomDescription, Date pdtUomCreationDate,
                  Date pdtUomUpdateDate, Set<CmdSaleOrderLine> cmdSaleOrderLines,
                  Set<CmdSaleOrderStock> cmdSaleOrderStocks,
                  Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines,
                  Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs,
                  Set<StkStockReserved> stkStockReserveds,
                  Set<RcpReceptionLine> rcpReceptionLines,
                  Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs,
                  Set<PdtProduct> pdtProductsForPdtProductUomSaleId,
                  Set<PdtProduct> pdtProductsForPdtProductUomBaseId,
                  Set<PdtProduct> pdtProductsForPdtProductUomPurshaseId,
                  Set<PdtProductPack> pdtProductPacks, Set<StkStockArc> stkStockArcs,
                  Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs,
                  Set<StkStock> stkStocks,
                  Set<RcpReceptionLineArc> rcpReceptionLineArcs) {
        this.pdtUomId = pdtUomId;
        this.ownOwner = ownOwner;
        this.pdtUomCode = pdtUomCode;
        this.pdtUomDescription = pdtUomDescription;
        this.pdtUomCreationDate = pdtUomCreationDate;
        this.pdtUomUpdateDate = pdtUomUpdateDate;
        this.cmdSaleOrderLines = cmdSaleOrderLines;
        this.cmdSaleOrderStocks = cmdSaleOrderStocks;
        this.rcpPurshaseOrderLines = rcpPurshaseOrderLines;
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
        this.stkStockReserveds = stkStockReserveds;
        this.rcpReceptionLines = rcpReceptionLines;
        this.cmdSaleOrderStockArcs = cmdSaleOrderStockArcs;
        this.pdtProductsForPdtProductUomSaleId = pdtProductsForPdtProductUomSaleId;
        this.pdtProductsForPdtProductUomBaseId = pdtProductsForPdtProductUomBaseId;
        this.pdtProductsForPdtProductUomPurshaseId = pdtProductsForPdtProductUomPurshaseId;
        this.pdtProductPacks = pdtProductPacks;
        this.stkStockArcs = stkStockArcs;
        this.rcpPurshaseOrderLineArcs = rcpPurshaseOrderLineArcs;
        this.stkStocks = stkStocks;
        this.rcpReceptionLineArcs = rcpReceptionLineArcs;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_pdt_uom", allocationSize = 1)
    @Column(name = "pdt_uomid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPdtUomId() {
        return this.pdtUomId;
    }

    public void setPdtUomId(long pdtUomId) {
        this.pdtUomId = pdtUomId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pdt_uomownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @Column(name = "pdt_uomcode", nullable = false, length = 30)
    public String getPdtUomCode() {
        return this.pdtUomCode;
    }

    public void setPdtUomCode(String pdtUomCode) {
        this.pdtUomCode = pdtUomCode;
    }

    @Column(name = "pdt_uomdescription", length = 100)
    public String getPdtUomDescription() {
        return this.pdtUomDescription;
    }

    public void setPdtUomDescription(String pdtUomDescription) {
        this.pdtUomDescription = pdtUomDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pdt_uomcreationdate")
    public Date getPdtUomCreationDate() {
        return this.pdtUomCreationDate;
    }

    public void setPdtUomCreationDate(Date pdtUomCreationDate) {
        this.pdtUomCreationDate = pdtUomCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "pdt_uomupdatedate")
    public Date getPdtUomUpdateDate() {
        return this.pdtUomUpdateDate;
    }

    public void setPdtUomUpdateDate(Date pdtUomUpdateDate) {
        this.pdtUomUpdateDate = pdtUomUpdateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<CmdSaleOrderLine> getCmdSaleOrderLines() {
        return this.cmdSaleOrderLines;
    }

    public void setCmdSaleOrderLines(Set<CmdSaleOrderLine> cmdSaleOrderLines) {
        this.cmdSaleOrderLines = cmdSaleOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<CmdSaleOrderStock> getCmdSaleOrderStocks() {
        return this.cmdSaleOrderStocks;
    }

    public void setCmdSaleOrderStocks(Set<CmdSaleOrderStock> cmdSaleOrderStocks) {
        this.cmdSaleOrderStocks = cmdSaleOrderStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<RcpPurshaseOrderLine> getRcpPurshaseOrderLines() {
        return this.rcpPurshaseOrderLines;
    }

    public void setRcpPurshaseOrderLines(
            Set<RcpPurshaseOrderLine> rcpPurshaseOrderLines) {
        this.rcpPurshaseOrderLines = rcpPurshaseOrderLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<CmdSaleOrderLineArc> getCmdSaleOrderLineArcs() {
        return this.cmdSaleOrderLineArcs;
    }

    public void setCmdSaleOrderLineArcs(
            Set<CmdSaleOrderLineArc> cmdSaleOrderLineArcs) {
        this.cmdSaleOrderLineArcs = cmdSaleOrderLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<StkStockReserved> getStkStockReserveds() {
        return this.stkStockReserveds;
    }

    public void setStkStockReserveds(Set<StkStockReserved> stkStockReserveds) {
        this.stkStockReserveds = stkStockReserveds;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<RcpReceptionLine> getRcpReceptionLines() {
        return this.rcpReceptionLines;
    }

    public void setRcpReceptionLines(Set<RcpReceptionLine> rcpReceptionLines) {
        this.rcpReceptionLines = rcpReceptionLines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<CmdSaleOrderStockArc> getCmdSaleOrderStockArcs() {
        return this.cmdSaleOrderStockArcs;
    }

    public void setCmdSaleOrderStockArcs(
            Set<CmdSaleOrderStockArc> cmdSaleOrderStockArcs) {
        this.cmdSaleOrderStockArcs = cmdSaleOrderStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUomByPdtProductUomSaleId")
    public Set<PdtProduct> getPdtProductsForPdtProductUomSaleId() {
        return this.pdtProductsForPdtProductUomSaleId;
    }

    public void setPdtProductsForPdtProductUomSaleId(
            Set<PdtProduct> pdtProductsForPdtProductUomSaleId) {
        this.pdtProductsForPdtProductUomSaleId = pdtProductsForPdtProductUomSaleId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUomByPdtProductUomBaseId")
    public Set<PdtProduct> getPdtProductsForPdtProductUomBaseId() {
        return this.pdtProductsForPdtProductUomBaseId;
    }

    public void setPdtProductsForPdtProductUomBaseId(
            Set<PdtProduct> pdtProductsForPdtProductUomBaseId) {
        this.pdtProductsForPdtProductUomBaseId = pdtProductsForPdtProductUomBaseId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUomByPdtProductUomPurshaseId")
    public Set<PdtProduct> getPdtProductsForPdtProductUomPurshaseId() {
        return this.pdtProductsForPdtProductUomPurshaseId;
    }

    public void setPdtProductsForPdtProductUomPurshaseId(
            Set<PdtProduct> pdtProductsForPdtProductUomPurshaseId) {
        this.pdtProductsForPdtProductUomPurshaseId = pdtProductsForPdtProductUomPurshaseId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<PdtProductPack> getPdtProductPacks() {
        return this.pdtProductPacks;
    }

    public void setPdtProductPacks(Set<PdtProductPack> pdtProductPacks) {
        this.pdtProductPacks = pdtProductPacks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<StkStockArc> getStkStockArcs() {
        return this.stkStockArcs;
    }

    public void setStkStockArcs(Set<StkStockArc> stkStockArcs) {
        this.stkStockArcs = stkStockArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<RcpPurshaseOrderLineArc> getRcpPurshaseOrderLineArcs() {
        return this.rcpPurshaseOrderLineArcs;
    }

    public void setRcpPurshaseOrderLineArcs(
            Set<RcpPurshaseOrderLineArc> rcpPurshaseOrderLineArcs) {
        this.rcpPurshaseOrderLineArcs = rcpPurshaseOrderLineArcs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<StkStock> getStkStocks() {
        return this.stkStocks;
    }

    public void setStkStocks(Set<StkStock> stkStocks) {
        this.stkStocks = stkStocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtUom")
    public Set<RcpReceptionLineArc> getRcpReceptionLineArcs() {
        return this.rcpReceptionLineArcs;
    }

    public void setRcpReceptionLineArcs(
            Set<RcpReceptionLineArc> rcpReceptionLineArcs) {
        this.rcpReceptionLineArcs = rcpReceptionLineArcs;
    }
    @Override
    public boolean equals(Object object) {
        boolean result = false;
        if (object == null || object.getClass() != getClass()) {
            result = false;
        } else {
            PdtUom obj = (PdtUom) object;
            if (this.getPdtUomId() == obj.getPdtUomId()) {
                result = true;
            }
        }
        return result;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 7 * hash + (int) this.getPdtUomId();
        hash = 7 * hash + (int) this.getPdtUomId();
        return hash;
    }
}
