package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import javax.persistence.*;
import javax.validation.constraints.Size;

/**
 * PrmEdi generated by hbm2java
 */
@Entity
@Table(name = "prm_edi", uniqueConstraints = @UniqueConstraint(columnNames = "prm_edicode"))
public class PrmEdi implements java.io.Serializable {

    private long prmEdiId;
    @Size(max = 30)
    private String prmEdiCode;
    @Size(max = 255)
    private String prmEdiDescription;

    public PrmEdi() {
    }

    public PrmEdi(long prmEdiId, String prmEdiCode) {
        this.prmEdiId = prmEdiId;
        this.prmEdiCode = prmEdiCode;
    }

    public PrmEdi(long prmEdiId, String prmEdiCode, String prmEdiDescription) {
        this.prmEdiId = prmEdiId;
        this.prmEdiCode = prmEdiCode;
        this.prmEdiDescription = prmEdiDescription;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_prm_edi", allocationSize = 1)
    @Column(name = "prm_ediid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPrmEdiId() {
        return this.prmEdiId;
    }

    public void setPrmEdiId(long prmEdiId) {
        this.prmEdiId = prmEdiId;
    }

    @Column(name = "prm_edicode", unique = true, nullable = false, length = 30)
    public String getPrmEdiCode() {
        return this.prmEdiCode;
    }

    public void setPrmEdiCode(String prmEdiCode) {
        this.prmEdiCode = prmEdiCode;
    }

    @Column(name = "prm_edidescription")
    public String getPrmEdiDescription() {
        return this.prmEdiDescription;
    }

    public void setPrmEdiDescription(String prmEdiDescription) {
        this.prmEdiDescription = prmEdiDescription;
    }

}
