package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.HashSet;
import java.util.Set;

/**
 * PrmImage generated by hbm2java
 */
@Entity
@Table(name = "prm_image")
public class PrmImage implements java.io.Serializable {

    private long prmImageId;
    @NotNull
    private byte[] prmImageBytes;
    private PdtProduct pdtProduct;
    private String prmImageCode;
    private String prmImageDescription;

    public PrmImage() {
    }


    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_prm_image", allocationSize = 1)
    @Column(name = "prm_imageid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getPrmImageId() {
        return this.prmImageId;
    }

    public void setPrmImageId(long prmImageId) {
        this.prmImageId = prmImageId;
    }

    @Column(name="prm_imagebytes" ,nullable = false)
    public byte[] getPrmImageBytes() {
        return prmImageBytes;
    }

    public void setPrmImageBytes(byte[] prmImageBytes) {
        this.prmImageBytes = prmImageBytes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="prm_imageproductid")
    public PdtProduct getPdtProduct() {
        return pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }

    @Column(name = "prm_imagecode")
    public String getPrmImageCode() {
        return prmImageCode;
    }

    public void setPrmImageCode(String prmImageCode) {
        this.prmImageCode = prmImageCode;
    }
    @Column(name = "prm_imagedescription")

    public String getPrmImageDescription() {
        return prmImageDescription;
    }

    public void setPrmImageDescription(String prmImageDescription) {
        this.prmImageDescription = prmImageDescription;
    }
}
