package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;

/**
 * StkStockreserved generated by hbm2java
 */
@Entity
@Table(name = "stk_stockreserved")
public class StkStockReserved implements java.io.Serializable {

    private long stkStockReservedId;
    private CmdAccount cmdAccount;
    private CmdSaleOrder cmdSaleOrder;
    private CmdSaleOrderLine cmdSaleOrderLine;
    private OwnOwner ownOwner;
    @NotNull
    private PdtProduct pdtProduct;
    @NotNull
    private PdtUom pdtUom;
    private PrmBlockType prmBlockType;
    private PrmColor prmColor;
    private RcpSupplier rcpSupplier;
    private WrhWarehouse wrhWarehouse;

    @Max(999999999)
    @NotNull
    private BigDecimal stkStockReservedQuantity;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date stkStockReservedDlc;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date stkStockReservedDluo;
    @Size(max = 255)
    private String stkStockReservedSerialNo;
    @Size(max = 255)
    private String stkStockReservedLot;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date stkStockReservedReceptionDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date stkStockReservedCreationDate;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date stkStockReservedUpdateDate;
    @Size(max=50)
    private String stkStockReservedQuality;
    @Max(999999999)
    private BigDecimal stkStockReservedWeight;
    private PdtProductDimension pdtProductDimensionOld;
    private PdtProductDimension pdtProductDimensionNew;

    public StkStockReserved() {
    }

    public StkStockReserved(long stkStockReservedId, OwnOwner ownOwner,
                            PdtProduct pdtProduct, PdtUom pdtUom,
                            BigDecimal stkStockReservedQuantity) {
        this.stkStockReservedId = stkStockReservedId;
        this.ownOwner = ownOwner;
        this.pdtProduct = pdtProduct;
        this.pdtUom = pdtUom;
        this.stkStockReservedQuantity = stkStockReservedQuantity;
    }

    public StkStockReserved(long stkStockReservedId, CmdAccount cmdAccount,
                            CmdSaleOrder cmdSaleOrder, CmdSaleOrderLine cmdSaleOrderLine,
                            OwnOwner ownOwner, PdtProduct pdtProduct, PdtUom pdtUom,
                            PrmBlockType prmBlockType, PrmColor prmColor,
                            RcpSupplier rcpSupplier, WrhWarehouse wrhWarehouse,
                            BigDecimal stkStockReservedQuantity, Date stkStockReservedDlc,
                            Date stkStockReservedDluo, String stkStockReservedSerialNo,
                            String stkStockReservedLot, Date stkStockReservedReceptionDate,
                            Date stkStockReservedCreationDate, Date stkStockReservedUpdateDate) {
        this.stkStockReservedId = stkStockReservedId;
        this.cmdAccount = cmdAccount;
        this.cmdSaleOrder = cmdSaleOrder;
        this.cmdSaleOrderLine = cmdSaleOrderLine;
        this.ownOwner = ownOwner;
        this.pdtProduct = pdtProduct;
        this.pdtUom = pdtUom;
        this.prmBlockType = prmBlockType;
        this.prmColor = prmColor;
        this.rcpSupplier = rcpSupplier;
        this.wrhWarehouse = wrhWarehouse;
        this.stkStockReservedQuantity = stkStockReservedQuantity;
        this.stkStockReservedDlc = stkStockReservedDlc;
        this.stkStockReservedDluo = stkStockReservedDluo;
        this.stkStockReservedSerialNo = stkStockReservedSerialNo;
        this.stkStockReservedLot = stkStockReservedLot;
        this.stkStockReservedReceptionDate = stkStockReservedReceptionDate;
        this.stkStockReservedCreationDate = stkStockReservedCreationDate;
        this.stkStockReservedUpdateDate = stkStockReservedUpdateDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_stk_stockreserved", allocationSize = 1)
    @Column(name = "stk_stockreservedid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getStkStockReservedId() {
        return this.stkStockReservedId;
    }

    public void setStkStockReservedId(long stkStockReservedId) {
        this.stkStockReservedId = stkStockReservedId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedaccountid")
    public CmdAccount getCmdAccount() {
        return this.cmdAccount;
    }

    public void setCmdAccount(CmdAccount cmdAccount) {
        this.cmdAccount = cmdAccount;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedorder_id")
    public CmdSaleOrder getCmdSaleOrder() {
        return this.cmdSaleOrder;
    }

    public void setCmdSaleOrder(CmdSaleOrder cmdSaleOrder) {
        this.cmdSaleOrder = cmdSaleOrder;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedorderlineid")
    public CmdSaleOrderLine getCmdSaleOrderLine() {
        return this.cmdSaleOrderLine;
    }

    public void setCmdSaleOrderLine(CmdSaleOrderLine cmdSaleOrderLine) {
        this.cmdSaleOrderLine = cmdSaleOrderLine;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedownerid", nullable = false)
    public OwnOwner getOwnOwner() {
        return this.ownOwner;
    }

    public void setOwnOwner(OwnOwner ownOwner) {
        this.ownOwner = ownOwner;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedproductid", nullable = false)
    public PdtProduct getPdtProduct() {
        return this.pdtProduct;
    }

    public void setPdtProduct(PdtProduct pdtProduct) {
        this.pdtProduct = pdtProduct;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreserveduomid", nullable = false)
    public PdtUom getPdtUom() {
        return this.pdtUom;
    }

    public void setPdtUom(PdtUom pdtUom) {
        this.pdtUom = pdtUom;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedblockid")
    public PrmBlockType getPrmBlockType() {
        return this.prmBlockType;
    }

    public void setPrmBlockType(PrmBlockType prmBlockType) {
        this.prmBlockType = prmBlockType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedcolorid")
    public PrmColor getPrmColor() {
        return this.prmColor;
    }

    public void setPrmColor(PrmColor prmColor) {
        this.prmColor = prmColor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedsupplierid")
    public RcpSupplier getRcpSupplier() {
        return this.rcpSupplier;
    }

    public void setRcpSupplier(RcpSupplier rcpSupplier) {
        this.rcpSupplier = rcpSupplier;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedwarehouseid")
    public WrhWarehouse getWrhWarehouse() {
        return this.wrhWarehouse;
    }

    public void setWrhWarehouse(WrhWarehouse wrhWarehouse) {
        this.wrhWarehouse = wrhWarehouse;
    }

    @Column(name = "stk_stockreservedquantity", nullable = false, precision = 17, scale = 5)
    public BigDecimal getStkStockReservedQuantity() {
        return this.stkStockReservedQuantity;
    }

    public void setStkStockReservedQuantity(BigDecimal stkStockReservedQuantity) {
        this.stkStockReservedQuantity = stkStockReservedQuantity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "stk_stockreserveddlc", length = 13)
    public Date getStkStockReservedDlc() {
        return this.stkStockReservedDlc;
    }

    public void setStkStockReservedDlc(Date stkStockReservedDlc) {
        this.stkStockReservedDlc = stkStockReservedDlc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "stk_stockreserveddluo", length = 13)
    public Date getStkStockReservedDluo() {
        return this.stkStockReservedDluo;
    }

    public void setStkStockReservedDluo(Date stkStockReservedDluo) {
        this.stkStockReservedDluo = stkStockReservedDluo;
    }

    @Column(name = "stk_stockreservedserialno", length = 50)
    public String getStkStockReservedSerialNo() {
        return this.stkStockReservedSerialNo;
    }

    public void setStkStockReservedSerialNo(String stkStockReservedSerialNo) {
        this.stkStockReservedSerialNo = stkStockReservedSerialNo;
    }

    @Column(name = "stk_stockreservedlot", length = 50)
    public String getStkStockReservedLot() {
        return this.stkStockReservedLot;
    }

    public void setStkStockReservedLot(String stkStockReservedLot) {
        this.stkStockReservedLot = stkStockReservedLot;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "stk_stockreservedreceptiondate")
    public Date getStkStockReservedReceptionDate() {
        return this.stkStockReservedReceptionDate;
    }

    public void setStkStockReservedReceptionDate(
            Date stkStockReservedReceptionDate) {
        this.stkStockReservedReceptionDate = stkStockReservedReceptionDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "stk_stockreservedcreationdate")
    public Date getStkStockReservedCreationDate() {
        return this.stkStockReservedCreationDate;
    }

    public void setStkStockReservedCreationDate(
            Date stkStockReservedCreationDate) {
        this.stkStockReservedCreationDate = stkStockReservedCreationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "stk_stockreservedupdatedate")
    public Date getStkStockReservedUpdateDate() {
        return this.stkStockReservedUpdateDate;
    }

    public void setStkStockReservedUpdateDate(Date stkStockReservedUpdateDate) {
        this.stkStockReservedUpdateDate = stkStockReservedUpdateDate;
    }
    @Column(name = "stk_stockreservedquality",length = 50)

    public String getStkStockReservedQuality() {
        return stkStockReservedQuality;
    }

    public void setStkStockReservedQuality(String stkStockReservedQuality) {
        this.stkStockReservedQuality = stkStockReservedQuality;
    }
    @Column(name = "stk_stockreservedweight",precision = 10,scale =0 )

    public BigDecimal getStkStockReservedWeight() {
        return stkStockReservedWeight;
    }

    public void setStkStockReservedWeight(BigDecimal stkStockReservedWeight) {
        this.stkStockReservedWeight = stkStockReservedWeight;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedproductdimensionoldid")
    public PdtProductDimension getPdtProductDimensionOld() {
        return pdtProductDimensionOld;
    }

    public void setPdtProductDimensionOld(PdtProductDimension pdtProductDimensionOld) {
        this.pdtProductDimensionOld = pdtProductDimensionOld;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stk_stockreservedproductdimensionnewid")
    public PdtProductDimension getPdtProductDimensionNew() {
        return pdtProductDimensionNew;
    }

    public void setPdtProductDimensionNew(PdtProductDimension pdtProductDimensionNew) {
        this.pdtProductDimensionNew = pdtProductDimensionNew;
    }
}
