package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * UsrUseractions generated by hbm2java
 */
@Entity
@Table(name = "usr_useractions")
public class UsrUserActions implements java.io.Serializable {

    private static final long serialVersionUID = 1986884852046158809L;

    private long usrUserActionsId;
    @NotNull
    private UsrActions usrActions;
    @NotNull
    private UsrUser usrUser;
    @DateTimeFormat(pattern = "yyyy-MM-dd")

    private Date usrUserActionsCreationDate;

    public UsrUserActions() {
    }

    public UsrUserActions(long usrUserActionsId, UsrActions usrActions,
                          UsrUser usrUser) {
        this.usrUserActionsId = usrUserActionsId;
        this.usrActions = usrActions;
        this.usrUser = usrUser;
    }

    public UsrUserActions(long usrUserActionsId, UsrActions usrActions,
                          UsrUser usrUser, Date usrUserActionsCreationDate) {
        this.usrUserActionsId = usrUserActionsId;
        this.usrActions = usrActions;
        this.usrUser = usrUser;
        this.usrUserActionsCreationDate = usrUserActionsCreationDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    @SequenceGenerator(name = "seq", sequenceName = "seq_usr_useractions", allocationSize = 1)
    @Column(name = "usr_useractionsid", unique = true, nullable = false, precision = 10, scale = 0)
    public long getUsrUserActionsId() {
        return this.usrUserActionsId;
    }

    public void setUsrUserActionsId(long usrUserActionsId) {
        this.usrUserActionsId = usrUserActionsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usr_useractionsactionid", nullable = false)
    public UsrActions getUsrActions() {
        return this.usrActions;
    }

    public void setUsrActions(UsrActions usrActions) {
        this.usrActions = usrActions;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usr_useractionsuserid", nullable = false)
    public UsrUser getUsrUser() {
        return this.usrUser;
    }

    public void setUsrUser(UsrUser usrUser) {
        this.usrUser = usrUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "usr_useractionscreationdate")
    public Date getUsrUserActionsCreationDate() {
        return this.usrUserActionsCreationDate;
    }

    public void setUsrUserActionsCreationDate(Date usrUserActionsCreationDate) {
        this.usrUserActionsCreationDate = usrUserActionsCreationDate;
    }

}
