package com.sinno.ems.entities;

// Generated 8 mars 2015 01:55:29 by Hibernate Tools 4.3.1

import org.hibernate.validator.constraints.Email;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsrUser generated by hbm2java
 */
@Entity
@Table(name = "usr_user", uniqueConstraints = @UniqueConstraint(columnNames = "usr_useremail"))
public class UsrUser implements java.io.Serializable {

}